### ISSUE TITLE
[ISSUE] Elasticsearch fails to start when provided with image values

### ISSUE THREAD

**Issue by jpan8866** [camunda/camunda-platform-helm#1097]
**Describe the issue:**

Elastic search does not start when provided with image values. Seems to have something to do with volume mounting. 

**Actual behavior:**

The error is the following:
ERROR: Missing logging config file at /usr/share/elasticsearch/config/log4j2.properties
sometimes it will say jvm.options not found as well.

**Expected behavior:**

**How to reproduce:**
```
elasticsearch:
    image:
      registry: "artifactory.blabla.ca"
      repository: "bla"
      tag: latest
      pullSecrets: 
        - artifactory
      pullPolicy: Always
```

I wrote a custom image to include s3 plugin:
```
FROM artifactory.bla.ca/elasticsearch:8.8.2
RUN bin/elasticsearch-plugin install --batch repository-s3
```
**Logs:**

ERROR: Missing logging config file at /usr/share/elasticsearch/config/log4j2.properties

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: openshift 
- Helm CLI version: 3.13.1
- Chart version: 8.3.2
- Values file: see above
