### ISSUE TITLE
[ISSUE] identity cannot be accessed under a sub-path

### ISSUE THREAD

**Issue by linonetwo** [camunda/camunda-platform-helm#1110]
**Describe the issue:**

Same as https://github.com/camunda/camunda-platform-helm/issues/479 , but solution in that issue is probably not correct, when accessing http://camunda.example.com/ , it will redirect to http://camunda.example.com//auth/login (two slash), and showing a 404 not found page of keycloak

after fixing "identity cannot be accessed under a sub-path", I get 404

![截屏2023-12-05 17 50 28](https://github.com/camunda/camunda-platform-helm/assets/3746270/09cff54b-53d2-4d35-8c7c-9f7346cfab9b)

**Expected behavior:**

Install chart and keycloak, and access identity service in / path

**How to reproduce:**

I try to combine https://github.com/camunda/camunda-platform-helm/blob/main/kind/camunda-platform-core-kind-values.yaml and https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup/

for my microk8s single node cluster.

diff here

```yaml
global:
  ingress:
    enabled: true
    host: "my.domain"
  identity:
    auth:
      publicIssuerUrl: "http://my.domain/auth/realms/camunda-platform"
      operate:
        redirectUrl: "http://my.domain/operate"
      tasklist:
        redirectUrl: "http://my.domain/tasklist"
      optimize:
        redirectUrl: "http://my.domain/optimize"
# Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# to get it running locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
zeebe-gateway:
  replicas: 1
  ingress:
    enabled: true
    className: nginx
    host: "zeebe.my.domain"

# Configure elastic search to make it running for local development
elasticsearch:
  replicas: 1
  
identity:
  contextPath: "/"
  fullURL: "http://my.domain/"

operate:
  contextPath: "/operate"

optimize:
  contextPath: "/optimize"

tasklist:
  contextPath: "/tasklist"
```

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: SelfHost
- Helm CLI version: 3 (kubeapps)
- Chart version: 8.3.2
- Values file: 
[values.yml.zip](https://github.com/camunda/camunda-platform-helm/files/13558376/values.yml.zip)

```[tasklist]
### Tasks
```

**Comment by aabouzaid** [comment]
@linonetwo Identity doesn't work under a sub-path if no TLS is enabled. Either set it with its own Ingress domain to work with HTTP or configure TLS to make it work as a sub-path. 
https://docs.camunda.io/docs/next/self-managed/platform-deployment/troubleshooting/#identity-contextpath

**Comment by linonetwo** [comment]
tasklist app give correct redirect to http://my.domain/auth/realms/camunda-platform/protocol/openid-connect/auth?client_id=tasklist&redirect_uri=http%3A%2F%2Fmy.domain%2Ftasklist%2Fidentity-callback&response_type=code&scope=openid+email&state=

just identity doesn't. And due to this I can't evaluate the zeebe . I just want to connect to zeebe
<img width="308" alt="截屏2023-12-06 17 17 47" src="https://github.com/camunda/camunda-platform-helm/assets/3746270/d13b81df-984c-45f0-b7c9-2aa5cc125592">

**Comment by linonetwo** [comment]
I try to setup tls to avoid this issue, but 

```yaml
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - my.domain
      secretName: camunda-platform
```

don't seem to work
