### ISSUE TITLE
[ISSUE] Invalid Redirect URI in Camunda Platform 8.3.3

### ISSUE THREAD

**Issue by failnix** [camunda/camunda-platform-helm#1116]
**Describe the issue:**

The issue refers to #714 where it was already marked as fixed.

I'm trying to host a self-manged Camunda-Installation and group the following camunda-services within a url-prefix with ingress f.ex.

- Operate https://acme.com/camunda/operate
- Tasklist https://acme.com/camunda/tasklist

A snipped of my value-file looks like
```
global:
  ingress:
    enabled: true
  image:
      tag: 8.3.3
  identity:
    auth:
      enabled: true
      operate:
        redirectUrl: "http://acme.com/camunda/operate"

operate:
  enabled: true
  contextPath: "/camunda/operate"
```
When trying to login, for example, http://acme.com/operate, Keycloak shows the error Invalid parameter: redirect_uri in the browser and it's not possible to login. 
The redirectUrl looks like http://acme.com/camunda/camunda/operate which is not correct ("camunda" is listed twice)

I think the problem for the operate-example is located in [camunda-platform-helm/charts/camunda-platform/templates/operate/deployment.yaml L88](https://github.com/camunda/camunda-platform-helm/blob/8ca642f4886830ff23d2d2126ebb712545926cc6/charts/camunda-platform/templates/operate/deployment.yaml#L88)
trimSuffix should not delete static "/operate" but the content of contextPath.

**Expected behavior:**

It should be possible to login into the apps normally.

**How to reproduce:**

Deploy any Helm chart v8.3.x with apps v8.3.x with combined Ingress enabled.

**Logs:**

Out of the keycloak-container

`2023-12-06 07:59:21,354 WARN  [org.keycloak.events] (executor-thread-20) type=LOGIN_ERROR, realmId=camunda-platform, clientId=operate, userId=null, ipAddress=10.42.0.1, error=invalid_redirect_uri, redirect_uri=http://acme.com/camunda/camunda/operate/identity-callback`

**Environment:**

- Platform: Any
- Helm CLI version: v3.10.3
- Chart version: 8.3.3
- Values file: see snippet in description
