### ISSUE TITLE
[ISSUE] kind/camunda-platform-core-kind-values.yaml is out of date with new elasticsearch changes

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1148]
**Describe the issue:**

Since commit 4abfd6a7e4568f8a2768b96e0bba17f7f623aea9, we had some ways that the elasticsearch configuration in values.yaml was changed because we started using a newer version of the elasticsearch helm chart. Because of this, users who are using kind/camunda-platform-core-kind-values.yaml are reporting issues where the configuration options are seemingly not being read (because the options changed.

One such example is how the old configuration for elasticsearch would reference 
```
elasticsearch:
  replicas: 2
```
and the new way of providing the same option is
```
elasticsearch:
  master:
    replicaCount: 2
```
The other example is how the persistent volume data size is altered. In the new configuration, there is 
```
elasticsearch:
  master:
    persistence:
      size: 64Gi
```

whereas the old configuration specifies 
```
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 15Gi

```

**Actual behavior:**

Storage gets set to 64 Gi rather than 15 as specified in the core kind values.yaml  
Replicas does not get set to 1 as seemingly configured.

**Expected behavior:**

Options that do not exist upstream should be removed or converted to the new syntax.
(or remove kind/camunda-platform-core-kind-values.yaml if we do not think we can maintain it.)

**How to reproduce:**

Try installing with the values.yaml file inside the kind folder.

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: KIND
- Helm CLI version: 3.11
- Chart version: 8.3.4
- Values file: kind/camunda-platform-core-kind-values.yaml
