### ISSUE TITLE
[ISSUE] connectors inbound not found

### ISSUE THREAD

**Issue by jpan8866** [camunda/camunda-platform-helm#1162]
**Describe the issue:**

I have deployed the entire stack to OpenShift and everything works as expected except that I am unable to reach the inbound endpoint for webhook. The problem seems to lie within the ingress as I am able to reach inbound through the service e.g. `connector-svc/inbound/my-webhook`.

My values file under connectors has the following configuration:
```
inbound:
      mode: oauth
    ingress:
      enabled: true
      className: ""
      path: /camunda/connectors
      host: "$HOSTNAME"
      tls:
        enabled: true
        secretName: cloud-ssl
      annotations:
        ingress.kubernetes.io/rewrite-target: "/"
```
This generates an ingress for connectors with the following rules:
```
  rules:
    - host: my-host.ca
      http:
        paths:
          - path: /camunda/connectors
            pathType: Prefix
            backend:
              service:
                name: camunda-engine-dev-connectors
                port:
                  number: 8080
```

**Actual behavior:**

I get the following when trying to start a flow at my-host.ca/camunda/connectors/inbound/my-webhook
```
{
    "timestamp": 1702938540096,
    "status": 404,
    "error": "Not Found",
    "path": "/camunda/connectors/inbound/my-webhook"
}
```

**Expected behavior:**

start a new process

**Environment:**
OpenShift

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: OpenShift
- Platform: OpenShift
- Helm CLI version: 3.13.1
- Chart version: 8.3.2
