### ISSUE TITLE
[ISSUE] Unable to install helm chart for camunda-platform version 8.3.4 with pullSecrets error

### ISSUE THREAD

**Issue by BololZ** [camunda/camunda-platform-helm#1175]
**Describe the issue:**

When I want to helm deploy the chart camunda/camunda-platform, version 8.3.4, in namespace camunda, the deploy failed.
Maybe, it's a mistake in values file ?

**Actual behavior:**

Installation failed.

**Expected behavior:**

Camunda-platform deployed in namespace camunda.

**How to reproduce:**

```
helm repo add camunda https://helm.camunda.io
helm repo update
helm -n camunda install camunda-platform camunda/camunda-platform --values ./values-camunda-platform.yaml --version 8.3.4 --debug
```

**Logs:**

`Error: INSTALLATION FAILED: template: camunda-platform/charts/elasticsearch/templates/master/statefulset.yaml:52:10: executing "camunda-platform/charts/elasticsearch/templates/master/statefulset.yaml" at <include "elasticsearch.imagePullSecrets" .>: error calling include: template: camunda-platform/charts/elasticsearch/templates/_helpers.tpl:19:3: executing "elasticsearch.imagePullSecrets" at <include "common.images.renderPullSecrets" (dict "images" (list .Values.image .Values.metrics.image .Values.sysctlImage .Values.volumePermissions.image) "context" $)>: error calling include: template: camunda-platform/charts/common/templates/_images.tpl:86:14: executing "common.images.renderPullSecrets" at <.pullSecrets>: can't evaluate field pullSecrets in type interface {}
helm.go:84: [debug] template: camunda-platform/charts/elasticsearch/templates/master/statefulset.yaml:52:10: executing "camunda-platform/charts/elasticsearch/templates/master/statefulset.yaml" at <include "elasticsearch.imagePullSecrets" .>: error calling include: template: camunda-platform/charts/elasticsearch/templates/_helpers.tpl:19:3: executing "elasticsearch.imagePullSecrets" at <include "common.images.renderPullSecrets" (dict "images" (list .Values.image .Values.metrics.image .Values.sysctlImage .Values.volumePermissions.image) "context" $)>: error calling include: template: camunda-platform/charts/common/templates/_images.tpl:86:14: executing "common.images.renderPullSecrets" at <.pullSecrets>: can't evaluate field pullSecrets in type interface {}`

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: EKS
- Helm CLI version: 3.13.3
- Chart version: 8.3.4
- Values file: 
```
global:
   image:
    tag: 8.3.4
    pullSecrets:
    - name: regcred-docker-hub

  ingress:
    enabled: true
    className: nginx
    annotations:
      ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    hosts:
      - host: xxxxx.example.com
        paths: 
          - /

connectors:
  image:
    repository: camunda/connectors-bundle
    tag: 8.3.2

identity:
  keycloak:
    image:
      repository: bitnami/keycloak
      tag: 22.0.5
    postgresql:
      image:
        repository: bitnami/postgresql
        tag: 15.5.0

optimize:
  image:
    repository: camunda/optimize
    tag: 8.3.5

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 1Gi

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"

zeebe-gateway:
  replicas: 1

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  logLevel: ERROR

elasticsearch:
  image: bitnami/elasticsearch
  tag: 8.9.2
  replicas: 1
  minimumMasterNodes: 1
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "gp3"
    resources:
      requests:
        storage: 50Gi
```

**Comment by HamzaMasood1** [comment]
Hello!
Yes your yaml file is slightly incorrect. 
There is an incorrect indentation in the global section and also the image value is incorrect under elasticsearch. I fixed your values yaml for you:
```yaml
global:
    image:
      tag: 8.3.4
    pullSecrets:
    - name: regcred-docker-hub

    ingress:
      enabled: true
      className: nginx
      annotations:
        ingress.kubernetes.io/rewrite-target: "/"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      hosts:
        - host: xxxxx.example.com
          paths:
            - /

connectors:
  image:
    repository: camunda/connectors-bundle
    tag: 8.3.2

identity:
  keycloak:
    image:
      repository: bitnami/keycloak
      tag: 22.0.5
    postgresql:
      image:
        repository: bitnami/postgresql
        tag: 15.5.0

optimize:
  image:
    repository: camunda/optimize
    tag: 8.3.5

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 1Gi

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"

zeebe-gateway:
  replicas: 1

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  logLevel: ERROR

elasticsearch:
  image:
    repository: bitnami/elasticsearch
    tag: 8.9.2
  replicas: 1
  minimumMasterNodes: 1
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "gp3"
    resources:
      requests:
        storage: 50Gi
```
