### ISSUE TITLE
[ENHANCEMENT] Support setting logging levels in all components

### ISSUE THREAD

**Issue by Parth-Shah-99** [camunda/camunda-platform-helm#1263]
**Describe the use case:**

Provide log level option in the Helm Chart for each component, to set Root level logs or class level logs.

**Describe the enhancement/feature:**

Only available in Operate/Connectors/Console as of now. For example for Operate as below:
```
  logging:
    level:
      ROOT: INFO
      io.camunda.operate: DEBUG
```

Similar option should be available for all the remaining components such as Tasklist, Optimize, Zeebe, Zeebe Gateway, etc.
