### ISSUE TITLE
Camunda identity page goes blank after login with ingress

### ISSUE THREAD

**Issue by nimblenitin** [camunda/camunda-platform-helm#1282]
**Describe the issue:**
Camunda identity page goes blank after login with ingress
![Screenshot from 2024-02-02 20-06-29](https://github.com/camunda/camunda-platform-helm/assets/25668152/7ee08c3b-e621-436a-8b2c-5c99750c169e)

**Actual behavior:**
Camunda identity page goes blank after login with ingress

**Expected behavior:**
Camunda identity page should not go blank after login 

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file: 
using below values file-
```
global:
  ingress:
    enabled: true
    className: nginx
    host: "dev-test.com"
  identity:
    auth:
      enabled: true
      publicIssuerUrl: "https://dev-test.com/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://dev-test.com/operate"
      tasklist:
        redirectUrl: "https://dev-test.com/tasklist"
      optimize:
        redirectUrl: "https://dev-test.com/optimize"
        
identity:
  nodeSelector:
    kubernetes.azure.com/os-sku: Ubuntu
  fullURL: "https://dev-test.com/identity"
  contextPath: "/identity"

operate:
  nodeSelector:
    kubernetes.azure.com/os-sku: Ubuntu
  contextPath: "/operate"

optimize:
  nodeSelector:
    kubernetes.azure.com/os-sku: Ubuntu
  contextPath: "/optimize"

tasklist:
  nodeSelector:
    kubernetes.azure.com/os-sku: Ubuntu
  contextPath: "/tasklist"

zeebe-gateway:
  nodeSelector:
    kubernetes.azure.com/os-sku: Ubuntu
  ingress:
    enabled: true
    className: nginx
    host: "dev-zeebe-test.com"
```
