### ISSUE TITLE
[ISSUE] Latest Camunda 8 helm install not creating camunda-platform realm in Keycloak

### ISSUE THREAD

**Issue by fragglehunter** [camunda/camunda-platform-helm#1306]
**Describe the issue:**

When installing Camunda 8 with the latest helm charts the camunda-platform realm is not showing up under the keycloak admin page.

**Actual behavior:**

This is causing pods from not starting as they cannot connect to keycloak.

**Expected behavior:**

Expecting pods to start without issues

**How to reproduce:**

**Logs:**

logs from identity pod:

2024-02-08 18:56:52.338 ERROR 1 --- [           main] i.c.i.i.k.c.KeycloakConfiguration        : Failure #1. Unable to connect to Keycloak.

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: **EKS**
- Helm CLI version: **v3.10.3**
- Chart version: **9.1.0**
- Values file: 
```
global:
  image:
    tag: 8.4.1
    pullSecrets: []
  ingress:
    enabled: true
    className: nginx-ingress
    host: "camunda8.example.com"
    tls:
      enabled: true
  identity:
    auth:
      publicIssuerUrl: "https://camunda8.example.com/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://camunda8.example.com/operate"
      tasklist:
        redirectUrl: "https://camunda8.example.com/tasklist"
      optimize:
        redirectUrl: "https://camunda8.example.com/optimize"

connectors:
  image:
    repository: camunda/connectors-bundle
    tag: 8.4.3

identity:
  fullURL: "https://camunda8.example.com/identity"
  contextPath: "/identity"

keycloak:
  image:
    repository: bitnami/keycloak
    tag: 22.0.5
  postgresql:
    image:
      repository: bitnami/postgresql
      tag: 15.5.0

operate:
  contextPath: "/operate"

optimize:
  image:
    repository: camunda/optimize
    tag: 8.4.0
  contextPath: "/optimize"

tasklist:
  contextPath: "/tasklist"

zeebe-gateway:
  ingress:
    enabled: true
    className: nginx-ingress
    host: "zeebe-camunda8.example.com"

elasticsearch:
  enabled: true
  image:
    repository: bitnami/elasticsearch
    tag: 8.9.2

webModeler:
  enabled: true
  image:
    tag: 8.4.1
    pullSecrets:
      - name: camundacloud
  contextPath: "/modeler"
  restapi:
    mail:
      smtpHost: ***
      smtpPort: 587
      smtpUser: ***
      smtpPassword: ***
      fromAddress: no-reply@example.com

postgresql:
  enabled: true
```

Domain changed to `example.com` to mask employer domain
