### ISSUE TITLE
[ISSUE] Zeebe gateway replicas are not controllable with `zeebeGateway.replicas`

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/camunda-platform-helm#1476]
**Describe the issue:**

The number of replicas in the Zeebe gateway deployment should be controllable with the `zeebeGateway.replicas` value.
Changing the value has no effect though, always resulting in 2 replicas.

**Actual behavior:**

The replica count is always 2, no matter the value of `zeebeGateway.replicas`

**Expected behavior:**

The replica count matches the value of `zeebeGateway.replicas`

**How to reproduce:**

```
$ helm install camunda-platform camunda/camunda-platform -f ~/Downloads/camunda-platform-core-kind-values.yaml --set zeebeGateway.replicas=3
$ kubectl get deployments.apps camunda-platform-zeebe-gateway
camunda-platform-zeebe-gateway   0/2     2            0           42s
```
 
The contents of `camunda-platform-core-kind-values.yaml`:
```yaml
global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false

# Disable identity as part of the Camunda core
identity:
  enabled: false

optimize:
  enabled: false

# Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# to get it running locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi

zeebeGateway:
  replicas: 1

connectors:
  enabled: true
  inbound:
    mode: disabled

elasticsearch:
  master:
    replicaCount: 1
    # Request smaller persistent volumes.
    persistence:
      size: 15Gi
```

I would expect the gateway replica count to be either 1 (the value from the file) or 3 (the overwritten value from the command line) but not 2 which seems to be the default value.

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: version.BuildInfo{Version:"v3.14.3", GitCommit:"f03cc04caaa8f6d7c3e67cf918929150cf6f3f12", GitTreeState:"clean", GoVersion:"go1.21.7"}
- Chart version: camunda-platform-9.3.2
- Values file:
