### ISSUE TITLE
[ISSUE] Web modeler secret not found (during CI)

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1586]
**Describe the issue:**

In the `kubectl describe` of the web-modeler restapi deployment
```
Error: secret "integration-postgresql-web-modeler" not found
```

relevant env variable for web-modeler restapi deployment
```
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: integration-postgresql-web-modeler
```

Secret that was supposed to be referenced
```
data:
  password: ...
  postgres-password: ...
kind: Secret
metadata:
...
  name: integration-postgresql

```

**Actual behavior:**

**Expected behavior:**

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:
