### ISSUE TITLE
[ISSUE] Port-forwarding Zeebe Gateway gRPC endpoint doesn't work

### ISSUE THREAD

**Issue by Langleu** [camunda/camunda-platform-helm#1595]
**Describe the issue:**

As reported on [Slack](https://camunda.slack.com/archives/C03UR0V2R2M/p1712740553278929) the Helm chart doesn't expose the gRPC endpoint of the Zeebe Gateway anymore.

The recent change to application config files https://github.com/camunda/camunda-platform-helm/pull/1297 is not working to expose the gRPC endpoint.

The configmap itself looks fine.
```
apiVersion: v1
data:
  application.yaml: |2

    server:
      address: "0.0.0.0"
      port: "8080"
    zeebe:
      gateway:
        monitoring:
          host: 0.0.0.0
          port: "9600"
        cluster:
          clusterName: camunda-zeebe
          port: "26502"
        network:
          host: 0.0.0.0
          port: "26500"
  gateway-log4j2.xml: ""
kind: ConfigMap
```

and right name
```
camunda-zeebe-gateway-configuration   2      11m
```

lastly properly configured
```
      volumes:
      - emptyDir: {}
        name: tmp
      - configMap:
          defaultMode: 484
          name: camunda-zeebe-gateway-configuration
        name: config
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /usr/local/zeebe/config/application.yaml
          name: config
          subPath: application.yaml
```

But ultimately it doesn't work and may be overwritten by the startup script:
```
[10/04/24 11:32:56] ➜  k logs -f camunda-zeebe-gateway-5b78fc54f7-b7jp2
+ hostname -i
+ HOST=10.202.62.10
+ [ true = true ]
+ export ZEEBE_GATEWAY_NETWORK_HOST=10.202.62.10
+ export ZEEBE_GATEWAY_CLUSTER_HOST=10.202.62.10
+ exec /usr/local/zeebe/bin/gateway
```

A temporary quick fix is to set the previous environment variables again;
```
    - name: ZEEBE_GATEWAY_NETWORK_HOST
      value: 0.0.0.0
    - name: ZEEBE_GATEWAY_NETWORK_PORT
      value: "26500"
```

Breaking behaviour and will cause confusion with customers on why gRPC out of the box doesn't work anymore.

**Actual behavior:**

When trying to port-forward
```
kubectl port-forward svc/camunda-zeebe-gateway 26500:26500 -n some-namespace
```
and getting the status of the Zeebe cluster, it always drops the call immediately and closes the local forwarding.
```
> zbctl status --insecure --address localhost:26500
Error: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"
```

**Expected behavior:**

The gRPC endpoint should be exposed and return my topology / Zeebe cluster status.

```
> zbctl status --insecure --address localhost:26500
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 8.5.0
Brokers:
  Broker 0 - camunda-zeebe-0.camunda-zeebe.c8-snap-cluster-1.svc:26501
    Version: 8.5.0
    Partition 1 : Leader, Healthy
    Partition 2 : Follower, Healthy
    Partition 3 : Follower, Healthy
  Broker 1 - camunda-zeebe-1.camunda-zeebe.c8-snap-cluster-1.svc:26501
    Version: 8.5.0
    Partition 1 : Follower, Healthy
    Partition 2 : Leader, Healthy
    Partition 3 : Follower, Healthy
  Broker 2 - camunda-zeebe-2.camunda-zeebe.c8-snap-cluster-1.svc:26501
    Version: 8.5.0
    Partition 1 : Follower, Healthy
    Partition 2 : Follower, Healthy
    Partition 3 : Leader, Healthy
```

**How to reproduce:**

For testing purposes the following install command is sufficient:
```
helm install camunda camunda/camunda-platform --version 10.0.1 --set identity.enabled=false --set global.identity.auth.enabled=false --set identity.keycloak.enabled=false
```

**Logs:**

Nothing mentioned in the Gateway logs since the call never reaches it.

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: AWS EKS (1.28)
- Helm CLI version: v3.14.3
- Chart version: 10.0.1
- Values file: see set values in the reproducing section
