### ISSUE TITLE
[ISSUE] Failing to set an existing secret key for keycloak

### ISSUE THREAD

**Issue by hamza-m-masood** [camunda/camunda-platform-helm#1652]
**Describe the issue:**

Keycloak pod does not start because it fails to reference the existing secret key in the values.yaml.
I have also created an issue in the main bitnami keycloak chart: https://github.com/bitnami/charts/issues/25232

Here is the values.yaml I used:
```yaml
identityKeycloak:
  auth:
    existingSecret: camunda-secrets
    passwordSecretKey: keycloak-secret
  postgresql:
    auth:
      existingSecret: camunda-secrets
      secretKeys:
        userPasswordKey: postgresql-secret
        adminPasswordKey: postgresql-secret
        replicationPasswordKey: postgresql-secret
```
**Actual behavior:**
The keycloak pod fails to reference `auth.passwordSecretKey` and hardcodes `password` as the secret key in it's env var:
```yaml
    - name: KEYCLOAK_DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: camunda-secrets
```
The `key` should have this value: `keycloak-secret`

**Expected behavior:**

The chart should correctly reference the `auth.passwordSecretKey` and start up the keycloak pod in a healthy state.
**How to reproduce:**
Run the helm chart with the values yaml I have given above.

**Logs:**
```
COMMAND:
kubectl events keycloak -n keycloak

OUTPUT:
...
2m51s (x11 over 4m45s)   Warning   Failed      Pod/keycloak-0     Error: couldn't find key password in Secret keycloak/camunda-secrets
```

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform:  GKE
- Helm CLI version:  3.14.3
- Chart version:  10.0.2
- Values file:  included above
