### ISSUE TITLE
[ISSUE] Identity fails to start due to missing urls for component presets

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda-platform-helm#1705]
**Describe the issue:**

Under certain conditions Identity will fail to start and therefore enters into a crashloop due to a recent refactoring ([REF](https://github.com/camunda-cloud/identity/pull/2710)). 

The application YAML for the presets has moved, and the reason this is an issue is because the helm charts also have a mirrored version of our yaml [here](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/templates/identity/configmap.yaml#L13) specifically there is a separate handling for KEYCLOAK [here](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/templates/identity/configmap.yaml#L158) which is no longer relevant as my PR ([here](https://github.com/camunda-cloud/identity/pull/2710)) refactored Keycloak to rely on the generic approach.

The yaml in the helm repo should be updated to reflect the new generic structure.

**Actual behavior:**

Identity fails to start successfully because there is a misconfiguration.

**Expected behavior:**

Identity starts successfully without issues

**How to reproduce:**

1. Use the included values file to deploy the services
2. Watch the Identity container logs
3. Observe error relating to a root url missing

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform:  Local KIND
- Helm CLI version:  v3.14.4
- Chart version:  used from main
- Values file:  

```
global:
  image:
    tag: latest
  identity:
    auth:
      enabled: true
  ingress:
    enabled: true
    className: nginx
    host: "local.distro.ultrawombat.com"
    tls:
      enabled: true
      secretName: camunda-platform
tasklist:
  image:
    tag: SNAPSHOT
  enabled: true
  contextPath: "/tasklist"
identity:
  image:
    tag: SNAPSHOT
  enabled: true
  contextPath: "/identity"
  fullURL: "https://local.distro.ultrawombat.com/identity"
operate:
  image:
    tag: SNAPSHOT
  enabled: true
  contextPath: "/operate"
optimize:
  image:
    tag: SNAPSHOT
  enabled: true
  contextPath: "/optimize"
connectors:
  enabled: false

elasticsearch:
  master:
    replicaCount: 1
    persistence:
      size: 15Gi

zeebe:
  image:
    # zeebe version that will be deployed.
    tag: SNAPSHOT
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi
zeebe-gateway:
  replicas: 1
  ingress:
    enabled: true
    className: ""
    host: "zeebe.local.distro.ultrawombat.com"
    tls:
      enabled: true
      secretName: camunda-platform
webModeler:
  enabled: true
  contextPath: "/modeler"
  image:
    pullSecrets:
      - name: registry-camunda-cloud
  restapi:
    mail:
      # This value is required, otherwise, the restapi pod won't start.
      fromAddress: noreply@example.com

postgresql:
  enabled: true
```
