### ISSUE TITLE
[ISSUE] Since 10.0.3 Elasticsearch Host is no longer overwritten in operate-configmap

### ISSUE THREAD

**Issue by lukas-beumer** [camunda/camunda-platform-helm#1734]
**Describe the issue:**

Since version 10.0.3, the variable 'global.elasticsearch.url.host' no longer replaces the value under camunda.operate.elasticsearch.host and camunda.operate.elasticsearch.url in the operate-configmap. The helpers.tpl seems not to work correctly anymore.

**Actual behavior:**

```
    camunda.operate:
      [...]
      # ELS instance to store Operate data
      elasticsearch:
        # Cluster name
        clusterName: elasticsearch
        username: "test-user"
        # Host
        host: release-name-elasticsearch
        # Transport port
        port: 9200
        # Elasticsearch full url
        url: "http://release-name-elasticsearch:9200"
```

**Expected behavior:**

```
    camunda.operate:
      [...]
      # ELS instance to store Operate data
      elasticsearch:
        # Cluster name
        clusterName: elasticsearch
        username: "test-user"
        # Host
        host: my-fancy-es-host
        # Transport port
        port: 9200
        # Elasticsearch full url
        url: "http://my-fancy-es-host:9200"
```

**How to reproduce:**

Try to override the global.elasticsearch.url.host value

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: GCP
- Helm CLI version: 3.14.3
- Chart version: >= 10.0.3
