### ISSUE TITLE
[ISSUE] Disabling Elasticsearch and enabling OpenSearch causes incorrect syntax in zeebe configmap

### ISSUE THREAD

**Issue by hamza-m-masood** [camunda/camunda-platform-helm#1863]
**Describe the issue:**

When Elasticsearch is disabled and OpenSearch is enabled then the resulting zeebe configmap syntax is incorrect.
**Actual behavior:**

The zeebe configmap has an extra `{}` that should not be included after the `exporters` key:
```
data:
  application.yaml: |
    zeebe:
      broker:
        exporters: {}   # invalid child element 
          opensearch:   # in a block mapping
            className: "io.camunda.zeebe.exporter.opensearch.OpensearchExporter"
           ....
```
**Expected behavior:**

I expect to have correct syntax for the zeebe config when OpenSearch is enabled.
**How to reproduce:**

Run the following command:
```
helm template test camunda/camunda-platform --version 10.0.5 --set global.elasticsearch.enabled=false,global.opensearch.enabled=true,global.opensearch.url.host=test > helm.yaml
```
Then check the content of `helm.yaml` for the above syntax error
**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 3.15.0
- Chart version: 10.0.5
- Values file:
