### ISSUE TITLE
[ISSUE] Cannot connect to OpenSearch: Missing required property 'OpenSearchVersionInfo.distribution'

### ISSUE THREAD

**Issue by prashanthisadde** [camunda/camunda-platform-helm#1891]
**Describe the issue:**

I am encountering an issue with Camunda Optimize where it cannot connect to the AWS OpenSearch Service. The error message indicates that a required property `OpenSearchVersionInfo.distribution` is missing.

**Actual behavior:**

Camunda Optimize fails to start with the following error:

```
ERROR o.s.boot.SpringApplication - Application run failed

Caused by: org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'OpenSearchVersionInfo.distribution'
```

**Expected behavior:**

Camunda Optimize should successfully connect to the OpenSearch cluster and start without errors.

**How to reproduce:**
1. Deploy Camunda Optimize using the official Helm chart on EKS.
2. Configure OpenSearch in the `values.yaml` file as follows:
   ```yaml
   opensearch:
     enabled: true
     aws:
       enabled: true
     tls:
       enabled: false
       existingSecret:
     auth:
       existingSecret:
       existingSecretKey:
     url:
       protocol: https
       host: https://vpc-<cluster>.<region>.es.amazonaws.com
       port: 443
     distribution: opensearch
     version: 2.13
   ```
3. Deploy the Helm chart:
   ```bash
   helm upgrade --install YOUR_RELEASE_NAME YOUR_CHART_PATH -f VALUES_YAML_PATH -n NAMESPACE
   ```

**Logs:**

```
ERROR o.s.boot.SpringApplication - Application run failed

Caused by: org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'OpenSearchVersionInfo.distribution'
```

**Environment:**

- Platform: AWS - EKS
- Helm CLI version: v3.15.0
- EKS Version: 1.29
- AWS OpenSearch Version: 2.13
- Camunda Optimize Backend Version: 3.13.1
- Camunda Optimize Image Version: 8.5.1
- Values file: default values.yaml

Any guidance on how to correctly pass these properties to Camunda Optimize or if there are any additional steps required to configure OpenSearch would be greatly appreciated.

Thank you for your assistance!
