### ISSUE TITLE
[ISSUE]  Helm Tests are failing with default values and if context path is used.

### ISSUE THREAD

**Issue by ManuelDittmar** [camunda/camunda-platform-helm#1900]
**Describe the issue:**

To validate my installation, I want to run `helm test <release-name>`,  however test-connection.yaml fails if default values or context path is used.

I don't know why exactly the default values fail, but for the context path you would need to add the context path here:

```
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['{{ include "identity.fullname" . }}:{{ .Values.identity.service.port }}']
```

**Actual behavior:**

```
Error: 1 error occurred:
        * pod camunda-identity-test-connection failed
```

**Expected behavior:**

tests pass

**How to reproduce:**

```
helm install camunda camunda/camunda-platform
helm test camunda

```
**Logs:**

```
Error: 1 error occurred:
        * pod camunda-identity-test-connection failed
```

**Environment:**

- Platform: GCP
- Helm CLI version: version.BuildInfo{Version:"v3.15.1", GitCommit:"e211f2aa62992bd72586b395de50979e31231829", GitTreeState:"clean", GoVersion:"go1.22.3"}
- Chart version: 10.0.2
- Values file:
