### ISSUE TITLE
[ISSUE] Unauthenticated external elasticsearch installations fails with CreateContainerConfigError because secret is not set

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1987]
**Describe the issue:**

In https://github.com/camunda/camunda-platform-helm/pull/1356 ,  we enabled support for external elasticsearch, while also providing a way to specify existingSecrets to authenticate to a password-protected elasticsearch cluster.

However, password-protection is not enabled by default in elasticsearch. So when a user with external elasticsearch upgrades to the latest helm release (10.1.0, as time of writing),  they will get a `CreateContainerConfigError` due to a reference to an `existingSecret` when the secret does not exist.

[SUPPORT-22303](https://jira.camunda.com/browse/SUPPORT-22303)

**Actual behavior:**

Operate throws a `CreateContainerConfigError`

**Expected behavior:**

Operate should be in the Ready state.

**How to reproduce:**

1. `kubectl run externalelastic --image=bitnami/elasticsearch --port=9200`
2. `kubectl expose pod externalelastic`
3. deploy the helm chart defining this section:

```yaml
global:
  elasticsearch:
    external: true
    url:
      protocol: http
      host: "hostname"
      port: 9200

elasticsearch:
  enabled: false
```

**Logs:**

```
> k get pods | grep cpt
cpt-connectors-55fd88bbf5-4g79k                             0/1     Running                           0               2m6s
cpt-console-6b864bcf7d-8jkpb                                1/1     Running                           0               2m6s
cpt-identity-84b5cd65d8-6rglp                               1/1     Running                           0               2m6s
cpt-identity-postgresql-0                                   1/1     Running                           0               2m6s
cpt-keycloak-0                                              1/1     Running                           0               2m6s
cpt-operate-766cf84fb-666rb                                 0/1     CreateContainerConfigError        0               2m6s
cpt-optimize-8f764c955-s2pv5                                0/1     Init:CreateContainerConfigError   0               2m6s
cpt-postgresql-0                                            1/1     Running                           0               2m6s
cpt-postgresql-web-modeler-0                                1/1     Running                           0               2m6s
cpt-tasklist-d5c67857d-m5zlk                                0/1     CreateContainerConfigError        0               2m6s
cpt-web-modeler-restapi-5b8f6ffb75-fjqpg                    0/1     CreateContainerConfigError        0               2m6s
cpt-web-modeler-webapp-86cd4bfb7f-jkhsc                     1/1     Running                           0               2m6s
cpt-web-modeler-websockets-55c4bb6768-k87rk                 1/1     Running                           0               2m6s
cpt-zeebe-0                                                 0/1     CreateContainerConfigError        0               2m6s
cpt-zeebe-gateway-6b84dcb8f6-47xj7                          1/1     Running                           0               2m6s

```

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: KIND
- Helm CLI version: 3.15.1
- Chart version: 10.1.0
- Values file:  
```yaml
global:
  elasticsearch:
    external: true
    url:
      protocol: http
      host: "hostname"
      port: 9200

elasticsearch:
  enabled: false
```

**Comment by jessesimpson36** [comment]
A workaround for this is setting 

```yaml
global:
  elasticsearch:
    auth:
      username: blah
      password: ignoredblahblah
```

The username/password are just ignored when they're passed to elasticsearch.
