### ISSUE TITLE
[ENHANCEMENT] Support existingSecretKey for other components

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#2085]
**Describe the use case:**

For users that use external secrets, some have requested that they be able to set the name of the key inside the kubernetes Secret. so for example:

```
apiVersion: v1
data:
  connectors-secret: ...
  console-secret: ...
  cpt-connectors-identity-secret: ...
  cpt-console-identity-secret: ...
  cpt-operate-identity-secret: ...
  cpt-optimize-identity-secret: ...
  cpt-tasklist-identity-secret: ...
  cpt-zeebe-identity-secret: ...
  operate-secret: ...
  optimize-secret: ...
  tasklist-secret: ...
  zeebe-secret: ...
  modeler-restapi-mail-secret: ...
  modeler-database-secret: ...
  modeler-postgres-user-password: ...

kind: Secret
metadata:
  annotations:
  name: existing-secret-for-apps
  namespace: default
type: Opaque


```

In this case, the components are just using their default key names.  If you want the "optimize-secret" to be named "optimize-vault-secret", you might expect to set `global.identity.auth.optimize.existingSecretKey` similar to how our external elasticsearch `existingSecretKey` allows you to do.

As for why someone would want this level of control, I'm not sure. 

**Describe the enhancement/feature:**

**Desired outcome and acceptance tests:**
