### ISSUE TITLE
[ISSUE] OpenSearch values require you to input a password and an existingSecret at the same time.

### ISSUE THREAD

**Issue by hamza-m-masood** [camunda/camunda-platform-helm#2133]
**Describe the issue:**

The [guide](https://docs.camunda.io/docs/self-managed/setup/guides/using-existing-opensearch/#connecting-to-amazon-opensearch-service-with-basic-auth) states that it is possible to connect to OpenSearch by referencing an existing k8s secret. This is currently not possible since the if statement [checks for a string literal password first](https://github.com/camunda/camunda-platform-helm/blob/2a334ba4eb16f0e46a6bfcf2791e03fc64b5a6dd/charts/camunda-platform-latest/templates/operate/deployment.yaml#L56C11-L56C99) before using the existingSecret.

**Actual behavior:**

The customer needs to specify a dummy password in raw string to use the existingSecret functionality for OpenSearch.

**Expected behavior:**

The customer should be able to specify an existing k8s secret or specify a raw string username/password for OpenSearch.
**How to reproduce:**

values.yaml:
```yaml
global:
  elasticsearch:
    enabled: false
  opensearch:
    enabled: true
    auth:
      existingSecret: test-secret
      existingSecretKey: test-secret-key
    url:
      protocol: https
      host: opensearch.example.com
      port: 443

optimize:
  migration:
    enabled: false

elasticsearch:
  enabled: false
```

When applying this values.yaml, you will notice that no OpenSearch configuration is generated.
**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file: 

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2168
```
