### ISSUE TITLE
Make it easier to enable gateway metrics

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#216]
Currently the gateway metrics exporting are disabled by default. They have to be enabled via env var like this https://github.com/camunda-cloud/zeebe/blob/main/benchmarks/setup/default/zeebe-values.yaml#L99-L100

We should make it easier to enable this via a separate variable like:

```yaml
zeebe-gateway:

  exportMetrics:
    enabled: true
```

Doing it like this allows to extend the `exportMetrics` with other properties later
