### ISSUE TITLE
Template for gRPC host of Zeebe-Gateway is missing

### ISSUE THREAD

**Issue by Szik** [camunda/camunda-platform-helm#2164]
**Describe the issue:**

Installing [camunda-platform-helm](https://github.com/camunda/camunda-platform-helm) via helm combined with Ingress and a configuration via a values.yaml containing:

```yaml
global:
  ingress:
    host: "local.distro.ultrawombat.com"

zeebeGateway:
  ingress:
    grpc:
      host: "zeebe-{{ .Values.global.ingress.host }}"
```

**Actual behavior:**

configuration of Console will be:

```
- name: Zeebe Gateway
    id: zeebeGateway
    version: 8.5.4
    urls:
      grpc: http://zeebe-{{ .Values.global.ingress.host }}
```

**Expected behavior:**

configuration of Console should be:

```
- name: Zeebe Gateway
    id: zeebeGateway
    version: 8.5.4
    urls:
      grpc: http://zeebe-local.distro.ultrawombat.com
```

**How to reproduce:**

- setup a cluster with propper configured Ingress running (locally)
- install helm charts of latest stable C8 version 

**Logs:**

see "**Expected behavior**"

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

local cluster, default configuration (Postgresql, keycloak, elasticsearch)
- Helm CLI version: 3.13.1
- Chart version: 10.2.0
- Values file: 

```yaml
global:
  ingress:
    enabled: true
    className: nginx
    host: "local.distro.ultrawombat.com"
    tls:
      enabled: true
      secretName: camunda-platform
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "{{ .Values.global.ingress.host }}"
      external-dns.alpha.kubernetes.io/ttl: "60"
  identity:
    auth:
      publicIssuerUrl: "https://{{ .Values.global.ingress.host }}/auth/realms/camunda-platform"
      console:
        redirectUrl: "https://{{ .Values.global.ingress.host }}"
      operate:
        redirectUrl: "https://{{ .Values.global.ingress.host }}/operate"
      tasklist:
        redirectUrl: "https://{{ .Values.global.ingress.host }}/tasklist"
      optimize:
        redirectUrl: "https://{{ .Values.global.ingress.host }}/optimize"
      webModeler:
        redirectUrl: "https://{{ .Values.global.ingress.host }}/modeler"

identity:
  contextPath: "/identity"

operate:
  contextPath: "/operate"

optimize:
  contextPath: "/optimize"

tasklist:
  contextPath: "/tasklist"

connectors:
  contextPath: "/connectors"

webModeler:
  enabled: true
  contextPath: "/modeler"
  image:
    pullSecrets:
    - name: registry-camunda-cloud
  restapi:
    mail:
      fromAddress: noreply@example.com

postgresql:
  enabled: true

zeebeGateway:
  contextPath: "/zeebe"
  ingress:
    grpc:
      enabled: true
      className: nginx
      host: "zeebe-{{ .Values.global.ingress.host }}"
      tls:
        enabled: true
        secretName: camunda-platform-zeebe-gateway
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "zeebe-{{ .Values.global.ingress.host }}"
        external-dns.alpha.kubernetes.io/ttl: "60"

console:
  enabled: true
  contextPath: "/"
  image:
    pullSecrets:
    - name: registry-camunda-cloud

elasticsearch:
  maxUnavailable: 0

zeebe:
  clusterSize: 3
  partitionCount: 3
  replicationFactor: 3
  pvcSize: 1Gi

```
