### ISSUE TITLE
[ISSUE] Impossible to set Optimize es.settings.index.number_of_replicas and es.settings.index.number_of_shards through helm values.yaml

### ISSUE THREAD

**Issue by igor-msk** [camunda/camunda-platform-helm#2179]
**Describe the issue:**

Configuring Optimize with setting es.settings.index.number_of_replicas and es.settings.index.number_of_shards through ENV does not have any effect 
```
optimize:
  env:
    - name: CAMUNDA_OPTIMIZE_ES_SETTINGS_INDEX_NUMBEROFREPLICAS
      value: "2"
    - name: CAMUNDA_OPTIMIZE_ES_SETTINGS_INDEX_NUMBER_OF_REPLICAS
      value: "2"
    - name: CAMUNDA_OPTIMIZE_ES_SETTINGS_INDEX_NUMBEROFSHARDS
      value: "2"
    - name: CAMUNDA_OPTIMIZE_ES_SETTINGS_INDEX_NUMBER_OF_SHARDS
      value: "2"
```

**Actual behavior:**

"_" in the name of the attributew are probably treated as additional nested levels like _es.settings.index.number.of.replicas_ instead of _es.settings.index.number_of_replicas_

**Expected behavior:**

one pair of provided settings works

**Alternative solution:**

add this to Optimize ConfigMap template
```
data:
    es:
      settings:
        index:
          number_of_replicas: {{ .Values.optimize.elasticSearchNumberOfReplicas }}
          number_of_shards: {{ .Values.optimize.elasticSearchNumberOfShards }}
```
and this to values.yaml
```
optimize:
  elasticSearchNumberOfReplicas: 1
  elasticSearchNumberOfShards: 1
```

**Environment:**
- Chart version: 10.2.1
