### ISSUE TITLE
[ENHANCEMENT] Execution Identity integration

### ISSUE THREAD

**Issue by megglos** [camunda/camunda-platform-helm#2195]
**Describe the use case:**

This feature request is about integrating the execution layer identity into a SM cluster. Execution Identity is a new component that is part of the mono-repo https://github.com/camunda/camunda and will be the component to manager uses/authorizations within a cluster going forward and replace the current present identity component.

For more context, also see https://docs.google.com/presentation/d/1VcdJGDqX4Jcjt7w2gf7KvEyLUueHojmg4wxfcZPJoDI/edit#slide=id.g21c05d33edd_0_0

relates to https://github.com/camunda/product-hub/issues/2222

**Describe the enhancement/feature:**

```[tasklist]
### Iteration 1 - Execution Identity Integration (8.6 Alpha5)
- [x] Add an execution identity component to the cluster - without removing the existing identity - by default it should be disabled
- [x] The execution identity can be accesses through a service
- [x] An ingress can be configured to access the execution identity service
```

```[tasklist]
### Iteration 2 - Webapp Exporter @megglos link relevant issue this depends on
- [ ] zeebe: Enable the WebApp Exporter (to be released still)
```

```[tasklist]
### Iteration 3- Migration App - TBD by @Ben-Sheppard 
```

**Desired outcome and acceptance tests:**

- Identity Webapp can be accessed

**Additional information**:
image: `camunda/camunda:SNAPSHOT`

Required config for the identity deployment:
configmap:
```
spring:
  profiles:
    active: identity,auth-basic
camunda:
  database:
    type: elasticsearch
    clusterName: elasticsearch
    url: http://elasticsearch:9200
zeebe:
  gateway:
    cluster:
      initial-contact-points: zeebe:26502
      member-id:identity
```
or alternatively the equivalent env vars:
```
SPRING_PROFILES_ACTIVE=identity,auth-basic
CAMUNDA_DATABASE_TYPE=elasticsearch
CAMUNDA_DATABASE_clusterName=elasticsearch
CAMUNDA_DATABASE_URL=http://elasticsearch:9200
ZEEBE_GATEWAY_CLUSTER_INITIALCONTACTPOINTS: zeebe:26502
ZEEBE_GATEWAY_CLUSTER_MEMBERID: identity
```
