### ISSUE TITLE
[ENHANCEMENT] As a User I can extend the default application configuration

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda-platform-helm#2197]
**Describe the use case:**

We have recently added a way to configure the applications with `configuration`. The problem with that is that it completely replaces the existing defaults (set in the template). 

**Describe the enhancement/feature:**

I would like to define an additional configuration, without the need to also configure the default again. Especially this might not be possible if I depend on the helm chart like the [benchmark-helm 
](https://github.com/zeebe-io/benchmark-helm), as some values are dynamic related to the release-name. 

See related [slack thread](https://camunda.slack.com/archives/C03UR0V2R2M/p1722947834149849) 

**Desired outcome and acceptance tests:**

I can configure for example Zeebe via:

```
zeebe:
  extraConfiguration:
    zeebe.gateway.monitoring.enabled: "true"
    zeebe.gateway.threads.managementThreads: "1"
    zeebe.broker.experimental.consistencyChecks.enablePreconditions: "true"
    zeebe.broker.experimental.consistencyChecks.enableForeignKeyChecks: "true"
    zeebe.broker.executionMetricsExporterEnabled: "true"
    zeebe.broker.data.diskUsageCommandWatermark: "0.8"
    zeebe.broker.data.diskUsageReplicationWatermark: "0.9"
    # Configure index suffix with hour pattern, so we create every hour a new index
    # such that ILM can clean it up quickly
    zeebe.broker.exporters.elasticsearch.args.index.indexSuffixDatePattern: "yyyy-MM-dd_HH"
```
and this is taken into account by Zeebe. Together with the defaults, like elasticsearch configurations
