### ISSUE TITLE
[ISSUE] ROSA integration tests are failing due to missing secret

### ISSUE THREAD

**Issue by leiicamundi** [camunda/camunda-platform-helm#2248]
**Describe the issue:**

The last run of ROSA integration tests is failing : https://github.com/camunda/camunda-platform-helm/actions/runs/10482775419
The error seems to be related to a missing secret `integration-test` that has been created at August 1 on the permanent cluster.

![Capture d’écran 2024-08-21 à 09 39 49](https://github.com/user-attachments/assets/53e64892-3c13-4cc2-b059-a418dac84d95)

**Actual behavior:**

The tests are failing and the secret is absent

**Expected behavior:**

The tests should work and the missing secret should be imported in the on-demand cluster.

**How to reproduce:**

Run the on-demand tests

**Logs:**

[](https://github.com/camunda/camunda-platform-helm/actions/runs/10482775419)

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: ROSA
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by jessesimpson36** [comment]
We need to validate whether this issue is still present, and this issue needs to be updated with information from the failing build.  I can fill that in myself later, or you can @leiicamundi .

**Comment by jessesimpson36** [comment]
```yaml
apiVersion: v1
data:
  admin-password: someBase64String
  client-secret: someBase64String
  connectors-secret: someBase64String
  console-secret: someBase64String
  identity-firstuser-password: someBase64String
  keycloak-secret: someBase64String
  management-password: someBase64String
  operate-secret: someBase64String
  optimize-secret: someBase64String
  password: someBase64String
  postgres-password: someBase64String
  smtp-password: someBase64String
  tasklist-secret: someBase64String
  zeebe-secret: someBase64String
kind: Secret
metadata:
  name: integration-test
type: Opaque

```

This is the shape of the referenced secret.  add this in the namespace that's failing for you, and you should be set.
