### ISSUE TITLE
[ISSUE] 8.3.0: Operate Migration InitContainer Env Templating has wrong indentation

### ISSUE THREAD

**Issue by lukas-beumer** [camunda/camunda-platform-helm#2271]
**Describe the issue:**

The new operate init container introduced in 8.3.0 templates the set env variables in the wrong place, which leads to a template error. The current indented value is 8 digits, but it should be 12 digits.

https://github.com/camunda/camunda-platform-helm/pull/2144/files#diff-4be9f29a24f0ef70bee14a071fe8111c2963c9a923b37ab49fdae26d323683f6R73

**Actual behavior:**

When the Helm Chart is generated, the additionally set environments are indented incorrectly.

![Screenshot 2024-08-29 at 07 07 11](https://github.com/user-attachments/assets/6dded878-8983-4a37-93d5-9d1882399409)

**Expected behavior:**

The environment variables are indented correctly

**How to reproduce:**

```
operate:
  ## @extra optimize.migration configuration for Optimize migration
  migration:
    ## @param operate.migration.enabled if true, run Operate migration script as an init container
    enabled: true
    env:
      - name: "CAMUNDA_OPERATE_ELASTICSEARCH_NUMBER_OF_REPLICAS"
        value: "1"
```

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: GCP
- Helm CLI version: v3.15.4
- Chart version: > 8.3.0
