### ISSUE TITLE
[ISSUE] RESTAPI_PUSHER_SECRET does not allow you to reference a differently-named k8s Secret

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#2281]
**Describe the issue:**

In https://github.com/camunda/camunda-platform-helm/issues/644

we wanted to define a configuration that would use existingSecret for all components. one set of `secretKeyRef`'s in the webmodeler restapi appears to not have a configurable secret name.

https://github.com/camunda/camunda-platform-helm/blob/e9ffb23292a0a3886cb4612a0e09d594dc7d32d4/charts/camunda-platform-latest/templates/web-modeler/deployment-restapi.yaml#L54-L68

A workaround to this would be to set 

```yaml
webModeler:
  restapi:
    env:
      - name: RESTAPI_PUSHER_SECRET
        valueFrom:
          secretKeyRef:
            name: name-of-different-secret
            key: pusher-app-secret
```

**Actual behavior:**

RESTAPI_PUSHER_SECRET uses RELEASE-web-modeler for the secret name regardless of whether all existingSecrets are defined explicitly.

**Expected behavior:**

I expect that I can reference a Secret for any references of `secretKeyRef`. 

This feature should be implemented for only 8.8. For 8.7 the workaround should be used.

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by jessesimpson36** [comment]
This is related to 
#1898 and #2277   and overall product-hub ticket https://github.com/camunda/product-hub/issues/2312

**Comment by daniel-ewing** [comment]
Hi @jessesimpson36, have you tested this with CHC 10.3.2?  It did not work for me:

![image](https://github.com/user-attachments/assets/080ceb23-faae-4da9-94d0-d06ecd9e164d)

![image](https://github.com/user-attachments/assets/6f8fc825-84e9-4451-a081-44bc94207f4e)

**Comment by jessesimpson36** [comment]
You are referencing the `kubectl describe` information, which doesn't properly display duplicate environment variables. I would suggest testing the functionality, or exec'ing into the pod to see what environment variable you actually have referenced.

But I admit I have  not yet  tested this workaround.

**Comment by jessesimpson36** [comment]
I created a secret with 

```
kubectl  create secret generic --from-literal pusher-app-secret=jesseishacker name-of-different-secret
```
and exec'd into the restapi pod and confirmed the env var is set properly.
```
~ $ env | grep PUSHER
RESTAPI_PUSHER_SECRET=jesseishacker
```

I have now tested the workaround.

**Comment by daniel-ewing** [comment]
Confirmed the alternate solution in 10.3.2 using:
```
webModeler:
  restapi:
    env:
      - name: RESTAPI_PUSHER_SECRET
        valueFrom:
          secretKeyRef:
            name: name-of-different-secret
            key: pusher-app-secret
```
