### ISSUE TITLE
[ISSUE] When zeebeGateway.ingress.rest.enabled contextPath and paths are causing issues. 

### ISSUE THREAD

**Issue by drodriguez-305** [camunda/camunda-platform-helm#2282]
**Describe the issue:**

When ` zeebeGateway.ingress.rest.enabled` is set to true we have constraints that the `zeebeGateway.contextPath` and `zeebeGateway.ingress.rest.path` need to be the same. 

**Actual behavior:**
I then set `zeebeGateway.contextPath= /` and `zeebeGateway.ingress.rest.path= /` 
```
zeebe-gateway:
  replicas: 1
  affinity: {}
  contextPath: /
  ingress:
    rest:
      enabled: true
      host: zeebe-gateway.dev.cosmdream.com
      tls:
        enabled: true
        secretName: "dev-cosmdream-com-tls"
      path: /
```
when running it the zeebe-gateway pod doesn't get in the ready state. Looking at the deployment we can see there is an additional `/` in the readiness probe.

```
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: //actuator/health/readiness
```

Then I edited and removed the `/`
```
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /actuator/health/readiness
```
After that you need to kill the pod and confirm the correct one runs. 

**Expected behavior:**
There should be no extra `/` and shouldn't have to edit the deployment to get a working configuration. 

**How to reproduce:**

**Logs:**

**Related:**
[SUPPORT-23427](https://jira.camunda.com/browse/SUPPORT-23427)

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:
