### ISSUE TITLE
[ENHANCEMENT] Execution Identity integration - iteration 2

### ISSUE THREAD

**Issue by drodriguez-305** [camunda/camunda-platform-helm#2294]
**Describe the use case:**

This feature request is about integrating the execution layer identity into a SM cluster. Execution Identity is a new component that is part of the mono-repo https://github.com/camunda/camunda and will be the component to manager uses/authorizations within a cluster going forward and replace the current present identity component.

For more context, also see https://docs.google.com/presentation/d/1VcdJGDqX4Jcjt7w2gf7KvEyLUueHojmg4wxfcZPJoDI/edit#slide=id.g21c05d33edd_0_0

relates to https://github.com/camunda/product-hub/issues/2222

first iteration was completed https://github.com/camunda/camunda-platform-helm/issues/2195
**Describe the enhancement/feature:**

```[tasklist]
### Iteration 2 - Webapp Exporter
- [x] zeebe statefulset: Enable the Camunda Exporter for Elasticsearch on Zeebe brokers for 8.7 clusters only
- [x] zeebe statefulset: Enable the Camunda Exporter for Opensearch on Zeebe brokers for 8.7 clusters only
```

```[tasklist]
### Iteration 3- Migration App - TBD by @Ben-Sheppard 
```

**Comment by megglos** [comment]
@mustafadagher can you please provide a minimal elasticsearch config for the camunda exporter here to get this integration started?

As a minimum, let's take the current [elasticsearch exporter config](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform-latest/templates/zeebe/configmap.yaml#L18-L33) as orientation + whatever is necessary from you perspective for the new exporter.

**Comment by mustafadagher** [comment]
@megglos 
To configure the new camunda exporter, 

Under the following
```yaml
zeebe:
      broker:
        exporters:
```
We should add:
```yaml
          CamundaExporter:
            className: "io.camunda.exporter.CamundaExporter"
            args:
              connect:
                type:
                url: 
                username:
              index:
                prefix: 
              retention:
                enabled: true
                minimumAge: 
                policyName:
              createSchema: true 
```

Notice that `connect.type` should have a value one of `elasticsearch` or `opensearch`. Also this is just a minimal configured based of [ExporterConfiguration](https://github.com/camunda/camunda/blob/main/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/config/ExporterConfiguration.java) class
