### ISSUE TITLE
[ISSUE] identity firstuser existingsecretkey has no effect

### ISSUE THREAD

**Issue by hamza-m-masood** [camunda/camunda-platform-helm#2366]
**Describe the issue:**

identity.firstUser.existingSecretKey does not take effect in the [identity template](https://github.com/camunda/camunda-platform-helm/blob/0a67ae901b5f517d8725e421ac0721eb71b8971f/charts/camunda-platform-latest/templates/identity/deployment.yaml#L188).
It is always the default key, “identity-firstuser-password” that is looked for, regardless of what is defined in the [values.yaml.](https://github.com/camunda/camunda-platform-helm/blob/0a67ae901b5f517d8725e421ac0721eb71b8971f/charts/camunda-platform-latest/values.yaml#L2016)
support-ticket: https://jira.camunda.com/browse/SUPPORT-23713
**Actual behavior:**

firstuser existingSecret key is not applied
**Expected behavior:**

firstuser existingSecret key is applied
**How to reproduce:**

```
identity:
    firstUser:
        enabled: true
        existingSecret: "identity-secret"
        existingSecretKey: "admin"
        email: test@camunda.com
        firstName: test
        lastName: test
```

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file: 

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2370
```
