### ISSUE TITLE
[ISSUE] elasticsearch unhealthy using helm chart version: 8.3.17

### ISSUE THREAD

**Issue by Szik** [camunda/camunda-platform-helm#2426]
**Describe the issue:**

C8 cluster in self-managed installed via helm with chart version: 8.3.17 stays unhealthy.

**Actual behavior:**

Root cause: elasticsearch is unhealthy.

**Expected behavior:**

Entire cluster being healthy.

**How to reproduce:**

Regular installation of SM via helm of chart version 8.3

**Logs:**

Elasticsearch:
```
touch: cannot touch '/opt/bitnami/elasticsearch/config/elasticsearch.yml': Read-only file system
```

**Environment:**

self-managed

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: GCP
- Helm CLI : v3.13.1
- Chart version: 8.3.17
- Values file:
```
console:
  enabled: true
  image:
    tag: 8.6.4

identity:
  enabled: true
  image:
    tag: 8.3.15

zeebe:
  enabled: true
  image:
    tag: 8.3.16

connectors:
  enabled: true
  image:
    tag: 8.3.18

tasklist:
  enabled: true
  image:
    tag: 8.3.17

operate:
  enabled: true
  image:
    tag: 8.3.16
    
optimize:
  enabled: true
  image:
    tag: 8.3.14

webModeler:
  enabled: true
  image:
    tag: 8.3.12

elasticsearch:
  enabled: true
  image:
    tag: 8.13.4
```
