### ISSUE TITLE
[ENHANCEMENT] Disable Connection test if the component is disabled

### ISSUE THREAD

**Issue by xevien96** [camunda/camunda-platform-helm#2492]
**Describe the issue:**

When setting up a cluster for Webmodeler only by disabling all the automation components the operate connection test pod still gets created.

**Actual behavior:**

Operate connection test pod get created even if operate is disabled.

**Expected behavior:**

Don't create the connection test pod when Operate is disabled. Same behaviour as with Webmodeler connection test pod

**How to reproduce:**

Disable Operate in a Helm install via
```
operate:
  enabled: false
```
Check with helm template what pods will be created.

**Logs:**

```
# Source: camunda-platform/templates/operate/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "camunda-management-operate-test-connection"
  labels:
    app: camunda-platform
    app.kubernetes.io/name: camunda-platform
    app.kubernetes.io/instance: camunda-management
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    helm.sh/chart: camunda-platform-11.0.1
    app.kubernetes.io/component: operate
    app.kubernetes.io/version: "8.6.2"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['camunda-management-operate:80']
  restartPolicy: Never
```

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: local kind cluster
- Helm CLI version: 3.16.2
- Chart version: 11.0.1
- Values file: [webmodelerOnly.yaml.txt](https://github.com/user-attachments/files/17461093/webmodelerOnly.yaml.txt)
