### ISSUE TITLE
[ISSUE] Missing Ingress Configuration for Web Modeler will break Console

### ISSUE THREAD

**Issue by ManuelDittmar** [camunda/camunda-platform-helm#2658]
**Describe the issue:**

**Actual behavior:** If no Ingress is defined, helm chart will not fall back to localhost. Without a Url, Console  runs into Object Conversion Error in Management Clusters.

```
camunda:
  console:
    oAuth:
      audience: "console-api"
      clientId: "console"
      issuer: "https://xxxx"
      jwksUri: "https://xxxx"
      type: "KEYCLOAK"
      wellKnown: "https://well-known-uri"
    managed:
      method: plain
      releases:
      - name: camunda
        namespace: camunda
        version: 11.0.4
        components:
        - name: Console
          id: console
          version: 8.6.18
          url: http://localhost:8087
          readiness: http://camunda-console.camunda:9100/health/readiness
          metrics: http://camunda-console.camunda:9100/prometheus
        - name: Keycloak
          id: keycloak
          version: 25.0.6
          url: 
        - name: Identity
          id: identity
          version: 8.6.5
          url: http://localhost:8080
          readiness: http://camunda-identity.camunda:82/actuator/health
          metrics: http://camunda-identity.camunda:82/actuator/prometheus
        - name: Operate
          id: operate
          version: 8.6.3
          url: http://localhost:8081
          readiness: http://camunda-operate.camunda:9600/actuator/health/readiness
          metrics: http://camunda-operate.camunda:9600/actuator/prometheus
        - name: Optimize
          id: optimize
          version: 8.6.2
          url: http://localhost:8083
          readiness: http://camunda-optimize.camunda:80/api/readyz
          metrics: http://camunda-optimize.camunda:8092/actuator/prometheus
        - name: Tasklist
          id: tasklist
          version: 8.6.5
          url: http://localhost:8082
          readiness: http://camunda-tasklist.camunda:9600/actuator/health/readiness
          metrics: http://camunda-tasklist.camunda:9600/actuator/prometheus
        - name: WebModeler WebApp
          id: webModelerWebApp
          version: 8.6.3
          url: 
          readiness: http://camunda-web-modeler-webapp.camunda:8071/health/readiness
          metrics: http://camunda-web-modeler-webapp.camunda:8071/metrics
        - name: Zeebe Gateway
          id: zeebeGateway
          version: 8.6.5
          urls:
            grpc: http://localhost:26500
            http: http://localhost:8088
          readiness: http://camunda-zeebe-gateway.camunda:9600/zeebe/actuator/health/readiness
          metrics: http://camunda-zeebe-gateway.camunda:9600/zeebe/actuator/prometheus
        - name: Zeebe
          id: zeebe
          version: 8.6.5
          readiness: http://camunda-zeebe.camunda:9600/actuator/health/readiness
          metrics: http://camunda-zeebe.camunda:9600/actuator/prometheus
  ```

**Expected behavior:** url for web modeler fallsback to e.g. http://localhost:8085

```
camunda:
  console:
    oAuth:
      audience: "console-api"
      clientId: "console"
      issuer: "https://xxxx"
      jwksUri: "https://xxxx"
      type: "KEYCLOAK"
      wellKnown: "https://well-known-uri"
    managed:
      method: plain
      releases:
      - name: camunda
        namespace: camunda
        version: 11.0.4
        components:
        - name: Console
          id: console
          version: 8.6.18
          url: http://localhost:8087
          readiness: http://camunda-console.camunda:9100/health/readiness
          metrics: http://camunda-console.camunda:9100/prometheus
        - name: Keycloak
          id: keycloak
          version: 25.0.6
          url: 
        - name: Identity
          id: identity
          version: 8.6.5
          url: http://localhost:8080
          readiness: http://camunda-identity.camunda:82/actuator/health
          metrics: http://camunda-identity.camunda:82/actuator/prometheus
        - name: Operate
          id: operate
          version: 8.6.3
          url: http://localhost:8081
          readiness: http://camunda-operate.camunda:9600/actuator/health/readiness
          metrics: http://camunda-operate.camunda:9600/actuator/prometheus
        - name: Optimize
          id: optimize
          version: 8.6.2
          url: http://localhost:8083
          readiness: http://camunda-optimize.camunda:80/api/readyz
          metrics: http://camunda-optimize.camunda:8092/actuator/prometheus
        - name: Tasklist
          id: tasklist
          version: 8.6.5
          url: http://localhost:8082
          readiness: http://camunda-tasklist.camunda:9600/actuator/health/readiness
          metrics: http://camunda-tasklist.camunda:9600/actuator/prometheus
        - name: WebModeler WebApp
          id: webModelerWebApp
          version: 8.6.3
          url: http://localhost:8085
          readiness: http://camunda-web-modeler-webapp.camunda:8071/health/readiness
          metrics: http://camunda-web-modeler-webapp.camunda:8071/metrics
        - name: Zeebe Gateway
          id: zeebeGateway
          version: 8.6.5
          urls:
            grpc: http://localhost:26500
            http: http://localhost:8088
          readiness: http://camunda-zeebe-gateway.camunda:9600/zeebe/actuator/health/readiness
          metrics: http://camunda-zeebe-gateway.camunda:9600/zeebe/actuator/prometheus
        - name: Zeebe
          id: zeebe
          version: 8.6.5
          readiness: http://camunda-zeebe.camunda:9600/actuator/health/readiness
          metrics: http://camunda-zeebe.camunda:9600/actuator/prometheus
  ```

**How to reproduce:**

  ```
webModeler:
  enabled: true
  ingress:
    enabled: false
  contextPath: "/modeler"
  restapi:
    mail:
      smtpHost: smtp.example.com
      smtpPort: 587
      smtpUser: user
      smtpPassword: secret
      # email address to be displayed as sender of emails from Web Modeler
      fromAddress: no-reply@example.com
postgresql:
  enabled: true
```

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform:  GCP
- Helm CLI version:  version.BuildInfo{Version:"v3.16.1", GitCommit:"5a5449dc42be07001fd5771d56429132984ab3ab", GitTreeState:"dirty", GoVersion:"go1.23.1"}

- Chart version:  11.0.4
- Values file:  see above.
