### ISSUE TITLE
[ISSUE] Unable to Login to Operate in 8.7.0-alpha2 Helm Chart

### ISSUE THREAD

**Issue by slolatte** [camunda/camunda-platform-helm#2662]
**Describe the issue:**

When using the 8.7.0-alpha2 Helm Chart, I am unable to login to Operate, however I can successfully login to all other Apps.

**Actual behavior:**

See the screen recording below:

https://github.com/user-attachments/assets/9e09998e-ab61-4a8d-a332-749f05e953c7

The workflow which generated this helm chart can be seen [here](https://github.com/camunda/c8-cross-component-e2e-tests/actions/runs/12251905567/job/34177739189).

**Expected behavior:**

I should be able to successfully login to each App.

**How to reproduce:**

Setup the helm chart using the same parameters as [here](https://github.com/camunda/c8-cross-component-e2e-tests/actions/runs/12251905567/job/34177739189).

**Logs:**

The logs can be found [here](https://github.com/camunda/c8-cross-component-e2e-tests/actions/runs/12251905567/job/34177739189).

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by pedesen** [comment]
@slolatte Can you please provide more context which configuration was used here?

**Comment by slolatte** [comment]
@pedesen Here is my extra-values I used, please let me know if you need any further information:

```
global:
  identity:
    auth:
      admin:
        clientId: test
        existingSecret: "aiHie3pi"
  image:
    pullPolicy: Always
identity:
  image:
    tag: "8.7.0-alpha2"
  firstUser:
    existingSecret: null
    user: demo
    password: "yaiK7shu"
  users:
    - username: lisa
      email: cawemodev+lisa@gmail.com
      firstName: Lisa
      lastName: Doe
      password: "lisa"
      roles:
        - Identity
        - Console
        - Core
        - Optimize
        - Web Modeler
    - username: bart
      email: cawemodev+bart@gmail.com
      firstName: Bart
      lastName: Foo
      password: "bart"
      roles:
        - Identity
        - Console
        - Core
        - Optimize
        - Web Modeler
optimize:
  image:
    tag: "8.7.0-alpha2"
webModeler:
  restapi:
    image:
      tag: "8.7.0-alpha2"
  webapp:
    image:
      tag: "8.7.0-alpha2"
  websockets:
    image:
      tag: "8.7.0-alpha2"
console:
  image:
    tag: "8.7.0-alpha2"
connectors:
  image:
    tag: "8.7.0-alpha2"
  env:
    - name: username
      value: username
    - name: password
      value: password
Extra values:

Merged values:
global:
  identity:
    auth:
      admin:
        clientId: test
        existingSecret: "aiHie3pi"
  image:
    pullPolicy: Always
identity:
  image:
    tag: "8.7.0-alpha2"
  firstUser:
    existingSecret: null
    user: demo
    password: "yaiK7shu"
  users:
    - username: lisa
      email: cawemodev+lisa@gmail.com
      firstName: Lisa
      lastName: Doe
      password: "lisa"
      roles:
        - Identity
        - Console
        - Core
        - Optimize
        - Web Modeler
    - username: bart
      email: cawemodev+bart@gmail.com
      firstName: Bart
      lastName: Foo
      password: "bart"
      roles:
        - Identity
        - Console
        - Core
        - Optimize
        - Web Modeler
optimize:
  image:
    tag: "8.7.0-alpha2"
webModeler:
  restapi:
    image:
      tag: "8.7.0-alpha2"
  webapp:
    image:
      tag: "8.7.0-alpha2"
  websockets:
    image:
      tag: "8.7.0-alpha2"
console:
  image:
    tag: "8.7.0-alpha2"
connectors:
  image:
    tag: "8.7.0-alpha2"
  env:
    - name: username
      value: username
    - name: password
      value: password

```
