### ISSUE TITLE
[TASK] Add env variables for document handling

### ISSUE THREAD

**Issue by mo-okocha** [camunda/camunda-platform-helm#2757]
## Related to

Epic: https://github.com/camunda/product-hub/issues/2555

## Overview

We need to configure a Helm chart to support multiple document stores in the Camunda project. Users should be able to choose from the following supported storage options: In-Memory, GCP, AWS, and Local Storage. The Helm chart must allow users to configure the necessary environment variables for each storage type. This configuration should be applicable across all components of the Camunda project:
- Operate
- Tasklist
- Zeebe
- Optimize

### Configurations for Each Document Store
We need to support the following configuration variables for each document store (default to be the `in-memory` option, see [decision](https://camunda.slack.com/archives/C075A4LHPQD/p1737377047433089)). The Helm chart should make these variables configurable to allow users to easily set them up based on their chosen storage solution.

### AWS
_**Credential Variables:**_
- `AWS_ACCESS_KEY_ID`
- `AWS_REGION`
- `AWS_SECRET_ACCESS_KEY`

_**Store Variables:**_
- `DOCUMENT_STORE_AWS_BUCKET`
- `DOCUMENT_STORE_AWS_BUCKET_PATH`
- `DOCUMENT_STORE_AWS_BUCKET_TTL`
- `DOCUMENT_STORE_AWS_CLASS`

### GCP
_**Credential Variables**_
- `GOOGLE_APPLICATION_CREDENTIALS`

_**Store Variables**_
- `DOCUMENT_STORE_GCP_BUCKET`
- `DOCUMENT_STORE_GCP_CLASS`

### In-memory
_**Store Variables:**_
- `DOCUMENT_STORE_INMEMORY_CLASS`

### Local Storage
_**Store Variables**_
- `DOCUMENT_STORE_LOCALSTORAGE_CLASS`
- `DOCUMENT_STORE_LOCALSTORAGE_PATH`

### Other configs
- `DOCUMENT_DEFAULT_STORE_ID`: The default store ID that can be used. The supported values are `inmemory`, `localstorage`, `aws`, and `gcp`

#### Make Environment Variables Configurable in Helm Chart:

- [ ] Modify the Helm chart to allow users to easily configure the appropriate environment variables for their chosen document store.
- [ ] Keep sensitive information related to credentials in secrets

## Outcome

**Easily Configure Document Storage**: I should be able to configure different document storage backends (In-Memory, GCP, AWS, Local Storage) through the Helm chart, and set the default store.

**Support All Camunda Components**: I should ensure that the document store configuration is supported across all relevant components of the Camunda project (e.g., Tasklist, Operate), ensuring consistent behavior and access to the document store for each component.

**Ensure Secure Configuration of Credentials**: I should handle sensitive environment variables (i.e., AWS credentials, GCP keys) securely, ensuring they are properly managed and injected into the Helm chart.

```[tasklist]
### Sub-tasks
- [x] Change deployment configurations into a shared configMap via envFrom
- [x] Remove any old references prior to shared configMap configurations (_helpers, deployments)
- [x] Confirm INMEMORY is being passed correctly via configMap
- [x] Confirm LOCAL is being passed correctly via configMap
- [x] Confirm AWS is being passed correctly via configMap
- [x] Confirm GCP is being passed correctly via configMap
- [x] Test GOOGLE_APPLICATION_CREDENTIALS is pointing to the json file
- [x] Forward Port to 8.8
- [ ] https://github.com/camunda/camunda-platform-helm/issues/2972
```

**Comment by hisImminence** [comment]
As I understood, we want to have something like:

webModeler:
   documentHandling:
     enabled: true

and with this setting all the envVars, right? 

Open questions:
- I imagine document handling `enabled: false` should be the default?
- Any default values we should set?

**Comment by marcosgvieira** [comment]
@hisImminence we can align with QA for E2E testing on that.

I believe that there is a bit more than Tasklist that we can consider - Document Handling will soon be used in Operate as well to check documents, so maybe we can have something as well to be reused by all the components, Modeler, Operate, etc.

We also have options to configure DocumentHandling with GCP, AWS, In-memory and Local Storage, so the scenario here would be that a customer can choose and configure a few secrets in order to connect to those, what makes this task a bit more complex (correct me if I'm wrong)

I'm also happy to provide more context in a quick call if that helps.

**Comment by hisImminence** [comment]
To add:
- default should be the in-memory option (added to top)
- target relase: 8.7

**Comment by drodriguez-305** [comment]
@marcosgvieira I was also thinking maybe we make it a global setting in the values and add the env vars into each component. They will all be using the same variables correct? 

I have already started on this a bit but we can make changes according to whats needed. 

An example of how it would look like in values.yaml and we can then pass this into the deployment with the vars listed above. 

```
global:
  ## Document Store Configuration
  ## @extra global.documentStore These parameters are used to configure the document storage backend across all Camunda components.
  documentStore:
    ## @param global.documentStore.defaultStoreId The default store ID to use if multiple stores are enabled. Valid values: inmemory, aws, gcp, localstorage
    defaultStoreId: "inmemory"

    ## @param global.documentStore.aws.enabled Enable AWS document store configuration
    aws:
      enabled: false
      ## @param global.documentStore.aws.region AWS region for the S3 bucket
      region: ""
      ## @param global.documentStore.aws.bucket Name of the S3 bucket
      bucket: ""
      ## @param global.documentStore.aws.bucketPath (Optional) Path/prefix within the S3 bucket
      bucketPath: ""
      ## @param global.documentStore.aws.bucketTtl (Optional) Time-to-live for documents in the S3 bucket
      bucketTtl: ""
      ## @param global.documentStore.aws.class Fully qualified class name (or relevant identifier) for AWS document store
      class: ""
      ## @param global.documentStore.aws.existingSecret Reference to an existing Kubernetes secret containing AWS credentials
      existingSecret: ""
      ## @param global.documentStore.aws.accessKeyIdKey Key within the existing secret for AWS_ACCESS_KEY_ID
      accessKeyIdKey: ""
      ## @param global.documentStore.aws.secretAccessKeyKey Key within the existing secret for AWS_SECRET_ACCESS_KEY
      secretAccessKeyKey: ""

    ## @param global.documentStore.gcp.enabled Enable GCP document store configuration
    gcp:
      enabled: false
      ## @param global.documentStore.gcp.bucket Name of the GCS bucket
      bucket: ""
      ## @param global.documentStore.gcp.class Fully qualified class name (or relevant identifier) for GCP document store
      class: ""
      ## @param global.documentStore.gcp.existingSecret Reference to an existing Kubernetes secret containing GCP credentials
      existingSecret: ""
      ## @param global.documentStore.gcp.credentialsKey Key in the existing secret that contains the GCP service-account JSON
      credentialsKey: ""

    ## @param global.documentStore.inmemory.enabled Enable in-memory document store configuration
    inmemory:
      enabled: true
      ## @param global.documentStore.inmemory.class Fully qualified class name (or relevant identifier) for the in-memory document store
      class: ""

    ## @param global.documentStore.localstorage.enabled Enable local-storage document store configuration
    localstorage:
      enabled: false
      ## @param global.documentStore.localstorage.class Fully qualified class name (or relevant identifier) for local file-based document store
      class: ""
      ## @param global.documentStore.localstorage.path Path on the container’s filesystem for storing documents locally
      path: ""
```
