### ISSUE TITLE
[ISSUE] Installation fails on Openshift when ES is not enabled

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda-platform-helm#2779]
**Describe the issue:**

When trying to install camunda to Openshift with these values, it fails:

```
global:
  compatibility:
    openshift:
      adaptSecurityContext: force
  elasticsearch:
    enabled: false
  identity:
    auth:
      enabled: false
tasklist:
  enabled: false
operate:
  enabled: false
identity:
  enabled: false
identityKeycloak:
  enabled: false
connectors:
  enabled: false
elasticsearch:
  enabled: false
optimize:
  enabled: false
```
**Actual behavior:**

The installation fails with the attached error

**Expected behavior:**

The installation is successful

**How to reproduce:**

1. Use openshift as platform
2. try to install camunda using the helm chart and the values (command added below)

**Logs:**

```
$ helm install camunda camunda/camunda-platform --version 11.1.0 --skip-crds --values /tmp/camunda-platform/values.yaml

Error: INSTALLATION FAILED: template: camunda-platform/templates/zeebe/1/2/3/4/5/6/7/8/z_compatibility_helpers.tpl:87:30: executing "camunda-platform/templates/zeebe/1/2/3/4/5/6/7/8/z_compatibility_helpers.tpl" at <.Values.elasticsearch.commonLabels>: wrong type for value; expected map[string]interface {}; got interface {}
```
**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: Openshift
- Helm CLI version: unknown
- Chart version: 11.1.0
- Values file: see above
