### ISSUE TITLE
Allow to disable optimize separately from identity

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#289]
Came up in https://github.com/camunda/camunda-platform-helm/pull/287#discussion_r855150637

> :wrench:  We might want to enable identity but disable Optimize. How easy would it be here to expand to condition to allow both? i.e. if optimize.enabled and global.identity.auth.enabled ?

After research, my thought was that it might make sense to combine the condition with a tag. 

```
dependencies:
  - name: optimize
    condition: optimize.enabled
    tags:
      - identity
```

We can disable optimize via `optimize.enabled=false` or via `tags.identity=false`

- https://helm.sh/docs/chart_best_practices/dependencies/
- https://stackoverflow.com/questions/64807093/helm-dependency-condition 

related to #126
