### ISSUE TITLE
Check Optimize resource limits/requests

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#298]
Check whether we use the same resource limits as in SaaS, this is what we agreed on

related to #126

**Comment by Zelldon** [comment]
**SaaS G3-S**

|    | Limit | Request |
|----|-|-|
|Importer Replicas|1||
|Importer CPU| 1 | 0.3 |
|Import Memory | 1 | 0.4 |
|Webapp replicas | 2 |  |
| Webapp CPU | 1 | 0.3 |
| Webapp Memory | 1 | 0.4 |


Our current defaults in helm charts 
```
# Resources configuration to set request and limit configuration for the container https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits
  resources:
    requests:
      cpu: 400m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
```

**Comment by Zelldon** [comment]
I guess i would go with the same as operate currently uses, which is a kind of importer and webapp resources combined. Makes sense since we have just on deployment for now.

```
# Resources configuration to set request and limit configuration for the container https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits
  resources:
    requests:
      cpu: 600m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
```
