### ISSUE TITLE
[ISSUE] Add env variables for document handling

### ISSUE THREAD

**Issue by Szik** [camunda/camunda-platform-helm#2996]
**Describe the issue:**

[configmap for document handling](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform-alpha/templates/camunda/configmap-documentstore.yaml) uses 
- activeStoreId and
- storeId
which can differ. if different, pods fail with error such as

`java.lang.IllegalArgumentException: Default document store ID does not match any configured document store: local`

value of `DOCUMENT_DEFAULT_STORE_ID` needs to be equal to `$localPrefix` in [configmap](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform-alpha/templates/camunda/configmap-documentstore.yaml)

**Actual behavior:**

using `localstorage` as value for `activeStoreId` causes pod to end in crash loop.
configmap looks like this if `storeId` remains unchanged:

```
  DOCUMENT_DEFAULT_STORE_ID: localstorage
  DOCUMENT_STORE_LOCAL_CLASS: io.camunda.document.store.localstorage.LocalStorageDocumentStoreProvider
  DOCUMENT_STORE_LOCAL_PATH: /usr/local/zeebe
```

which causes crashloops because `LOCAL` must either be changed to
- `LOCALSTORAGE` (value of `DOCUMENT_DEFAULT_STORE_ID`) or 
- `localstorage` to `local`

**Expected behavior:**

pod is healthy and storage is working as expected

**How to reproduce:**

see above

**Logs:**

see above

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: GCP (distro-ci)
- Helm CLI version: v3.13.1
- Chart version: 0.0.0.0-rc-alpha
- Values file: 
```
global:
  documentStore:
    activeStoreId: "localstorage"
    type:
      localstorage:
        enabled: true
        storeId: "LOCAL"
        class: "io.camunda.document.store.localstorage.LocalStorageDocumentStoreProvider"
        path: "/usr/local/zeebe"

```
