### ISSUE TITLE
[TASK] Add the possibility to define a full manifest through arbitrary data in the values.yaml. 

### ISSUE THREAD

**Issue by hisImminence** [camunda/camunda-platform-helm#2999]
## Related to

Epic: https://github.com/camunda/product-hub/issues/2464

A way to define a full manifest through arbitrary data in the values.yaml. This can be done relatively easily by providing a value like this in the values.yaml:

   ```
global:
  extraManifests:
    - |
       apiVersion: v1
       kind: ConfigMap
       metadata:
         name: example-cm
       data:
         test: test
   ```

   The customer can then append an extra ingress object as show in the above example.
   Functionality like this is also present in the Bitnami Keycloak chart: `extraDeploy: []`

### Sub-tasks
-  [x] Breakdown and scope this tasks needed to implement the linked pdp feature request
- [x] add extraManifest to values
- [x] Determine either _tpl implementation or extra camunda template
- [x] Local testing and validation
- [ ] Create unit test
- [ ] Documentation for extraManifest
