### ISSUE TITLE
[ISSUE] Disabling ES makes Brokers crash loop with NPE

### ISSUE THREAD

**Issue by falko** [camunda/camunda-platform-helm#3003]
**Describe the issue:**

When I set `global.elasticsearch.enabled: false` the Zeebe Brokers fail to start. 

**Actual behavior:**

Error:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'broker' defined in io.camunda.zeebe.broker.BrokerModuleConfiguration: Failed to instantiate [io.camunda.zeebe.broker.Broker]: Factory method 'broker' threw exception with message: null
	...
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.camunda.zeebe.broker.Broker]: Factory method 'broker' threw exception with message: null
	...
Caused by: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[?:?]
	...
	at io.camunda.zeebe.broker.exporter.repo.ExporterRepository.load(ExporterRepository.java:82) ~[zeebe-broker-8.6.6.jar:8.6.6]
```

**Expected behavior:**

**How to reproduce:**

**Logs:**

```json
{
  "insertId": "5v6lyf8ruhx5svke",
  "jsonPayload": {
    "context": {
      "threadName": "main",
      "threadId": 1,
      "threadPriority": 5,
      "loggerName": "org.springframework.boot.SpringApplication"
    },
    "exception": "org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'broker' defined in io.camunda.zeebe.broker.BrokerModuleConfiguration: Failed to instantiate [io.camunda.zeebe.broker.Broker]: Factory method 'broker' threw exception with message: null\n\tat org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.14.jar:6.1.14]\n\tat org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:485) ~[spring-beans-6.1.14.jar:6.1.14]\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.14.jar:6.1.14]\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) ~[spring-beans-6.1.14.jar:6.1.14]\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.14.jar:6.1.14]\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.14.jar:6.1.14]\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.14.jar:6.1.14]\n\tat org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.14.jar:6.1.14]\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.14.jar:6.1.14]\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.14.jar:6.1.14]\n\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.14.jar:6.1.14]\n\tat org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971) ~[spring-context-6.1.14.jar:6.1.14]\n\tat org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625) ~[spring-context-6.1.14.jar:6.1.14]\n\tat org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.6.jar:3.3.6]\n\tat org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-3.3.6.jar:3.3.6]\n\tat org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) [spring-boot-3.3.6.jar:3.3.6]\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:335) [spring-boot-3.3.6.jar:3.3.6]\n\tat io.camunda.application.StandaloneBroker.main(StandaloneBroker.java:30) [camunda-zeebe-8.6.6.jar:8.6.6]\nCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.camunda.zeebe.broker.Broker]: Factory method 'broker' threw exception with message: null\n\tat org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178) ~[spring-beans-6.1.14.jar:6.1.14]\n\tat org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.14.jar:6.1.14]\n\t... 17 more\nCaused by: java.lang.NullPointerException\n\tat java.base/java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[?:?]\n\tat java.base/java.util.concurrent.ConcurrentHashMap.putIfAbsent(Unknown Source) ~[?:?]\n\tat java.base/java.lang.ClassLoader.getClassLoadingLock(Unknown Source) ~[?:?]\n\tat java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source) ~[?:?]\n\tat java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]\n\tat java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]\n\tat java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]\n\tat io.camunda.zeebe.broker.exporter.repo.ExporterRepository.load(ExporterRepository.java:82) ~[zeebe-broker-8.6.6.jar:8.6.6]\n\tat io.camunda.zeebe.broker.Broker.buildExporterRepository(Broker.java:150) ~[zeebe-broker-8.6.6.jar:8.6.6]\n\tat io.camunda.zeebe.broker.Broker.<init>(Broker.java:71) ~[zeebe-broker-8.6.6.jar:8.6.6]\n\tat io.camunda.zeebe.broker.Broker.<init>(Broker.java:49) ~[zeebe-broker-8.6.6.jar:8.6.6]\n\tat io.camunda.zeebe.broker.BrokerModuleConfiguration.broker(BrokerModuleConfiguration.java:87) ~[camunda-zeebe-8.6.6.jar:8.6.6]\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]\n\tat java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]\n\tat org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146) ~[spring-beans-6.1.14.jar:6.1.14]\n\tat org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.14.jar:6.1.14]\n\t... 17 more\n",
    "serviceContext": {
      "service": "zeebe",
      "version": "camunda"
    },
    "message": "Application run failed",
    "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "location": "europe-west1-b",
      "project_id": "camunda-researchanddevelopment",
      "container_name": "zeebe",
      "namespace_name": "camunda",
      "cluster_name": "falko-benchmark",
      "pod_name": "camunda-zeebe-0"
    }
  },
  "timestamp": "2025-02-26T12:02:31.560437482Z",
  "severity": "ERROR",
  "labels": {
    "logging.gke.io/top_level_controller_type": "StatefulSet",
    "k8s-pod/app_kubernetes_io/name": "camunda-platform",
    "k8s-pod/app_kubernetes_io/part-of": "camunda-platform",
    "k8s-pod/app": "camunda-platform",
    "k8s-pod/app_kubernetes_io/managed-by": "Helm",
    "k8s-pod/apps_kubernetes_io/pod-index": "0",
    "k8s-pod/statefulset_kubernetes_io/pod-name": "camunda-zeebe-0",
    "logging.gke.io/top_level_controller_name": "camunda-zeebe",
    "compute.googleapis.com/resource_name": "gke-falko-benchmark-pool-c2-standard--2cd7014d-g4m5",
    "k8s-pod/helm_sh/chart": "camunda-platform-11.1.0",
    "k8s-pod/app_kubernetes_io/instance": "camunda",
    "k8s-pod/app_kubernetes_io/version": "8.6.6",
    "k8s-pod/controller-revision-hash": "camunda-zeebe-5dc9b47d7c",
    "k8s-pod/app_kubernetes_io/component": "zeebe-broker"
  },
  "logName": "projects/camunda-researchanddevelopment/logs/stdout",
  "sourceLocation": {
    "file": "SpringApplication.java",
    "line": "859",
    "function": "reportFailure"
  },
  "receiveTimestamp": "2025-02-26T12:02:33.696180750Z",
  "errorGroups": [
    {
      "id": "CMPgsrWr4MPDCQ"
    }
  ]
}
```

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: GCP
- Helm CLI version: v3.15.2
- Chart version: 8.6.6
- Values file: 
```yaml
# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

global:
  image:
    tag: 8.6.6
  elasticsearch:
    enabled: FALSE
  identity:
    auth:
      # Disable the Identity authentication
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false

zeebe:
  image:
    repository: camunda/zeebe
#  nodeSelector:
#    cloud.google.com/gke-nodepool: pool-c2-standard-30
#    alpha.eksctl.io/nodegroup-name: c7g-8xlarge
  resources:
    limits:
      cpu: 30
      memory: 108Gi
    requests:
      cpu: 29
      memory: 108Gi
  clusterSize: "18"
  partitionCount: "150"
  replicationFactor: "3"
  cpuThreadCount: 20
  ioThreadCount: 8
  persistenceType: local
  pvcSize: 94Gi
  pvcStorageClassName: ssd
  env:
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_NUMBEROFSHARDS
      value: "3"
    - name: ZEEBE_BROKER_CLUSTER_RAFT_FLUSH_DELAYTIME
      value: "0"
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_EXPERIMENTAL_FEATURES_ENABLEACTORMETRICS
      value: "true"
    - name: ZEEBE_BROKER_DATA_LOGSEGMENTSIZE
      value: "16MB"
    - name: ZEEBE_BROKER_EXPERIMENTAL_RAFT_PREALLOCATESEGMENTFILES
      value: "TRUE"
    - name: ZEEBE_BROKER_EXPERIMENTAL_DISABLEEXPLICITRAFTFLUSH
      value: "FALSE"
    - name: ZEEBE_BROKER_BACKPRESSURE_ENABLED
      value: "TRUE"
    - name: ZEEBE_BROKER_BACKPRESSURE_USEWINDOWED
      value: "true"
    - name: ZEEBE_BROKER_BACKPRESSURE_ALGORITHM
      value: "aimd"
    - name: ZEEBE_BROKER_BACKPRESSURE_FIXED_LIMIT
      value: "100"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_INITIALLIMIT
      value: "100"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_ALPHA
      value: "3"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_BETA
      value: "6"
    - name: ZEEBE_BROKER_BACKPRESSURE_GRADIENT_MINLIMIT
      value: "1"
    - name: ZEEBE_BROKER_BACKPRESSURE_GRADIENT_INITIALLIMIT
      value: "100"
    - name: ZEEBE_BROKER_BACKPRESSURE_GRADIENT_RTTTOLERANCE
      value: "2"
    - name: "ZEEBE_BROKER_CLUSTER_MESSAGECOMPRESSION"
      value: "NONE"
    - name: ZEEBE_BROKER_EXPERIMENTAL_MAXAPPENDSPERFOLLOWER
      value: "2"
    - name: ZEEBE_BROKER_EXPERIMENTAL_MAXAPPENDBATCHSIZE
      value: "32KB"
    - name: ZEEBE_BROKER_EXPERIMENTAL_ROCKSDB_DISABLEWAL
      value: "TRUE"
    # Enable JSON logging for Google Cloud Stackdriver
    - name: ZEEBE_LOG_APPENDER
      value: Stackdriver
    - name: ZEEBE_LOG_STACKDRIVER_SERVICENAME
      value: zeebe
    - name: ZEEBE_LOG_STACKDRIVER_SERVICEVERSION
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
zeebeGateway:
  image:
    repository: camunda/zeebe
  replicas: 4
#  nodeSelector:
#    cloud.google.com/gke-nodepool: pool-c2-standard-30
  resources:
    limits:
      cpu: 14
      memory: 24Gi
    requests:
      cpu: 14
      memory: 24Gi
  env:
    - name: ZEEBE_GATEWAY_MONITORING_ENABLED
      value: "true"
    - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
      value: "14"
    - name: ZEEBE_GATEWAY_CLUSTER_MESSAGECOMPRESSION
      value: "NONE"
    # Enable JSON logging for Google Cloud Stackdriver
    - name: ZEEBE_LOG_APPENDER
      value: Stackdriver
    - name: ZEEBE_LOG_STACKDRIVER_SERVICENAME
      value: zeebe
    - name: ZEEBE_LOG_STACKDRIVER_SERVICEVERSION
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
operate:
  enabled: FALSE
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 2
      memory: 2Gi
  env:
    - name: CAMUNDA_OPERATE_IMPORTER_READERTHREADSCOUNT
      value: "3"
    - name: CAMUNDA_OPERATE_IMPORTER_THREADSCOUNT
      value: "3"
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_NUMBEROFSHARDS
      value: "3"
tasklist:
  enabled: false
console:  
  enabled: false
optimize:
  enabled: false
connectors:
  enabled: false
identity:
  enabled: false
  keycloak:
    enabled: false
identityKeycloak:
  enabled: false
prometheusServiceMonitor:
  enabled: true
elasticsearch:
  enabled: FALSE
  image:
    tag: 8.16.1
#  nodeSelector:
#    cloud.google.com/gke-nodepool: pool-c2-standard-30
  master:
    masterOnly: TRUE
    heapSize: 1024m
    replicaCount: 3
    persistence:
      size: 512Gi
      storageClass: 
    resources:
      limits:
        cpu: 108
        memory: 24Gi
      requests:
        cpu: 107
        memory: 24Gi
  data:
    heapSize: 0m
    resources:
      limits:
        cpu: 0
        memory: 0Gi
      requests:
        cpu: -1
        memory: 0Gi
    replicaCount: 0
    persistence:
      ## @param elasticsearch.master.persistence.size
      size: 512Gi
      storageClass: 
```
