### ISSUE TITLE
[ENHANCEMENT] Zeebe add support for additional Exporter Configuration

### ISSUE THREAD

**Issue by felicijus** [camunda/camunda-platform-helm#3144]
**Describe the use case:**

The configuration of additional Zeebe exporters are currently not supported directly via the camunda-platform Helm Chart. The usage of custom exporters should be possible natively.

UseCases See:
* [zeebe-redis-exporter](https://github.com/camunda-community-hub/zeebe-redis-exporter?tab=readme-ov-file#configuration)
* [zeebe-kafka-exporter](https://github.com/camunda-community-hub/zeebe-kafka-exporter?tab=readme-ov-file#quick-start)
* [zeebe-hazelcast-exporter](https://github.com/camunda-community-hub/zeebe-hazelcast-exporter?tab=readme-ov-file#configuration)

All of these examples of exporters expect the user to change the application.yaml of zeebe to something like this:

````yaml
zeebe:
  broker:
    exporters:
      <exporter>:
        className: <className>
        jarPath: <jarPath>
        args:
          <key: value>
````

**Describe the enhancement/feature:**

Currently camunda-platform Helm Charts only supports the [addition of Zeebe exporters by using initContainer](https://docs.camunda.io/docs/self-managed/zeebe-deployment/exporters/install-zeebe-exporters/) and environment variables. Or manually changing the Zeebe application.yaml.

This could be changed by providing a property like `additionalExporterConfig` inside values.yaml:
````yaml
zeebe:
  additionalExporterConfig:
      redis:
        className: "io.zeebe.redis.exporter.RedisExporter"
        jarPath: "/usr/local/zeebe/lib/zeebe-redis-exporter-1.0.2-jar-with-dependencies.jar"
        args:
          remoteAddress: "redis://redis:6379"
      
      kafka:
        className: "io.zeebe.kafka.exporter.KafkaExporter"
        jarPath: "/usr/local/zeebe/lib/zeebe-kafka-exporter-1.0.2-jar-with-dependencies.jar"
        args:
          bootstrapServers: "kafka:9092"
````

**Desired outcome and acceptance tests:**

Contents of a property like `additionalExporterConfig` should be rendered into the Helm Chart into the Zeebe configmap inside application.yaml to support additional exporters.
