### ISSUE TITLE
ingress.kubernetes.io/rewrite-target should be nginx.ingress.kubernetes.io/rewrite-target

### ISSUE THREAD

**Issue by falko** [camunda/camunda-platform-helm#317]
and I'd suggest to leave it commented out by default because neither sub-domain-based nor prefix-based ingress patterns seem to need it. In fact it sounds like our applications don't support rewritten URLs and rather need their context paths to be adjusted. So we might as well remove it completely.

**Comment by falko** [comment]
It looks like one is forced to set an annotation to an empty value in order to unset it. Otherwise, the default value will be always merged in, e.g.:

```yaml
    annotations:
      ingress.kubernetes.io/rewrite-target:
      ...
```
