### ISSUE TITLE
[ISSUE] Broker is missing configurations required for Multi-tenancy

### ISSUE THREAD

**Issue by houssain-barouni** [camunda/camunda-platform-helm#3199]
**Describe the issue:**

For the Zeebe REST API to work with MT enabled in versions **8.5, 8.6, and 8.7,** we need to have the following configurations:
- Spring profile: `spring.profiles.active: "identity-auth"` 
- Identity SDK configuration:
```
    camunda:
      identity:
        type: {{ include "camundaPlatform.authType" . | quote }}
        issuerBackendUrl: {{ include "camundaPlatform.authIssuerBackendUrl" . | quote }}
        audience: {{ include "zeebe.authAudience" . | quote }}
        baseUrl: {{ include "camundaPlatform.identityURL" . | quote }}
```

**Actual behavior:**

I have noticed that, within the helm chart, this configuration is missing in the broker [configMap](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform-alpha/templates/zeebe/configmap.yaml), so it may not work when embedded gateway is used.

This configuration is present in the standalone gateway [configMap](https://github.com/camunda/camunda-platform-helm/blob/0f1a15e76f4626bfcccae3e37c4b051b2147a971/charts/camunda-platform-8.6/templates/zeebe-gateway/configmap.yaml#L59-L64).

**Expected behavior:**

Configuration is present in the broker configMap (needed only when the embedded gateway is enabled)

**How to reproduce:**

https://github.com/camunda/camunda-platform-helm/blob/0f1a15e76f4626bfcccae3e37c4b051b2147a971/charts/camunda-platform-alpha/test/unit/zeebe/golden/configmap.golden.yaml

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version:  10.x.x, 11.x.x, 12.x.x
- Values file:

**Comment by hamza-m-masood** [comment]
relevant PR: https://github.com/camunda/camunda-distributions/pull/109

**Comment by hamza-m-masood** [comment]
Even with finding a solution for the above issues. I am still having trouble running 8.8 with multitenancy. I get a 403 unauthorized when access any endpoint after logging in. Here is the values.yaml I use on top of the base values.yaml:
```yaml
global:
  multitenancy:
    enabled: true
identity:
  enabled: true
identityKeycloak:
  enabled: true
  postgresql:
    auth:
      existingSecret: "integration-test-credentials"
      secretKeys:
        adminPasswordKey: "identity-keycloak-postgresql-admin-password"
        userPasswordKey: "identity-keycloak-postgresql-user-password"
  auth:
    existingSecret: "integration-test-credentials"
    passwordSecretKey: "identity-keycloak-admin-password"
identityPostgresql:
  enabled: true
  auth:
    existingSecret: integration-test-credentials

```
