### ISSUE TITLE
[ISSUE] Operate/Tasklist Redirect Errors (Port Loss/HTTP) behind Ingress Nginx (Non-Std Port 26643 + Subpath)

### ISSUE THREAD

**Issue by dawnhhhh** [camunda/camunda-platform-helm#3366]
**Describe the issue:**

When accessing the Camunda Operate UI via its configured external URL https://camunda.dawn.ltd:26643/operate, a series of incorrect HTTP 302 redirects occur, making the UI inaccessible.

**Actual behavior:**

1.  A request to `https://camunda.dawn.ltd:26643/operate` receives a 302 redirect.
2.  The `Location` header in the first redirect points to `http://camunda.dawn.ltd:26643/operate/` (incorrectly switching to HTTP, though the port is retained here).
3.  Following this redirect results in another 302 redirect.
4.  The `Location` header in the second redirect points to `https://camunda.dawn.ltd/operate/operate` (losing the non-standard port `26643` and incorrectly duplicating the `/operate` path segment).
5.  The client then attempts to connect to the standard HTTPS port 443, leading to failure.

**Expected behavior:**

1.  All redirects initiated by Operate/Tasklist should maintain the original HTTPS protocol and the non-standard port `26643`.
2.  Redirects (e.g., for authentication to Keycloak or internal routing) should point to the correct URLs, incorporating the non-standard port and the correct base path, without duplicating path segments (e.g., `https://camunda.dawn.ltd:26643/auth/...` or `https://camunda.dawn.ltd:26643/operate/...`).
3.  The Operate/Tasklist UI should load successfully after authentication via `https://camunda.dawn.ltd:26643/operate` (or `/tasklist`).

**How to reproduce:**

1. Deploy Camunda Platform 8.6.x using Helm Chart 11.3.0 in a self-managed K8s cluster.
2. Configure Ingress Nginx to handle TLS termination and expose HTTPS traffic on a non-standard port (e.g., `26643`).
3. Configure Camunda component Ingress resources (using `operate.ingress`, `tasklist.ingress`, `identityKeycloak.ingress`, etc. in values.yaml) with the correct hostname, respective subpaths (`/operate`, `/tasklist`, `/auth`), `pathType: Prefix`, and TLS settings referencing the correct secret. Ensure `nginx.ingress.kubernetes.io/backend-protocol: HTTP` annotation is set and no `rewrite-target` is used for Operate/Tasklist.
4. Ensure the` ingress-nginx-controller` Service correctly maps external port `26643 `to the controller's `https `target port.
5. Attempt to access `https://camunda.dawn.ltd:26643/operate` in a browser or using `curl -Lv`.

**Logs:**

```
[root@node01 ~]# curl -Lv https://camunda.dawn.ltd:26643/operate
* About to connect() to camunda.dawn.ltd port 26643 (#0)
*   Trying 12x.19x.13x.13x...
* Connected to camunda.dawn.ltd (12x.19x.13x.13x) port 26643 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.camunda.dawn.ltd
* 	start date: Feb 28 00:00:00 2025 GMT
* 	expire date: May 29 23:59:59 2025 GMT
* 	common name: *.camunda.dawn.ltd
* 	issuer: CN=ZeroSSL ECC Domain Secure Site CA,O=ZeroSSL,C=AT
> GET /operate HTTP/1.1
> User-Agent: curl/7.29.0
> Host: camunda.dawn.ltd:26643
> Accept: */*
> 
< HTTP/1.1 302 
< Date: Fri, 11 Apr 2025 02:16:33 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Location: http://camunda.dawn.ltd:26643/operate/
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< 
* Ignoring the response-body
* Connection #0 to host camunda.dawn.ltd left intact
* Issue another request to this URL: 'http://camunda.dawn.ltd:26643/operate/'
* Found bundle for host camunda.dawn.ltd: 0x192bee0
* Re-using existing connection! (#0) with host camunda.dawn.ltd
* Connected to camunda.dawn.ltd (122.190.133.134) port 26643 (#0)
> GET /operate/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: camunda.dawn.ltd:26643
> Accept: */*
> 
< HTTP/1.1 302 
< Date: Fri, 11 Apr 2025 02:16:33 GMT
< Content-Length: 0
< Connection: keep-alive
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Frame-Options: DENY
< Content-Security-Policy: default-src 'self'; base-uri 'self'; script-src 'self'; script-src-elem 'self' cdn.jsdelivr.net; connect-src 'self' cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' cdn.jsdelivr.net; img-src * data:; block-all-mixed-content; form-action 'self'; frame-ancestors 'none'; frame-src 'self' https:; object-src 'none'; font-src 'self' fonts.camunda.io cdn.jsdelivr.net; worker-src 'self' blob:; sandbox allow-forms allow-scripts allow-same-origin allow-popups
< Location: https://camunda.dawn.ltd/operate/operate
< Content-Language: en-US
< 
* Connection #0 to host camunda.dawn.ltd left intact
* Issue another request to this URL: 'https://camunda.dawn.ltd/operate/operate'
* Found bundle for host camunda.dawn.ltd: 0x192bee0
* About to connect() to camunda.dawn.ltd port 443 (#1)
*   Trying 12x.19x.13x.13x...
* Connection timed out
* Failed connect to camunda.dawn.ltd:443; Connection timed out
* Closing connection 1
curl: (7) Failed connect to camunda.dawn.ltd:443; Connection timed out
```

**Environment:**

- Platform: Self-Managed Kubernetes v1.28.3 + Ingress Nginx v1.12.0 (from chart ingress-nginx-4.12.0)
- Helm CLI version: v3.12.0
- Chart version: camunda-platform-11.3.0
- Values file: https://github.com/dawnhhhh/c8-k8s/blob/main/values.yaml

**Comment by aabouzaid** [comment]
@dawnhhhh the components Ingress is used only if you want to make it work on a different host (e.g. `operate.camunda.example.com`).

If you want to use the global Ingress with a subpath like `camunda.example.com/operate`, then you need to set it under `global.ingress`:

https://github.com/dawnhhhh/c8-k8s/blob/a5519b90b2ae6f8c8b6b4423cbfbd68d89aa4742/values.yaml#L101

For more details, please check the guide on the official docs: [Combined and separated Ingress setup - 8.6](https://docs.camunda.io/docs/8.6/self-managed/setup/guides/ingress-setup/).

**Comment by dawnhhhh** [comment]
Thank you for your reply.But after configuring `global.ingress`, this issue still persists for `https://camunda.dawn.ltd:26643/tasklist` and `https://camunda.dawn.ltd:26643/operate`. Other subpaths are accessible normally.
My ingress.yaml configuration is as follows:
`global:
  ingress:
    enabled: true
    className: nginx
    host: "camunda.dawn.ltd"
    tls:
      enabled: true
      secretName: "tls-dawn"
  identity:
    auth:
      publicIssuerUrl: "https://camunda.dawn.ltd:26643/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://camunda.dawn.ltd:26643/operate"
      tasklist:
        redirectUrl: "https://camunda.dawn.ltd:26643/tasklist"
      optimize:
        redirectUrl: "https://camunda.dawn.ltd:26643/optimize"

identity:
  contextPath: "/identity"
  fullURL: "https://camunda.dawn.ltd:26643/identity"

  keycloak: 
    ingress: 
      enabled: true
      ingressClassName: nginx
      hostname: "camunda.dawn.ltd"
    extraEnvVars: 
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_FRONTEND_URL
        value: "https://camunda.dawn.ltd:26643/auth/"

operate:
  contextPath: "/operate"
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    path: /
    host: "camunda.dawn.ltd"
    tls:
      enabled: true
      secretName: "tls-dawn"

optimize:
  contextPath: "/optimize"
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: 'true' 
    path: /
    host: "camunda.dawn.ltd"
    tls:
      enabled: true
      secretName: "tls-dawn"

tasklist:
  contextPath: "/tasklist"
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    path: /
    host: "camunda.dawn.ltd"
    tls:
      enabled: true
      secretName: "tls-dawn"

zeebeGateway:
  ingress:
    grpc:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: 'false'
        nginx.ingress.kubernetes.io/backend-protocol: 'GRPC'
        nginx.ingress.kubernetes.io/proxy-buffer-size: '128k'
      host: "zeebe.camunda.dawn.ltd"
      tls:
        enabled: true
        secretName: "tls-dawn"`

**Comment by dawnhhhh** [comment]
Thank you for your response! I tried your suggestion, after configuring `global.ingress`, this issue still persists for `https://camunda.dawn.ltd:26643/tasklist` and `https://camunda.dawn.ltd:26643/operate`. Other subpaths are accessible normally.Here’s the configuration I’m using: 
```
global:
  ingress:
    enabled: true
    className: nginx
    host: "camunda.dawn.ltd"
    tls:
      enabled: true
      secretName: "tls-dawn"
  identity:
    auth:
      publicIssuerUrl: "https://camunda.dawn.ltd:26643/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://camunda.dawn.ltd:26643/operate"
      tasklist:
        redirectUrl: "https://camunda.dawn.ltd:26643/tasklist"
      optimize:
        redirectUrl: "https://camunda.dawn.ltd:26643/optimize"

identity:
  contextPath: "/identity"
  fullURL: "https://camunda.dawn.ltd:26643/identity"

  keycloak: 
    ingress: 
      enabled: true
      ingressClassName: nginx
      hostname: "camunda.dawn.ltd"
    extraEnvVars: 
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_FRONTEND_URL
        value: "https://camunda.dawn.ltd:26643/auth/"

operate:
  contextPath: "/operate"
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    path: /
    host: "camunda.dawn.ltd"
    tls:
      enabled: true
      secretName: "tls-dawn"

optimize:
  contextPath: "/optimize"
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: 'true' 
    path: /
    host: "camunda.dawn.ltd"
    tls:
      enabled: true
      secretName: "tls-dawn"

tasklist:
  contextPath: "/tasklist"
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    path: /
    host: "camunda.dawn.ltd"
    tls:
      enabled: true
      secretName: "tls-dawn"

zeebeGateway:
  ingress:
    grpc:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: 'false'
        nginx.ingress.kubernetes.io/backend-protocol: 'GRPC'
        nginx.ingress.kubernetes.io/proxy-buffer-size: '128k'
      host: "zeebe.camunda.dawn.ltd"
      tls:
        enabled: true
        secretName: "tls-dawn"
```
Let me know if I missed something.

**Comment by dawnhhhh** [comment]
@aabouzaid Thank you again. Based on your suggestions,I have adjusted the ingress.yaml, The specific behavior is outlined below(this issue only occurs with the Tasklist and Operate components):

https://github.com/user-attachments/assets/82d4ac4b-9135-447d-924c-777a64e47050

```
global:
  ingress:
    enabled: true
    className: nginx
    host: "camunda.hcxw.ltd"
  identity:
    auth:
      publicIssuerUrl: "https://camunda.hcxw.ltd:26643/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://camunda.hcxw.ltd:26643/operate"
        existingSecret:
          name: components-secret
      tasklist:
        redirectUrl: "https://camunda.hcxw.ltd:26643/tasklist"
        existingSecret:
          name: components-secret
      optimize:
        redirectUrl: "https://camunda.hcxw.ltd:26643/optimize"
        existingSecret:
          name: components-secret
      connectors:
        redirectUrl: "https://camunda.hcxw.ltd:26643/connectors"
        existingSecret:
          name: components-secret

identity:
  contextPath: "/identity"
  fullURL: "https://camunda.hcxw.ltd:26643/identity"

operate:
  contextPath: "/operate"

optimize:
  contextPath: "/optimize"

tasklist:
  contextPath: "/tasklist"

connectors:
  contextPath: "/connectors"

zeebeGateway:
  ingress:
    grpc:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: 'false'
        nginx.ingress.kubernetes.io/backend-protocol: 'GRPC'
        nginx.ingress.kubernetes.io/proxy-buffer-size: '128k'
      host: "zeebe.camunda.hcxw.ltd"
      tls:
        enabled: true
        secretName: "tls-hcxw"
```

**Comment by aabouzaid** [comment]
@dawnhhhh what you want to achieve is not related to Camunda but the Ingress controller. In the controller config (which is not part of the Camunda apps), you set the default ports of HTTP and HTTPS to the port you want. Once you do that, it will be the default port.

If you are using Helm chart for [ingress-nginx Ingress controller](https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx), it will be something around this:

```
[...]
  controller:
    service:
      ports:
        http: 26680
        https: 26643
```
