### ISSUE TITLE
[ISSUE][8.8] Keycloak service port is not rendered in Ingress

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#3381]
**Describe the issue:**

@zalanszak [reported](https://camunda.slack.com/archives/C03UR0V2R2M/p1744659905318179) that the Keycloak service port is not rendered in Ingress in the 8.8 chart.

```
---
# Source: camunda-platform/templates/camunda/ingress-http.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
[...]
spec:
  ingressClassName: nginx
  rules:
    - host: camunda.example.com
      http:
        paths:
          - backend:
              service:
                name: debug-keycloak
                port:
                  number:
```

**Actual behavior:**

After debugging the issue, looks like it was a [copy/paste glitch](https://github.com/camunda/camunda-platform-helm/commit/c9676c82a4ad5ca5564c878d57b2726d1f46e178#diff-e4dd32133d4a77534d903c26ad09bc462e5b43a4821e94308a8026bfe6575ba7R129-L134) and it was not discovered because we disable Keycloak for 8.8 alpha as there is an ongoing refactoring of the Camunda Identity flow.

**Expected behavior:**

The port should be rendered when the Keycloak is enabled.

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: Any
- Helm CLI version: v3.17.2
- Chart version: 8.8 alpha snapshot ([7282631](https://github.com/camunda/camunda-platform-helm/commit/7282631e166248f38b00ebd6b05e8c7013ed1ad4))
- Values file: Check the Slack thread.
