### ISSUE TITLE
[ENHANCEMENT] Enable Reliable Re-Runs of OpenSearch Workflows by Cleaning Up All QA Clusters

### ISSUE THREAD

**Issue by slolatte** [camunda/camunda-platform-helm#3415]
**Describe the use case:**

In the current QA setup, we can only run the OpenSearch-based tests once in a 24-hour period. This is because we only clean the OpenSearch database used by the workflow under test, but not other QA clusters in the Distro CI cluster that also use OpenSearch. This leads to data contamination and unreliable test results when re-running workflows within the same day.

This limitation prevents us from triggering these workflows on demand—such as during release testing—without risking test interference.

**Describe the enhancement/feature:**

We need to enhance the existing cleanup step in the workflows. In addition to resetting the OpenSearch DB used by the workflow under test, we should also identify and delete any other QA clusters in the Distro CI cluster that are using OpenSearch and could interfere with test data.

This extended cleanup should happen at the beginning of each workflow, ensuring test environments remain isolated and clean across runs.

This applies to the following workflows:

- [Workflow 1](https://github.com/camunda/c8-cross-component-e2e-tests/blob/main/.github/workflows/playwright_sm_manual_opensearch.yml)
- [Workflow 2](https://github.com/camunda/c8-cross-component-e2e-tests/blob/main/.github/workflows/playwright_sm_nightly_tests_opensearch.yml)

**Desired outcome and acceptance tests:**

- OpenSearch-based workflows can be safely re-run multiple times within a 24-hour window.
- The cleanup process at the start of each workflow:
- Resets the OpenSearch DB used by the workflow.
- Deletes any QA clusters in Distro CI using OpenSearch.
- Test data does not persist across different QA environments.
- Tests remain stable and isolated when workflows are re-run manually or during release testing.

# pull requests from @hamza-m-masood :
PR for E2E Repo: https://github.com/camunda/c8-cross-component-e2e-tests/pull/875
PR for skipping elasticsearch preflight: https://github.com/camunda/camunda-platform-helm/pull/3516
PR for clean up opensearch indices: https://github.com/camunda/camunda-platform-helm/pull/3536
PR for ES preflight fix: https://github.com/camunda/camunda-platform-helm/issues/3415
PR for backporting ES preflight to 8.6 and 8.8: https://github.com/camunda/camunda-platform-helm/pull/3572

**Comment by slolatte** [comment]
@hamza-m-masood  Based on the latest nightly run ([link](https://github.com/camunda/c8-cross-component-e2e-tests/actions/runs/14788021846)), I think we should take another look at the OpenSearch DB cleanup itself—not just the cleanup of other QA OpenSearch clusters in Distro CI.

The same issues we’ve seen before are still showing up, which suggests the DB might not be fully wiped between runs. Since the TTL has already been reduced and no other QA OpenSearch clusters were active during the test, I suspect the root cause may still lie within the DB reset step in the workflow.

For more context, please see the following [Slack thread](https://camunda.slack.com/archives/C06BN4SRB6C/p1746169832627069).

**Comment by hamza-m-masood** [comment]
I am looking at the workflows to understand the current state

**Comment by hamza-m-masood** [comment]
Everything is deleted.
I will manually test the following:
1. Deploy camunda with custom instance prefixes
2. Deploy another camunda instance with custom prefixes and see if there are any errors
3. Delete one of the camunda instances
4. Deploy another instance with custom prefix to see for any errors

**Comment by hamza-m-masood** [comment]
I cam across a bug when running the chart on OpenShift with elasticsearch disabled. I created a PR for it: https://github.com/camunda/camunda-platform-helm/pull/3472

**Comment by hamza-m-masood** [comment]
I see that the prefix option for OpenSearch is not working properly. I see default prefixes in the opensearch DB even when I specified:
`global.opensearch.prefix: e2ecct`

**Comment by hamza-m-masood** [comment]
I see that the openserach DB has been modified. I will delete it and create again.

**Comment by hamza-m-masood** [comment]
I can run two camunda instances at the same time in an OpenSearch DB using custom prefixes for both the application and the bpmn deployments. Here is the values.yaml to run camunda with full custom prefixes:
```
global:
  image:
    pullPolicy: Always
  elasticsearch:
    enabled: false
  opensearch:
    enabled: true
    # aws:
    #   enabled: true
    auth:
      username: test
      password: "test"
    url:
      protocol: https
      host: search-qa-e2e-test.es.amazonaws.com
      port: 443

elasticsearch:
  enabled: false

zeebeGateway:
  replicas: 1
  env:
    - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
      value: none
zeebe:
  env:
    - name: ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_INDEX_PREFIX
      value: second-zeebe

operate:
  env:
    - name: CAMUNDA_OPERATE_OPENSEARCH_INDEXPREFIX
      value: second-operate
    - name: CAMUNDA_OPERATE_ZEEBEOPENSEARCH_PREFIX
      value: second-zeebe
  migration:
    env:
      - name: CAMUNDA_OPERATE_OPENSEARCH_INDEXPREFIX
        value: second-op-migration
      - name: CAMUNDA_OPERATE_ZEEBEOPENSEARCH_PREFIX
        value: second-zeebe

tasklist:
  env:
    - name: CAMUNDA_TASKLIST_OPENSEARCH_INDEXPREFIX
      value: second-tasklist
    - name: CAMUNDA_TASKLIST_ZEEBEOPENSEARCH_PREFIX
      value: second-zeebe

optimize:
  env:
    - name: CAMUNDA_OPTIMIZE_OPENSEARCH_SETTINGS_INDEX_PREFIX
      value: second-optimize
    - name: CAMUNDA_OPTIMIZE_OPENSEARCH_SETTINGS_INDEX_PREFIX
      value: second-zeebe
  migration:
    env:
      - name: CAMUNDA_OPTIMIZE_ZEEBE_NAME
        value: second-opz-migration
      - name: CAMUNDA_OPTIMIZE_OPENSEARCH_SETTINGS_INDEX_PREFIX
        value: second-zeebe

```
