### ISSUE TITLE
[ENHANCEMENT] implement javaOpts for all components

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#3417]
**Describe the use case:**

Users of java applications are familiar with the environment variable `JAVA_TOOL_OPTIONS`, which is used to supply options to the JVM. in Zeebe and Zeebe Gateway, we support a `javaOpts` option to use a default and it easily lets customers modify the whole thing, or just append the extra arguments they want.

However, in some cases, as part of the helm chart, we will configure `JAVA_TOOL_OPTIONS`, such as when `global.opensearch.tls` is configured. In these cases, a customer may set 

```yaml
zeebe:
  env:
    - name: JAVA_TOOL_OPTIONS
      value: extra arguments
```
and that will override the settings our helm chart may set by default.

components are also not being very uniform about this (like operate not having javaOpts), 

**Describe the enhancement/feature:**

We introduce the key `javaOpts` to be used in place of `JAVA_TOOL_OPTIONS`, implement it for all java components, and if we need to add options to it as part of the helm chart, such as for a custom TLS keystore, we can append `javaOpts` to the env var we already declare in the `env` section for `JAVA_TOOL_OPTIONS`.

So lets say

```yaml

global:
  opensearch:
    tls:
      enabled: true

operate:
  javaOpts: >-
    -DMxMem=6Gb
```

then the resulting `JAVA_TOOL_OPTIONS` should be 

```
- name: JAVA_TOOL_OPTIONS
  value: -Dssl.keystore=something.p12 -DMxMem=6Gb
```

**Desired outcome and acceptance tests:**
