### ISSUE TITLE
[ISSUE] 8.8 helper function for keycloak port not functioning properly

### ISSUE THREAD

**Issue by hamza-m-masood** [camunda/camunda-platform-helm#3448]
**Describe the issue:**

This helper function is not working properly in 8.8:
https://github.com/camunda/camunda-platform-helm/blob/c68c68170d4e364862aa561faa98a550ec68ef7b/charts/camunda-platform-8.8/templates/identity/_helpers.tpl#L166C1-L178C12

This helper function results in the following ingress object:
```yaml
spec:
  rules:
    - host: hamzatest.ci.distro.ultrawombat.com
      http:
        paths:
            ...
          - backend:
              service:
                name: camunda-keycloak
                port:
                  number: 
            path: /auth/
            pathType: Prefix

```

The port number is missing when keycloak is enabled.

Here is the values.yaml I used:
```yaml
global:
  secrets:
    autoGenerated: true
    name: "integration-test-credentials"
  ingress:
    enabled: true
    className: nginx
    # The Ingress host will be added via CLI.
    host: "hamzatest.ci.distro.ultrawombat.com"
    tls:
      enabled: true
      # A wildcard certificate will be used.
      secretName: camunda-platform
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "{{ .Values.global.ingress.host }}"
      external-dns.alpha.kubernetes.io/ttl: "60"
  identity:
    auth:
      publicIssuerUrl: "https://{{ .Values.global.ingress.host }}/auth/realms/camunda-platform"
      admin:
        enabled: true
        existingSecret:
          name: "integration-test-credentials"
      #######################
      # Management Group
      #######################
      webModeler:
        redirectUrl: "https://{{ .Values.global.ingress.host }}/modeler"
      console:
        redirectUrl: "https://{{ .Values.global.ingress.host }}"
        existingSecret:
          name: "integration-test-credentials"
      #######################
      # Orchestration Group
      #######################
      core:
        redirectUrl: "https://{{ .Values.global.ingress.host }}/core"
        existingSecret:
          name: "integration-test-credentials"
      connectors:
        existingSecret:
          name: "integration-test-credentials"
      optimize:
        redirectUrl: "https://{{ .Values.global.ingress.host }}/optimize"
        existingSecret:
          name: "integration-test-credentials"

identity:
  contextPath: "/identity"
  firstUser:
    existingSecret: "integration-test-credentials"

identityKeycloak:
  enabled: true
  postgresql:
    auth:
      existingSecret: "integration-test-credentials"
      secretKeys:
        adminPasswordKey: "identity-keycloak-postgresql-admin-password"
        userPasswordKey: "identity-keycloak-postgresql-user-password"
  auth:
    existingSecret: "integration-test-credentials"
    passwordSecretKey: "identity-keycloak-admin-password"

```

**Actual behavior:**

ingress object fails to render correctly

**Expected behavior:**

ingress object renders correctly

**How to reproduce:**

values.yaml given

**Logs:**

error output given

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 8.8
- Values file:
