### ISSUE TITLE
[ISSUE] 13.0.0-alpha4 requires contextPath for Optimize, even if disabled.

### ISSUE THREAD

**Issue by ManuelDittmar** [camunda/camunda-platform-helm#3490]
**Describe the issue:**

When defining an ingress, the helm chart is expecting a context path for optimize, even if optimize is disabled.

**Actual behavior:**

```
Error: INSTALLATION FAILED: 1 error occurred:
	* Ingress.networking.k8s.io "camunda-camunda-platform-http" is invalid: spec.rules[0].http.paths[1].path: Invalid value: "": must be an absolute path
**Expected behavior:**

```

**How to reproduce:**

helm install camunda camunda/camunda-platform -f values.yaml --version 13.0.0-alpha4

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: GCP
- Helm CLI version: version.BuildInfo{Version:"v3.16.1", GitCommit:"5a5449dc42be07001fd5771d56429132984ab3ab", GitTreeState:"dirty", GoVersion:"go1.23.1"}
- Chart version: 13.0.0-alpha4
- Values file: 

```
global:
  security:
    authentication:
      method: oidc
  multitenancy:
    enabled: false # why does this require database?
  ingress:
    enabled: true
    className: nginx
    host: "example.de"
    tls:
      enabled: true
      secretName: camunda-tls
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  identity:
    auth:
      issuer: https://login.microsoftonline.com/ATENANTID/v2.0
      # this is used for container to container communication
      issuerBackendUrl: https://login.microsoftonline.com/ATENANTID/v2.0
      tokenUrl: https://login.microsoftonline.com/ATENANTID/oauth2/v2.0/token
      jwksUrl: https://login.microsoftonline.com/ATENANTID/discovery/v2.0/keys
      type: "MICROSOFT"
      publicIssuerUrl: https://login.microsoftonline.com/ATENANTID/v2.0
      identity:
        clientId: xxx
        existingSecret: xxx
        audience: xxx
        initialClaimValue: xxx
        redirectUrl: https://example.de/identity
      core:
        clientId: xxx
        audience: xxx
        existingSecret: xxx
        redirectUrl: https://example.de/core
      connectors:
        clientId: xxx
        existingSecret: xxx

identity:
  enabled: false
  contextPath: "/identity"
  fullURL: "https://example.de/identity"

identityPostgresql:
  enabled: false
  auth:
    existingSecret: password

console:
  enabled: false
  contextPath: "/console"
  env:
  - name: CAMUNDA_CONSOLE_TELEMETRY_ENABLED
    value: "true"
  - name: CAMUNDA_CONSOLE_CUSTOMERID
    value: manuel.dittmar
  - name: CAMUNDA_CONSOLE_INSTALLATIONID
    value: console-8-8-assessment

webModeler:
  contextPath: "/modeler"
  enabled: false
  restapi:
    mail:
      smtpHost: smtp.example.com
      smtpPort: 587
      smtpUser: user
      smtpPassword: secret
      # email address to be displayed as sender of emails from Web Modeler
      fromAddress: no-reply@example.com

webModelerPostgresql:
  enabled: false
  auth:
    existingSecret: password

core:
  contextPath: "/core" # why required?
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  env:
  - name: VALUES_CAMUNDA_CORE_CLIENT_SECRET
    value: xxx
  ingress:
    grpc:
      enabled: true
      className: nginx
      host: "zeebe.example.de"
      tls:
        enabled: true
        secretName: zeebe-tls
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        ingress.kubernetes.io/rewrite-target: "/"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"

optimize:
  enabled: false

prometheusServiceMonitor:
  enabled: true

elasticsearch:
  master:
    masterOnly: false
    replicaCount: 1
```
