### ISSUE TITLE
[ISSUE] 13.0.0-alpha4 enforces secret creation for env VALUES_CAMUNDA_CORE_CLIENT_SECRET

### ISSUE THREAD

**Issue by ManuelDittmar** [camunda/camunda-platform-helm#3492]
**Describe the issue:**

I want to hardcode secrets in values.yaml for local testing. For most secrets this works, but for the core component there is a mapping for the environment variable VALUES_CAMUNDA_CORE_CLIENT_SECRET

```
    Environment:
      CAMUNDA_LICENSE_KEY:                <set to the key 'CAMUNDA_LICENSE_KEY' in secret 'camunda-camunda-platform-license'>  Optional: false
      LC_ALL:                             C.UTF-8
      K8S_NAME:                           camunda-zeebe-0 (v1:metadata.name)
      K8S_SERVICE_NAME:                   camunda-core
      K8S_NAMESPACE:                      default (v1:metadata.namespace)
      VALUES_CAMUNDA_CORE_CLIENT_SECRET:  <set to the key 'identity-core-client-token' in secret 'camunda-core-identity-secret'>  Optional: false
```

**Actual behavior:**

`  Warning  Failed                  13s (x5 over 53s)  kubelet                  Error: secret "camunda-core-identity-secret" not found`

**Expected behavior:**

If I overwrite the env, I don't have to create the secret.

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: GCP
- Helm CLI version: version.BuildInfo{Version:"v3.16.1", GitCommit:"5a5449dc42be07001fd5771d56429132984ab3ab", GitTreeState:"dirty", GoVersion:"go1.23.1"}
- Chart version: 13.0.0-alpha4
- Values file: 
```
global:
  security:
    authentication:
      method: oidc
  multitenancy:
    enabled: false # why does this require database?
  ingress:
    enabled: true
    className: nginx
    host: "example.de"
    tls:
      enabled: true
      secretName: camunda-tls
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  identity:
    auth:
      issuer: https://login.microsoftonline.com/ATENANTID/v2.0
      # this is used for container to container communication
      issuerBackendUrl: https://login.microsoftonline.com/ATENANTID/v2.0
      tokenUrl: https://login.microsoftonline.com/ATENANTID/oauth2/v2.0/token
      jwksUrl: https://login.microsoftonline.com/ATENANTID/discovery/v2.0/keys
      type: "MICROSOFT"
      publicIssuerUrl: https://login.microsoftonline.com/ATENANTID/v2.0
      identity:
        clientId: xxx
        existingSecret: xxx
        audience: xxx
        initialClaimValue: xxx
        redirectUrl: https://example.de/identity
      core:
        clientId: xxx
        audience: xxx
        existingSecret: xxx
        redirectUrl: https://example.de/core
      connectors:
        clientId: xxx
        existingSecret: xxx

identity:
  enabled: false
  contextPath: "/identity"
  fullURL: "https://example.de/identity"

identityPostgresql:
  enabled: false
  auth:
    existingSecret: password

console:
  enabled: false
  contextPath: "/console"
  env:
  - name: CAMUNDA_CONSOLE_TELEMETRY_ENABLED
    value: "true"
  - name: CAMUNDA_CONSOLE_CUSTOMERID
    value: manuel.dittmar
  - name: CAMUNDA_CONSOLE_INSTALLATIONID
    value: console-8-8-assessment

webModeler:
  contextPath: "/modeler"
  enabled: false
  restapi:
    mail:
      smtpHost: smtp.example.com
      smtpPort: 587
      smtpUser: user
      smtpPassword: secret
      # email address to be displayed as sender of emails from Web Modeler
      fromAddress: no-reply@example.com

webModelerPostgresql:
  enabled: false
  auth:
    existingSecret: password

core:
  contextPath: "/core" # why required?
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  env:
  - name: VALUES_CAMUNDA_CORE_CLIENT_SECRET
    value: xxx
  ingress:
    grpc:
      enabled: true
      className: nginx
      host: "zeebe.example.de"
      tls:
        enabled: true
        secretName: zeebe-tls
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        ingress.kubernetes.io/rewrite-target: "/"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"

optimize:
  contextPath: "/optimize" # why?=
  enabled: false

prometheusServiceMonitor:
  enabled: true

elasticsearch:
  master:
    masterOnly: false
    replicaCount: 1
```
