### ISSUE TITLE
[ISSUE] /modeler redirect infinitely with permanent redirect

### ISSUE THREAD

**Issue by ThibaultLesuisse** [camunda/camunda-platform-helm#3495]
**Describe the issue:**

Installed self-managed Camunda with combined ingress controller on Azure Kubernetes Services with AGIC (Application gateway Ingress Controller). All applications work correctly but the webmodeler has an infinite redirect loop because it returns a 301 permanent redirect.

**Actual behavior:**

301 permanent redirect loop

**Expected behavior:**

the webmodeler

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: AKS
- Helm CLI version: 
- Chart version: 12.0.1
- Values file: 
``` yaml
global:
      secrets:
        autofGenerate: true
      defaultStorageClass: "azurefile-csi-nfs"
      storageClass: "azurefile-csi-nfs"
      identity:
        auth:
          publicIssuerUrl: https://camunda-dev.riziv.tstdev/auth/realms/camunda-platform
          operate:
            redirectUrl: "https://camunda-dev.riziv.tstdev/operate"
            existingSecret:
              name: identity-secret-for-components
          tasklist:
            redirectUrl: "https://camunda-dev.riziv.tstdev/tasklist"
            existingSecret:
              name: identity-secret-for-components
          optimize:
            redirectUrl: "https://camunda-dev.riziv.tstdev/optimize"
            existingSecret:
              name: identity-secret-for-components
          connectors:
            existingSecret:
              name: identity-secret-for-components
          identity:
            redirectUrl: "https://camunda-dev.riziv.tstdev/identity"
          console:
            existingSecret:
              name: identity-secret-for-components
          webModeler:
            redirectUrl: "https://camunda-dev.riziv.tstdev/modeler"

      ingress:
        enabled: true
        className: ''
        host: kubecamunda-dev.riziv.tstdev
        annotations:
          appgw.ingress.kubernetes.io/use-private-ip: 'true'
          kubernetes.io/ingress.class: azure/application-gateway

    identityPostgresql:
      enabled: true
      postgresql:
        volumePermissions:
          enabled: true

    identity:
      enabled: true
      contextPath: /identity
      fullURL: https://camunda-dev.riziv.tstdev/identity
      keycloak:
        enabled: true

    operate:
      contextPath: /operate

    optimize:
      contextPath: /optimize

    tasklist:
      contextPath: /tasklist

    console:
      contextPath: "/console"

    connectors:
      contextPath: "/connectors"

    identityKeycloak:
      postgresql:
        volumePermissions:
          enabled: true
        image:
          debug: true
      extraEnvVars:
        - name: KC_HOSTNAME
          value: "camunda-dev.riziv.tstdev"
        - name: KC_HOSTNAME_PORT
          value: "443"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KC_PROXY
          value: "edge"
        - name: KEYCLOAK_FRONTEND_URL
          value: "https://camunda-dev.riziv.tstdev/auth"

    zeebe:
      enabled: true
      clusterSize: 1
      partitionCount: 1
      replicationFactor: 1
      pvcStorageClassName: private-azurefile-csi
      resources:
        requests:
          cpu: 500m
          memory: 1Gi

    zeebeGateway:
      contextPath: "/zeebe"

    elasticsearch:
      enabled: true
      master:
        replicaCount: 1
        resources:
          limits:
            cpu: "4"
            memory: "6Gi"
          requests:
            cpu: "1"
            memory: "1Gi"

    webModeler:
      enabled: true
      contextPath: /modeler
      restapi:
        mail:
          smtpHost: smtp.example.com
          smtpPort: 587
          smtpUser: user
          smtpPassword: secret
          fromAddress: noreply@example.com
      websockets:
        publicHost: "https://camunda-dev.riziv.tstdev/modeler-ws"
        publicPort: "443"

    postgresql:
      enabled: true
      auth:
        existingSecret: "poc-postgresql"
        secretKeys:
          adminPasswordKey: "postgres-password"
          userPasswordKey: "password"
```
