### ISSUE TITLE
[TASK] Document and support use of self-signed certs with AWS OpenSearch

### ISSUE THREAD

**Issue by eamonnmoloney** [camunda/camunda-platform-helm#3498]
## Related to

[SUPPORT-27289](https://jira.camunda.com/browse/SUPPORT-27289)
[SUPPORT-27290](https://jira.camunda.com/browse/SUPPORT-27290)

## Overview

As part of the 8.6.7 update on all services, the library used to connect to OpenSearch changed to use OS standard TLS cert resolution, rather than Java resolution. This means, for connections to OpenSearch, the library expects to find the trusted keychain in the OS.

This only effects the connection to OpenSearch if that connection uses self-signed certs because the library can no longer find the trusted chain.

In 8.6.6 and before, we used a library that used the Java keystore rather than the OS keystore.

The effect of this is, all services using OpenSearch with self-signed certs required BOTH a Java keystore and a trusted chain in the OS.

## Workaround

_Hint: This workaround requires root access . If this is not permitted, set the SSL_CERT_FILE envVar in the pods, pointing to the PEM cert file._ 

To fix the issue, one can add a CA certificate into a ConfigMap or Secret, and mount it in the relevant pods.

In Camunda 8.7, the affected pods are:
* Operate, Tasklist, Optimize, and Zeebe

In Camunda 8.8, the affected pods are:
   * core (which includes Operate, Tasklist, and Zeebe)
   * optimize (separate pod)
 
One needs an init container (running as root) to copy the certificate into the container’s trusted certificate store and run update-ca-certificates.

#### Example Configuration
**1. Create a ConfigMap with your CA certificate**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-ca-cert
data:
  my-custom-ca.crt: |
    -----BEGIN CERTIFICATE-----
    [YOUR_CA_CERTIFICATE_CONTENT]
    -----END CERTIFICATE-----
```

**2. Add to the values.yaml of Camunda Helm chart (example: Operate)**

```
operate:
  initContainers:
    - name: install-custom-ca
      image: camunda:camunda:8.7.3
      command: ["/bin/sh", "-c"]
      args:
        - |
          cp /custom-ca/my-custom-ca.crt /usr/local/share/ca-certificates/my-custom-ca.crt && \
          update-ca-certificates && \
          cp -r /etc/ssl/certs /ssl-certs/
      volumeMounts:
        - name: ca-cert
          mountPath: /custom-ca
        - name: ssl-certs
          mountPath: /ssl-certs
      securityContext:
        runAsUser: 0 # must run as root
  extraVolumes:
    - name: ca-cert
      configMap:
        name: custom-ca-cert
    - name: ssl-certs
      emptyDir: {}
  extraVolumeMounts:
    - name: ssl-certs
      mountPath: /etc/ssl/certs
```

_Note: Make sure the main container uses /etc/ssl/certs from the shared volume if you're overriding it._

Reminder: Init containers and volume configurations can be defined per component in the Helm chart using:
* tasklist.initContainers
* tasklist.extraVolumes
* tasklist.extraVolumeMounts
* (and similarly for operate, optimize, etc.)

### Tasks
