### ISSUE TITLE
[ENHANCEMENT] Put a condition around SPRING_DATASOURCE_PASSWORD env var in web-modeler restapi template

### ISSUE THREAD

**Issue by hisImminence** [camunda/camunda-platform-helm#3510]
**Describe the use case:**

A Customer is using Camunda 8.6 with Helm chart 11.x.x and Camunda 8.7 with Helm chart 12.x.x. In their setup, they are using AWS IAM Role Based Authentication (RBAC) to connect to their external PostgreSQL database.

They do not set a database password, nor do they use `existingSecret` or `existingSecretPasswordKey` in the `webModeler.restapi.externalDatabase` configuration.

Currently, the Helm chart _always_ renders the `SPRING_DATASOURCE_PASSWORD` environment variable in the Web Modeler REST API deployment manifest (e.g. [8.7 - deployment-restapi.yaml#44](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform-8.7/templates/web-modeler/deployment-restapi.yaml#L44)), even when no password or secret is provided. This leads to installation issues, as the Helm deployment expects a secret that does not exist.

**Describe the enhancement/feature:**

Conditionally render the SPRING_DATASOURCE_PASSWORD environment variable in the deployment template:

Proposed logic:

```yaml
# This condition is suggested by customer
{{- if or .Values.webModeler.restapi.externalDatabase.password .Values.webModeler.restapi.externalDatabase.existingSecret }}
- name: SPRING_DATASOURCE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ include "webModeler.restapi.databaseSecretName" . }}
      key: {{ include "webModeler.restapi.databaseSecretKey" . }}
{{- end }}
```

This conditional check would allow it to fully omit the SPRING_DATASOURCE_PASSWORD variable when it's not required, enabling password-less database connectivity via IAM authentication.

**Desired outcome and acceptance tests:**

- When neither password nor existingSecret is defined for `webModeler.restapi.externalDatabase`, the Helm chart should not include SPRING_DATASOURCE_PASSWORD in the Web Modeler REST API deployment manifest.
- When either password or existingSecret is defined, the `SPRING_DATASOURCE_PASSWORD` should be rendered correctly as it is today.
- This should not break support for embedded Postgres, which relies on the password environment variable.

**Note:** While the suggestion makes sense, implementing this change is not entirely straightforward (see [internal comment](https://camunda.slack.com/archives/C05H6R2DXUY/p1747400627377499?thread_ts=1747382439.737829&cid=C05H6R2DXUY)). The current template assumes that a password will always be present, especially due to embedded Postgres support. Its should taken care that we dont add a regressions in existing default behavior - while making this configurable for external DB setups.

**Related:**

- [SUPPORT-27288](https://jira.camunda.com/browse/SUPPORT-27288)
- https://github.com/camunda/camunda-platform-helm/issues/3408
