### ISSUE TITLE
Camunda INSTALLATION FAILED

### ISSUE THREAD

**Issue by RViththakan** [camunda/camunda-platform-helm#352]
Hi,

I'm a beginner in Camunda. When installing the camunda I got this error. Can anyone help on this?

```
helm install --name camunda ./camunda-platform/
helm3 install --name camunda ./camunda-platform/
```

These are the installation commands used and below is the corresponding error.

`Error: INTALLATION FAILED: template: camunda-platform/charts/optimize/templates/deployement.yaml:47:22: executing "camunda-platform/charts/optimize/templates/deployment.yaml" at <include "camundaPlatfrom.issuerBackendUrl" .>: error calling include: template: camunda-platform/templates/_helpers.tpl:63:10: executing "camundaPlatform.issuerBackendUrl" at <include "common.names.dependency.fullname"> (dict "chartName" "keycloak" "chartValues" . "context" $)>: error calling include template no template "common.names.dependency.fullname" associated with template "gotpl"`

**Comment by RViththakan** [comment]
I was keeping the auth enabled and able to successfully deploy the camunda.
```
global:
  identity:
    keycloak:
      fullname: ""

    auth:
    enabled: true
```
When I get the pods
`kubectl get pods`
some of them were running and some of them run earlier and later show a crashed loop back error. and Elasticsearch, zeebe and postgresql are always on persistence volume claim error. 
Is that because of auth enabled true?

I set the pv cand pvc like for the other service tools like kafka, elk and it also worked with camunda 7 and not with camunda 8. What could be an issue?

**Comment by npepinpe** [comment]
Authentication should have no impact on PVCs, so I don't think so.

Can you share the Zeebe/Elastic/Postgresql persistence related config?

**Comment by RViththakan** [comment]
I have described the pods 
For the pods having persistent volume claim issues, the error message was
`0/9 nodes are available : 9 pod has unbound immediate PersistentVolumeClaims` and under reasons it is as `FailedSheduling`
For the pods having the CrashLoopBackOff error, the error message was
`Back-off restarting failed container` and under reasons it is as `BackOff`

zeebe config

```
configMap:
  defaultMode: 0744
command: [ ]

resources:
   requests:
       cpu: 100m
       memory: 1000Mi
   limits:
       cpu: 960m
       memory: 1000Mi
persistenceType: disk
pvcSize: "10Gi"
pvcAccessModes: ["ReadWriteOnce"]
pvcStorageClassName: 'storage-sample'
```

ElasticSearch

```
elasticsearch:
   enabled: true
   extraEnvs:
      - name: "sec enable"
        value: "false"
   replicas: 2
   volumeClaimTemplate:
       accessModes: ["ReadWriteOnce"]
       storageClassName: storage-sample
        resources:
            requests:
                 storage: 10Gi
```

I couldn't able to find the postgres within the `values.yaml`. I couldn't able to `grep `the word postgres also in the whole directory. But postgres was deployed when the camunda installation was done. This is all I could find. Can you help me with this?
