### ISSUE TITLE
[ISSUE] when defining `global.identity.auth.<component>.existingSecret` a secret is not created for 8.8

### ISSUE THREAD

**Issue by hamza-m-masood** [camunda/camunda-platform-helm#3567]
**Describe the issue:**

For example, when defining a string literal for `global.identity.auth.console.existingSecret`, I expect a secret with the name `camunda-console-identity-secret` to be created. That is not the case. No secret is created. 

This applies for all components, including the core, which gives a `CreateContainerConfigError`:
```
Error: secret "camunda-core-identity-secret" not found
```
**Actual behavior:**

**Expected behavior:**

**How to reproduce:**

```
global:
  identity:
    auth:
      core:
        clientId: test
        audience: test
        existingSecret: test
        redirectUrl: test
      identity:
        clientId: test
        audience: test
        existingSecret: test
        redirectUrl: test
        initialClaimValue: test
```
**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:
