### ISSUE TITLE
[TASK] Document access level required for chart install, rollback, and upgrade

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#3590]
## Related to

- Epic: 8.9
- Support: [SUPPORT-27129](https://jira.camunda.com/browse/SUPPORT-27129)

## Overview

For tight security requirements, some users need a Role/ClusterRole for the resources required to access by the user to install, rollback, and upgrade the chart.

The Camunda chart doesn't change that much in the resources, as we use the Kubernetes core primitives, so I created the Role/ClusterRole manually.

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helm-release-manager
  namespace: <YOUR_NAMESPACE> # Replace with the appropriate namespace
rules:
  - apiGroups: [""] # Core API group
    resources:
      - configmaps
      - secrets
      - services
      - serviceaccounts
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"] # For Deployments and StatefulSets
    resources:
      - deployments
      - statefulsets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"] # For Ingress
    resources:
      - ingresses
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["policy"] # For PodDisruptionBudgets
    resources:
      - poddisruptionbudgets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["monitoring.coreos.com"] # For ServiceMonitors (used by Prometheus Operator)
    resources:
      - servicemonitors
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```

Later, in my free time, I created a CLI tool to extract that I called [kube-rbac-extractor](https://github.com/DevOpsHiveHQ/kube-rbac-extractor).

## Actions

- Automate generating the Role/ClusterRole for each version.
- Document the Role/ClusterRole in our [official docs](https://docs.camunda.io/).

### Sub-tasks

- [ ] TBA
