### ISSUE TITLE
[ISSUE] Documentstore AWS region not mapped

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda-platform-helm#3622]
**Describe the issue:**

The value `global.documentStore.type.aws.region` is not mapped to any configuration to take effect

**Actual behavior:**

When setting the AWS region, it does not work

**Expected behavior:**

The region is applied in the way it is configured in other distros as well (as env `AWS_REGION`)

**How to reproduce:**

1. Set `global.documentStore.type.aws.region` and enable the aws document store
2. Pods using the document store will not come up, reporting no region was defined

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: any
- Helm CLI version: any
- Chart version: camunda-platform-12.0.2
- Values file: 

```yaml
global:
  documentStore:
    activeStoreId: aws
    type:
      aws:
        enabled: true
        bucket: idp-docs
        existingSecret: minio
        accessKeyIdKey: root-user
        secretAccessKeyKey: root-password
        region: us-east-1
```
