### ISSUE TITLE
[ENHANCEMENT] add functionality for custom role bindings for a specific user in 8.8 basic auth

### ISSUE THREAD

**Issue by hamza-m-masood** [camunda/camunda-platform-helm#3633]
**Describe the use case:**

Currently in 8.8, while using basic auth, all users are assigned the admin role.
It is already possible to assign custom roles to users in the `core` configmap like so:
```yaml
camunda:
  security:
    initialization:
        default-roles.connectors.users:
          - "lisa"
        default-roles.rpa.users:
          - "demo"
```

This functionality is not supported in the values.yaml. 
When defining a user, it would be better to also define the custom roles of that user as well.

**Describe the enhancement/feature:**

The challenge here is to find a good non-breaking syntax that would work in the values.yaml and would then get translated to the `core` configmap syntax above.

**Desired outcome and acceptance tests:**
