### ISSUE TITLE
Unable to pass env vars to Keycloak from Camunda Helm

### ISSUE THREAD

**Issue by conadrisca** [camunda/camunda-platform-helm#364]
Admittedly not an expert with helm, but I'm finding I am unable to pass env variables to the keycloak dependency when configuring it in main Values.yaml . 

Here is values-dev.yaml where I am attempting to set an env variable using configuration guidance described in the keycloak helm chart repo (https://github.com/bitnami/charts/tree/master/bitnami/keycloak/#keycloak-parameters): 

```
identity:  
  keycloak:
    extraEnvVars:
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
```

Deploying to my AKS cluster using:
`
helm install camunda camunda/camunda-platform -f values-dev.yaml
`

Once deployed, we can see the environment var not set:
![Screen Shot 2022-07-29 at 5 34 40 PM](https://user-images.githubusercontent.com/7191642/181846118-a78ff7ef-eefa-48e6-8a6d-d12073039b48.png)

Please let me know if I am going about this entirely wrong or if this is a bug.
