### ISSUE TITLE
[TASK] Investigate chart-verifier tool benefits

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda-platform-helm#366]
**Description**

RedHat provides an open source tool called [chart-verifier](https://github.com/redhat-certification/chart-verifier) which lets you run some predefined and custom checks against your chart.

As a first step, we can look into the existing checks to see if any of them are useful for us, integrate it into our workflow (you can use the [openshift-tools-installer](https://github.com/redhat-actions/openshift-tools-installer) action in CI to install this tool), and then we could think about custom checks.

This is a suggestion, as we don't have yet an ad-hoc place to talk about the charts as a product.
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2034
```

**Comment by hamza-m-masood** [comment]
I ran the tool on our latest chart and this is the output that I got:
```yaml
apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.4
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:13503106373664558913
        chart-uri: /charts/
        digests:
            chart: sha256:7dce5d259b555215d4e12f7e2b8776c37b8bc9dc7f06930a067a48e626b72a17
        lastCertifiedTimestamp: "2024-06-20T22:05:47.756963+00:00"
        testedOpenShiftVersion: N/A
        supportedOpenShiftVersions: N/A
        webCatalogOnly: false
    chart:
        name: camunda-platform
        home: https://docs.camunda.io/docs/self-managed/overview/
        sources:
            - https://github.com/camunda/camunda-platform-helm
        version: 10.1.1
        description: 'Camunda 8 Self-Managed Helm charts. Camunda''s process automation platform allows developers to design, automate and improve processes. '
        keywords:
            - bpm
            - bpmn
            - camunda-platform
            - dmn
            - process-engine
            - workflow
        maintainers:
            - name: Zelldon
              email: christopher.zell@camunda.com
              url: ""
            - name: aabouzaid
              email: ahmed.abouzaid@camunda.com
              url: ""
        icon: https://helm.camunda.io/imgs/camunda.svg
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 8.5.x
        deprecated: false
        annotations:
            artifacthub.io/changes: |
                - kind: added
                  description: "add console auth vars"
            artifacthub.io/containsSecurityUpdates: "false"
            artifacthub.io/links: |
                - name: Camunda 8 docs
                  url: https://docs.camunda.io/
                - name: Camunda 8 Self-Managed docs
                  url: https://docs.camunda.io/docs/self-managed/about-self-managed/
                - name: Camunda 8 Self-Managed Helm charts
                  url: https://github.com/camunda/camunda-platform-helm
            camunda.io/helmCLIVersion: 3.15.1
            dummy: dummy
        kubeversion: ""
        dependencies:
            - name: keycloak
              version: 19.4.1
              repository: https://charts.bitnami.com/bitnami
              condition: identity.keycloak.enabled,identityKeycloak.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: identityKeycloak
            - name: postgresql
              version: 12.x.x
              repository: https://charts.bitnami.com/bitnami
              condition: identity.postgresql.enabled,identityPostgresql.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: identityPostgresql
            - name: web-modeler-postgresql
              version: 11.x.x
              repository: file://../web-modeler-postgresql
              condition: postgresql.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: postgresql
            - name: elasticsearch
              version: 20.0.4
              repository: oci://registry-1.docker.io/bitnamicharts
              condition: elasticsearch.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: common
              version: 2.x.x
              repository: https://charts.bitnami.com/bitnami
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: ""
        type: application
    chart-overrides: ""
results:
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: FAIL
      reason: |
        Helm lint has failed:  [ERROR] templates/: template: camunda-platform/templates/zeebe-gateway/deployment.yaml:23:28: executing "camunda-platform/templates/zeebe-gateway/deployment.yaml" at <include (print $.Template.BasePath "/zeebe-gateway/configmap.yaml") .>: error calling include: template: camunda-platform/templates/zeebe-gateway/configmap.yaml:44:29: executing "camunda-platform/templates/zeebe-gateway/configmap.yaml" at <include "camundaPlatform.authIssuerBackendUrl" .>: error calling include: template: camunda-platform/templates/camunda/_helpers.tpl:195:10: executing "camundaPlatform.authIssuerBackendUrl" at <include "identity.keycloak.url" .>: error calling include: template: camunda-platform/templates/identity/_helpers.tpl:193:9: executing "identity.keycloak.url" at <include "identity.keycloak.host" .>: error calling include: template: camunda-platform/templates/identity/_helpers.tpl:161:12: executing "identity.keycloak.host" at <include "identity.keycloak.hostDefault" .>: error calling include: template: camunda-platform/templates/identity/_helpers.tpl:128:17: executing "identity.keycloak.hostDefault" at <{{template "common.names.fullname" .Subcharts.identityKeycloak}}>: template "common.names.fullname" not defined
        [WARNING] /root/.cache/helm/repository/chart-verifier/_charts_/camunda-platform: chart directory is missing these dependencies: keycloak,postgresql,web-modeler-postgresql,elasticsearch,common
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: FAIL
      reason: 'Missing required annotations: [charts.openshift.io/name]'
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: FAIL
      reason: Kubernetes version is not specified
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: FAIL
      reason: Values schema file does not exist
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: No images to certify
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: FAIL
      reason: 'invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable'
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt


```
