### ISSUE TITLE
[ISSUE] value is not rendred correctly for `global.identity.auth.identity.existingSecret.name` on 8.8

### ISSUE THREAD

**Issue by hamza-m-masood** [camunda/camunda-platform-helm#3695]
**Describe the issue:**

This applies to OIDC.
When entering a value for `global.identity.auth.identity.existingSecret.name`, the wrong value is rendered in the config map.

**Actual behavior:**

With this values.yaml:
```
global:
  identity:
    auth:
      identity:
        existingSecret:
          name: oidc
        existingSecretKey: token
```
The configmap value renders like this:
```
camunda:
      identity:
        client-secret: "map[name:oidc]"
```
as you can see the client-secret does not reference an env var with the secret value or the secret value itself but instead, it treats `global.identity.auth.identity.existingSecret` as just an input for a string literal. 
**Expected behavior:**

expected 
**How to reproduce:**

When entere
**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:
