### ISSUE TITLE
[ISSUE] Configuration through application.yml for operate / migrate not working

### ISSUE THREAD

**Issue by tpjg** [camunda/camunda-platform-helm#3706]
The `migration` part of operate, and probably also `operate` cannot connect to ElasticSearch.

**Actual behavior:**

Migrate tries to connect to http://localhost:9200

**Expected behavior:**

Migrate should connect to http://camunda-elasticsearch:9200 (to be more generic to the defined elasticsearch URL either through global.elasticsearch.url or the global.elasticsearch.host/port/protocol).

**How to reproduce:**

Updating from earlier versions of this Chart. When I upgraded from 10.7.1 to 11.4.0 (and I also tried 11.5.0) operate would no longer correctly start.

**Logs:**

```2025-06-25 13:48:30.745  WARN 1 --- [           main] i.c.o.u.RetryOperation                   : Retry Operation Connect to Elasticsearch cluster [elasticsearch] at http://localhost:9200 failed: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused```

**Environment:**

- Platform: AWS
- Chart version: 11.4.0

**Guesswork:**

My guess is that /usr/local/operate/bin/migrate (and possibly operate as well) tries to read /usr/local/operate/config/application.yml but the Chart, possibly in templates/operate/configmap.yaml defines application.**yaml** instead. See the output of `kubectl describe` below.

Entering a shell in the relevant pod shows both application.yml and application.yaml existing and application.yml having the default values pointing to localhost.

```
  migration:
    Container ID:    containerd://52ee1b938df2fcf3d5077f91fb77f124412e5f76c9a85956141b49ffe8e5738e
    Image:           camunda/operate:8.2.12
    Image ID:        docker.io/camunda/operate@sha256:9657ca21523aa89204daca159d6e7ad6f2cb230bd7f0785469b1b31c3d36e8d5
    Port:            <none>
    Host Port:       <none>
    SeccompProfile:  RuntimeDefault
    Command:
      /bin/sh
      /usr/local/operate/bin/migrate
    State:          Running
      Started:      Wed, 25 Jun 2025 15:50:55 +0200
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Wed, 25 Jun 2025 15:48:21 +0200
      Finished:     Wed, 25 Jun 2025 15:50:55 +0200
    Ready:          False
    Restart Count:  1
    Limits:
      cpu:     2
      memory:  2Gi
    Requests:
      cpu:        600m
      memory:     1Gi
    Environment:  <none>
    Mounts:
      /camunda from camunda (rw)
      /tmp from tmp (rw)
      /usr/local/operate/config/application.yaml from config (rw,path="application.yaml")
```

Part of application.yaml:
```
# Operate configuration file
camunda.operate:

  # ELS instance to store Operate data
  elasticsearch:
    # Cluster name
    clusterName: elasticsearch
    # Host
    host: camunda-elasticsearch
    # Transport port
    port: 9200
    # Elasticsearch full url
    url: "http://camunda-elasticsearch:9200"
```

Part of application.yml:
```
camunda.operate:
  # Set operate username and password.
  # If user with <username> does not exists it will be created.
  # Default: demo/demo
  #username:
  #password:
  # ELS instance to store Operate data
  elasticsearch:
    # Cluster name
    clusterName: elasticsearch
    # URL
    url: http://localhost:9200
```
