### ISSUE TITLE
[TASK] Support existing Elasticsearch

### ISSUE THREAD

**Issue by vctrmn** [camunda/camunda-platform-helm#473]
**Describe the use case:**

I would like to connect Camunda Platform (Zeebe, Operate, Tasklist and Optmize) to an external managed Elasticsearch.

**Describe the enhancement/feature:**

Here is the `values.yaml` file to achieve this : (tested with an Elasticsearch provided on https://cloud.elastic.co/) 
```bash
global:
  elasticsearch:
    url: "https://camunda-platform-elasticsearch.com"
    host: camunda-platform-elasticsearch.com
    port: 443

zeebe:
  # ClusterSize defines the amount of brokers (=replicas), which are deployed via helm
  clusterSize: "1"
  # PartitionCount defines how many zeebe partitions are set up in the cluster
  partitionCount: "1"
  # ReplicationFactor defines how each partition is replicated, the value defines the number of nodes
  replicationFactor: "1"

  resources:
    requests:
      cpu: 800m
      memory: 1200Mi
    limits:
      cpu: 800m
      memory: 1200Mi

  # PvcSize defines the persistent volume claim size, which is used by each broker pod https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
  pvcSize: "16Gi"

  env:
    - name: ZEEBE_BROKER_DATA_SNAPSHOTPERIOD
      value: "5m"
    - name: ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK
      value: "0.85"
    - name: ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK
      value: "0.87"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_USERNAME
      value: "elastic"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_PASSWORD
      value: "mysecretpassword"

zeebe-gateway:
  # Replicas defines how many standalone gateways are deployed
  replicas: 1

operate:
  resources:
    requests:
      cpu: 600m
      memory: 400Mi
    limits:
      cpu: 600m
      memory: 400Mi

  env:
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_URL
      value: "https://camunda-platform-elasticsearch.com"
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_USERNAME
      value: "elastic"
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_PASSWORD
      value: "mysecretpassword"
    - name: CAMUNDA_OPERATE_ZEEBE_ELASTICSEARCH_URL
      value: "https://camunda-platform-elasticsearch.com"
    - name: CAMUNDA_OPERATE_ZEEBE_ELASTICSEARCH_USERNAME
      value: "elastic"
    - name: CAMUNDA_OPERATE_ZEEBE_ELASTICSEARCH_PASSWORD
      value: "mysecretpassword"

tasklist:
  resources:
    requests:
      cpu: 400m
      memory: 1Gi
    limits:
      cpu: 400m
      memory: 1Gi

  env:
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_URL
      value: "https://camunda-platform-elasticsearch.com"
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_USERNAME
      value: "elastic"
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_PASSWORD
      value: "mysecretpassword"
    - name: CAMUNDA_TASKLIST_ZEEBE_ELASTICSEARCH_URL
      value: "https://camunda-platform-elasticsearch.com"
    - name: CAMUNDA_TASKLIST_ZEEBE_ELASTICSEARCH_USERNAME
      value: "elastic"
    - name: CAMUNDA_TASKLIST_ZEEBE_ELASTICSEARCH_PASSWORD
      value: "mysecretpassword"

optimize:
  # PartitionCount defines how many Zeebe partitions are set up in the cluster and which should be imported by Optimize
  partitionCount: "1"

  image:
    # Image.repository defines which image repository to use
    repository: camunda/optimize
    # Image.tag can be set to overwrite the global tag, which should be used in that chart
    # Don't change the comment after the value, it's needed due to a bug yq. Check Makefile for more details.
    tag: 3.9.2 # optimize.image.tag

  env:
    - name: CAMUNDA_OPTIMIZE_ELASTICSEARCH_SSL_ENABLED
      value: "true"
    - name: CAMUNDA_OPTIMIZE_ELASTICSEARCH_SECURITY_USERNAME
      value: "elastic"
    - name: CAMUNDA_OPTIMIZE_ELASTICSEARCH_SECURITY_PASSWORD
      value: "mysecretpassword"

  resources:
    requests:
      cpu: 600m
      memory: 1Gi
    limits:
      cpu: 600m
      memory: 1Gi

identity:
  resources:
    requests:
      cpu: 600m
      memory: 400Mi
    limits:
      cpu: 600m
      memory: 400Mi

elasticsearch:
  enabled: false
```

**Comment by mhuijgen** [comment]
It would be very nice if we could also configure CA certificate or truststore for use cases where elasticsearch is running with security local in same cluster.  Or set some config to not validate certificates in this use case.

Using above example, zeebe tries to connect but fails certificate validation because the elasticsearch in the cluster is running with self signed certificates.
Zeebe log:
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target


Same goes for the other services operate/optimize/tasklist. Tested with operate, it connects to elastic, but fails on certificate validation:
2022-11-07 14:08:59.252  WARN 7 --- [           main] i.c.o.u.RetryOperation                   : java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by vctrmn** [comment]
Hello @mhuijgen  ! 

I have prepared a values.yaml example for this, but it still a work in progress.
Do you want me to share it ?

**Comment by vctrmn** [comment]
1. You should first create a keystore from your certificate :
`keytool -import -alias elasticsearch  -keystore elasticsearch.jks -file elasticsearch.cer -storepass changeit -noprompt`

2. Then create a secret from this certificate :
`kubectl create secret generic elasticsearch-jks --from-file=elasticsearch.jks`

3. Mount the secret in each pod (See example below) :
```bash
global:
  # Image configuration to be used in each sub chart
  image:
    # Image.tag defines the tag / version which should be used in the chart
    tag: 8.1.2

  elasticsearch:
    url: "https://camunda-platform-elasticsearch.com"
    host: camunda-platform-elasticsearch.com
    port: 443

zeebe:
  # ClusterSize defines the amount of brokers (=replicas), which are deployed via helm
  clusterSize: "1"
  # PartitionCount defines how many zeebe partitions are set up in the cluster
  partitionCount: "1"
  # ReplicationFactor defines how each partition is replicated, the value defines the number of nodes
  replicationFactor: "1"

  resources:
    requests:
      cpu: 800m
      memory: 1200Mi
    limits:
      cpu: 800m
      memory: 1200Mi

  # PvcSize defines the persistent volume claim size, which is used by each broker pod https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
  pvcSize: "16Gi"

  env:
    - name: ZEEBE_BROKER_DATA_SNAPSHOTPERIOD
      value: "5m"
    - name: ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK
      value: "0.85"
    - name: ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK
      value: "0.87"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_USERNAME
      value: "elastic"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_PASSWORD
      value: "mysecretpassword"

  javaOpts: >-
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/usr/local/zeebe/data
    -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
    -XX:+ExitOnOutOfMemoryError
    -Djavax.net.ssl.trustStore=/usr/local/zeebe/certificates/elasticsearch.jks

  extraVolumeMounts:
    - name: keystore
      mountPath: /usr/local/zeebe/certificates/elasticsearch.jks
      subPath: elasticsearch.jks
  extraVolumes:
    - name: keystore
      secret:
        secretName: elasticsearch-jks
        optional: false

zeebe-gateway:
  # Replicas defines how many standalone gateways are deployed
  replicas: 1

operate:
  resources:
    requests:
      cpu: 600m
      memory: 400Mi
    limits:
      cpu: 600m
      memory: 400Mi

  env:
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_URL
      value: "https://camunda-platform-elasticsearch.com"
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_USERNAME
      value: "elastic"
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_PASSWORD
      value: "mysecretpassword"
    - name: CAMUNDA_OPERATE_ZEEBE_ELASTICSEARCH_URL
      value: "https://camunda-platform-elasticsearch.com"
    - name: CAMUNDA_OPERATE_ZEEBE_ELASTICSEARCH_USERNAME
      value: "elastic"
    - name: CAMUNDA_OPERATE_ZEEBE_ELASTICSEARCH_PASSWORD
      value: "mysecretpassword"
    - name: JAVA_TOOL_OPTIONS
      value: "-Djavax.net.ssl.trustStore=/usr/local/operate/certificates/elasticsearch.jks"

  extraVolumeMounts:
    - name: keystore
      mountPath: /usr/local/operate/certificates/elasticsearch.jks
      subPath: elasticsearch.jks
  extraVolumes:
    - name: keystore
      secret:
        secretName: elasticsearch-jks
        optional: false

tasklist:
  resources:
    requests:
      cpu: 400m
      memory: 1Gi
    limits:
      cpu: 400m
      memory: 1Gi

  env:
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_URL
      value: "https://camunda-platform-elasticsearch.com"
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_USERNAME
      value: "elastic"
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_PASSWORD
      value: "mysecretpassword"
    - name: CAMUNDA_TASKLIST_ZEEBE_ELASTICSEARCH_URL
      value: "https://camunda-platform-elasticsearch.com"
    - name: CAMUNDA_TASKLIST_ZEEBE_ELASTICSEARCH_USERNAME
      value: "elastic"
    - name: CAMUNDA_TASKLIST_ZEEBE_ELASTICSEARCH_PASSWORD
      value: "mysecretpassword"
    - name: JAVA_TOOL_OPTIONS
      value: "-Djavax.net.ssl.trustStore=/app/certificates/elasticsearch.jks"

  extraVolumeMounts:
    - name: keystore
      mountPath: /app/certificates/elasticsearch.jks
      subPath: elasticsearch.jks
  extraVolumes:
    - name: keystore
      secret:
        secretName: elasticsearch-jks
        optional: false

  ingress:
    enabled: true
    className: nginx
    annotations:
      ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt
    host: "tasklist.cwa.wap.ibminteractive.fr"
    tls:
      # Ingress.tls.enabled if true, then tls is configured on the ingress resource. If enabled the Ingress.host need to be defined.
      enabled: true
      # Ingress.tls.secretName defines the secret name which contains the TLS private key and certificate
      secretName: tasklist.cwa.wap.ibminteractive.fr

optimize:
  # PartitionCount defines how many Zeebe partitions are set up in the cluster and which should be imported by Optimize
  partitionCount: "1"

  image:
    # Image.repository defines which image repository to use
    repository: camunda/optimize
    # Image.tag can be set to overwrite the global tag, which should be used in that chart
    # Don't change the comment after the value, it's needed due to a bug yq. Check Makefile for more details.
    tag: 3.9.2 # optimize.image.tag

  env:
    - name: CAMUNDA_OPTIMIZE_ELASTICSEARCH_SSL_ENABLED
      value: "true"
    - name: CAMUNDA_OPTIMIZE_ELASTICSEARCH_SECURITY_USERNAME
      value: "elastic"
    - name: CAMUNDA_OPTIMIZE_ELASTICSEARCH_SECURITY_PASSWORD
      value: "mysecretpassword"
    - name: JAVA_TOOL_OPTIONS
      value: "-Djavax.net.ssl.trustStore=/optimize/certificates/elasticsearch.jks"

  resources:
    requests:
      cpu: 600m
      memory: 1Gi
    limits:
      cpu: 600m
      memory: 1Gi

  extraVolumeMounts:
    - name: keystore
      mountPath: /optimize/certificates/elasticsearch.jks
      subPath: elasticsearch.jks
  extraVolumes:
    - name: keystore
      secret:
        secretName: elasticsearch-jks
        optional: false

identity:
  resources:
    requests:
      cpu: 600m
      memory: 400Mi
    limits:
      cpu: 600m
      memory: 400Mi

elasticsearch:
  enabled: false
```

⚠️  It is still a Work In Progress ⚠️

**Comment by vctrmn** [comment]
To debug, you can add `-Djavax.net.debug=all` in your `JAVA_TOOL_OPTIONS`

```bash
    - name: JAVA_TOOL_OPTIONS
      value: "-Djavax.net.debug=all -Djavax.net.ssl.trustStore=/usr/local/operate/certificates/elasticsearch.jks"
```

**Comment by mhuijgen** [comment]
Tested this work in progress values file after creating the secret based on the ca.crt exported from the secret created by the bitnami/elasticsearch chart and it works right away. That is, it can connect now just fine and operate starts to create some indexes. However it seems that camunda/operate:8.1.2does not yet support ES 8.x ?

https://forum.camunda.io/t/operate-8-0-1-not-supporting-elasticsearch-8-1-3/37298


2022-11-07 18:45:05.229 DEBUG 7 --- [           main] i.c.o.s.ElasticsearchSchemaManager       : Template [operate-incident-1.3.0_template] was successfully created
2022-11-07 18:45:05.234  WARN 7 --- [           main] o.e.c.RestClient                         : request [HEAD https://elastic-elasticsearch:9200/operate-incident-1.3.0_?ignore_throttled=false&ignore_unavailable=true&expand_wildcards=open&allow_no_indices=false] returned 1 warnings: [299 Elasticsearch-8.5.0-c94b4700cda13820dad5aa74fae6db185ca5c304 "[ignore_throttled] parameter is deprecated because frozen indices have been deprecated. Consider cold or frozen tiers in place of frozen indices."]
2022-11-07 18:45:05.531 DEBUG 7 --- [           main] i.c.o.s.ElasticsearchSchemaManager       : Index [operate-incident-1.3.0_] was successfully created
2022-11-07 18:45:05.539  WARN 7 --- [           main] o.e.c.RestClient                         : request [HEAD https://elastic-elasticsearch:9200/operate-web-session-1.1.0_?ignore_throttled=false&ignore_unavailable=true&expand_wildcards=open&allow_no_indices=false] returned 1 warnings: [299 Elasticsearch-8.5.0-c94b4700cda13820dad5aa74fae6db185ca5c304 "[ignore_throttled] parameter is deprecated because frozen indices have been deprecated. Consider cold or frozen tiers in place of frozen indices."]
2022-11-07 18:45:05.635  WARN 7 --- [           main] i.c.o.u.RetryOperation                   : Elasticsearch exception [type=illegal_argument_exception, reason=Unknown token [VALUE_NULL] in alias [operate-web-session-1.1.0_alias]]

**Comment by vctrmn** [comment]
@mhuijgen Zeebe support only version 7.x.x

**Comment by mhuijgen** [comment]
Looks like the latest bitnam/elasticsearch chart 19.0.5 still configures elasticsearch 7.17.7 correctly if I override the image tag. Redeployed camunda using based on @vctrmn 's values.yaml and operate now created all indexes succesfully using a secured elasticsearch with self signed certificates.

**Comment by menski** [comment]
Notes from discussions, we can split this down into multiple topics:
- ease the configuration to configure in a central place an external elasticsearch
- support self-signed certificate for elasticsearch or other external systems

@aabouzaid we could break this down into the two issues, and already prioritize the first topic, for the second one we have to discuss when and how we want to implement https://github.com/camunda/product-hub/issues/583

**Comment by hoangduy1912** [comment]
> Tested this work in progress values file after creating the secret based on the ca.crt exported from the secret created by the bitnami/elasticsearch chart and it works right away. That is, it can connect now just fine and operate starts to create some indexes. However it seems that camunda/operate:8.1.2does not yet support ES 8.x ?
> 
> https://forum.camunda.io/t/operate-8-0-1-not-supporting-elasticsearch-8-1-3/37298
> 
> 2022-11-07 18:45:05.229 DEBUG 7 --- [ main] i.c.o.s.ElasticsearchSchemaManager : Template [operate-incident-1.3.0_template] was successfully created 2022-11-07 18:45:05.234 WARN 7 --- [ main] o.e.c.RestClient : request [HEAD https://elastic-elasticsearch:9200/operate-incident-1.3.0_?ignore_throttled=false&ignore_unavailable=true&expand_wildcards=open&allow_no_indices=false] returned 1 warnings: [299 Elasticsearch-8.5.0-c94b4700cda13820dad5aa74fae6db185ca5c304 "[ignore_throttled] parameter is deprecated because frozen indices have been deprecated. Consider cold or frozen tiers in place of frozen indices."] 2022-11-07 18:45:05.531 DEBUG 7 --- [ main] i.c.o.s.ElasticsearchSchemaManager : Index [operate-incident-1.3.0_] was successfully created 2022-11-07 18:45:05.539 WARN 7 --- [ main] o.e.c.RestClient : request [HEAD https://elastic-elasticsearch:9200/operate-web-session-1.1.0_?ignore_throttled=false&ignore_unavailable=true&expand_wildcards=open&allow_no_indices=false] returned 1 warnings: [299 Elasticsearch-8.5.0-c94b4700cda13820dad5aa74fae6db185ca5c304 "[ignore_throttled] parameter is deprecated because frozen indices have been deprecated. Consider cold or frozen tiers in place of frozen indices."] 2022-11-07 18:45:05.635 WARN 7 --- [ main] i.c.o.u.RetryOperation : Elasticsearch exception [type=illegal_argument_exception, reason=Unknown token [VALUE_NULL] in alias [operate-web-session-1.1.0_alias]]

Hi @mhuijgen 

Can you please quickly document what you did with bitnami elasticsearch? What is your value file?

**Comment by mhuijgen** [comment]
@hoangduy1912  you are correct that Camunda does not support ES 8.x.
What I did is use the bitnami/elasticsearch chart version 19.5.0, which by default uses 8.x, but I overrode the image tag to use latest 7.17.x at the time. The values I used for this chart:

```
global:
  kibanaEnabled: true
image:
  tag: 7.17.7-debian-11-r4
master:
  replicaCount: 1
  masterOnly: false
  heapSize: 1024m
  persistence:
    size: 40Gi
data:
  replicaCount: 0
coordinating:
  replicaCount: 0
ingest:
  replicaCount: 0
security:
  enabled: true
  tls:
    autoGenerated: true
kibana:
  image:
    tag: 7.17.7-debian-11-r4
  persistence:
    enabled: false
  elasticsearch:
    hosts:
      - elastic-elasticsearch
    port: 9200
    security:
      auth:
        enabled: true
        createSystemUser: true
        kibanaPassword: secretPass
        elasticsearchPasswordSecret: elastic-elasticsearch
      tls:
        enabled: true
        existingSecret: elastic-elasticsearch-master-crt
        usePemCerts: true
```

**Comment by hoangduy1912** [comment]
> ```shell
> elasticsearch-jks
> ```

Thanks @mhuijgen 

How about the secret? I followed these steps but the following error occured

```
2023-03-09 09:27:18.168  INFO 1 --- [           main] i.c.t.e.ElasticsearchConnector           : Retrying #7 connect to Elasticsearch at https://bitnami-es-elasticsearch:9200 due to ElasticsearchException[java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty]; nested: ExecutionException[javax.net.ssl.SSLException: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty]; nested: SSLException[java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty]; nested: InvalidAlgorithmParameterException[the trustAnchors parameter must be non-empty];
```

```
You should first create a keystore from your certificate :
keytool -import -alias elasticsearch  -keystore elasticsearch.jks -file elasticsearch.cer -storepass changeit -noprompt

Then create a secret from this certificate :
kubectl create secret generic elasticsearch-jks --from-file=elasticsearch.jks
```

**Comment by mhuijgen** [comment]
To create the secret with java keystore I used:

```
kubectl  get secret elastic-elasticsearch-master-crt -o jsonpath='{.data.ca\.crt}'|base64 -d >elastic-ca.crt
keytool -import -alias elasticsearch -keystore elasticsearch.jks -storetype jks -file elastic-ca.crt -storepass changeit -noprompt
kubectl  create secret generic elasticsearch-jks --from-file=elasticsearch.jks
```

Deployed using camunda helm chart version 8.1.0 using the following values (showing just the bits for zeebe and operate). Depending on the deployment name for your elasticsearch you might need to tweak some names a bit.

```
global:
  elasticsearch:
    url: "https://elastic-elasticsearch:9200"
    host: "elastic-elasticsearch"
    port: 9200

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  env:
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_USERNAME
      value: "elastic"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elastic-elasticsearch
          key: elasticsearch-password
  javaOpts: >-
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/usr/local/zeebe/data
    -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
    -XX:+ExitOnOutOfMemoryError
    -Djavax.net.ssl.trustStore=/usr/local/zeebe/certificates/elasticsearch.jks
  extraVolumeMounts:
    - name: keystore
      mountPath: /usr/local/zeebe/certificates/elasticsearch.jks
      subPath: elasticsearch.jks
  extraVolumes:
    - name: keystore
      secret:
        secretName: elasticsearch-jks
        optional: false

operate:
  enabled: true
  env:
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_URL
      value: "https://elastic-elasticsearch:9200"
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_USERNAME
      value: "elastic"
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elastic-elasticsearch
          key: elasticsearch-password
    - name: CAMUNDA_OPERATE_ZEEBE_ELASTICSEARCH_URL
      value: "https://elastic-elasticsearch:9200"
    - name: CAMUNDA_OPERATE_ZEEBE_ELASTICSEARCH_USERNAME
      value: "elastic"
    - name: CAMUNDA_OPERATE_ZEEBE_ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elastic-elasticsearch
          key: elasticsearch-password
    - name: JAVA_TOOL_OPTIONS
      value: "-Djavax.net.ssl.trustStore=/usr/local/operate/certificates/elasticsearch.jks"
  extraVolumeMounts:
    - name: keystore
      mountPath: /usr/local/operate/certificates/elasticsearch.jks
      subPath: elasticsearch.jks
  extraVolumes:
    - name: keystore
      secret:
        secretName: elasticsearch-jks
        optional: false

```


Also note that every time you helm upgrade bitnami/elasticsearch with values 
```
  tls:
    autoGenerated: true
```
It will generate a new elastic-ca certificate after which you will need to update the JKS secret and rollout restart the camunda services.
