### ISSUE TITLE
[BUG] Access to Camunda services are not secured, eventhough certificate is configured

### ISSUE THREAD

**Issue by hoangduy1912** [camunda/camunda-platform-helm#493]
Hi @aabouzaid. I included the steps to reproduce below. Hope you find it useful.

**Describe the bug:**

In reference to issue https://github.com/camunda/camunda-platform-helm/issues/479

**Actual behavior:**

1. Separated ingress works normally, connection is secured with certificate from AWS ACM
2. Combined ingress has issue

There're 2 problems:
1. Path based url is marked as "not secure" while subdomain works normally.
![image](https://user-images.githubusercontent.com/11615917/203501388-4b7bd8a3-ee96-44d0-a06f-486ecd7645a2.png)
![image](https://user-images.githubusercontent.com/11615917/203501416-03329a04-d9e5-4a7d-98ac-caff80a2e743.png)

2. Identity returns with the following error
![image](https://user-images.githubusercontent.com/11615917/203501503-5c513b14-8c37-447c-b420-13915249ba47.png)

I'm using certificate from AWS ACM.

**Expected behavior:**

Access to camunda services using path based routing (combined ingress) works normally with certificate

**How to reproduce:**

1. Request a certificate on AWS ACM  (*.example.com)
2. Install camunda via helm chart. Custom value below
3. Use route 53 to add an alias record to map domain name with AWS ALB.
4. Access the service via domain name. E.g. example.com/tasklist

**Environment:**
- Platform: AWS EKS
- Chart version: 8.1.1
- Values file: 
```
global:
  ingress:
    enabled: true
    tls:
      enabled: true
    className: alb
    host: "example.com"
    annotations:
      alb.ingress.kubernetes.io/load-balancer-name: "lb-name"
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/target-type: "instance"
      alb.ingress.kubernetes.io/tags: "Name=qa-camunda-qa-ingress,Stage=qa"
      external-dns.alpha.kubernetes.io/hostname: "example.com"
      alb.ingress.kubernetes.io/subnets: "subnet-id"
      alb.ingress.kubernetes.io/certificate-arn: "cert-arn"
  identity:
    auth:
      publicIssuerUrl: "https://example.com/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://example.com/operate"
      tasklist:
        redirectUrl: "https://example.com/tasklist"
      optimize:
        redirectUrl: "https://example.com/optimize"

operate:
  service:
    type: NodePort
  contextPath: "/operate"

identity:
  service:
    type: NodePort
  keycloak:
    service:
      type: NodePort
    extraEnvVars:
    - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_FRONTEND_URL
      value: "https://example.com/auth"
  env:
    - name: IDENTITY_URL
      value: "https://example.com/identity"
  contextPath: "/identity"
  fullURL: "https://example.com/identity"

tasklist:
  service:
    type: NodePort
  contextPath: "/tasklist"

optimize:
  service:
    type: NodePort
  contextPath: "/optimize"

zeebe-gateway:
  service:
    type: NodePort
```
