### ISSUE TITLE
[ISSUE] Upgrade to camunda 8.1.6 has issue with optimize

### ISSUE THREAD

**Issue by hoangduy1912** [camunda/camunda-platform-helm#524]
**Describe the issue:**

When I upgraded from 8.1.2 to 8.1.6, I cannot browse to optimize anymore. Logs from optimize are filled with:

**Logs:**

Caused by: org.camunda.optimize.service.exceptions.OptimizeRuntimeException: The Elasticsearch Optimize schema version [3.9.1] doesn't match the current Optimize version [3.9.3]. Please make sure to run the Upgrade first.

**Environment:**

- Platform: AWS
- Chart version: 8.1.6
- Values file:

```
operate:
  service:
    type: NodePort
identity:
  service:
    type: NodePort
  keycloak:
    service:
      type: NodePort
    extraEnvVars:
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_FRONTEND_URL
        value: "https://keycloak.example.com"
  env:
    - name: IDENTITY_URL
      value: "https://identity.example.com"
tasklist:
  service:
    type: NodePort
optimize:
  service:
    type: NodePort
zeebe-gateway:
  service:
    type: NodePort
global:
  identity:
    auth:
      publicIssuerUrl: "https://keycloak.example.com/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://operate.example.com"
      tasklist:
        redirectUrl: "https://tasklist.example.com"
      optimize:
        redirectUrl: "https://optimize.example.com"
```
