### ISSUE TITLE
[ENHANCEMENT] Select the destination namespace

### ISSUE THREAD

**Issue by paranoiasystem** [camunda/camunda-platform-helm#557]
**Describe the use case:** Select the destination namespace.

It seems is impossible to select the destination namespace.
There are no reference in the [documentation](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/README.md) how it is possible to add it in values.yaml, taking a quick look in the charts directory it seems not implemented.

eg. https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/charts/operate/templates/deployment.yaml

**Describe the enhancement/feature:** The possibility to set the namespace destination in the global values.

eg.
```yaml
global:
  annotations: {}
  namespace: <desired-namespace>
  labels:
    app: camunda-platform
...
```
