### ISSUE TITLE
[ENHANCEMENT] Set %_ENTERPRISE for C8 components under Global section

### ISSUE THREAD

**Issue by renzpatriarca** [camunda/camunda-platform-helm#563]
**Describe the use case:**
Set license config in global section instead of individual components in values.yaml.

**Describe the enhancement/feature:**
The possibility to set the license config in the global values.

From:

Operate/Tasklist/Identity/Optimize
```
operate:
  enabled: true
​  # Env can be used to set extra environment variables in each zeebe broker container
  env:
    - name: %_ENTERPRISE
      value: ****
```

To:
```
global:
...
  env:
    -name: OPERATE_ENTERPRISE
      value: ****
    -name: TASKLIST_ENTERPRISE
      value: ****
    -name: IDENTITY_ENTERPRISE
      value: ****
    -name: OPTIMIZE_ENTERPRISE
      value: ****
```
