### ISSUE TITLE
[ENHANCEMENT] add support to configure the zeebe oauth interceptor

### ISSUE THREAD

**Issue by megglos** [camunda/camunda-platform-helm#608]
**Describe the use case:**

With 8.2.0 Zeebe got support for Camunda Identity OAuth token validation with https://github.com/camunda/product-hub/issues/120 .

Similar as to how support for it was added to https://github.com/camunda/camunda-platform/issues/104, it should be added to the helm chart as well for users to make use of.

**Describe the enhancement/feature:**

**Desired outcome and acceptance tests:**

- [x] allow to configure token based auth on the zeebe gateway
- [x] enabled it by default (to make security the default)

**Comment by ManuelDittmar** [comment]
if someone else ends up in this issue, here is an example how you can configure the interceptor via environment variables:

```
zeebe-gateway:
  env:
   - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_TYPE
     value: "keycloak"
   - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
     value: "identity"
   - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_ISSUERBACKENDURL
     value: "http://keycloak.localhost/auth/realms/camunda-platform"
   - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_AUDIENCE
     value: "zeebe-api"
```

```
identity:
  env: 
   - name: KEYCLOAK_INIT_ZEEBE_NAME
     value: "zeebe"
   - name: KEYCLOAK_CLIENTS_0_NAME
     value: "zeebe"
   - name: KEYCLOAK_CLIENTS_0_ID
     value: "my-id"
   - name: KEYCLOAK_CLIENTS_0_SECRET
     value: "my-secret"
   - name: KEYCLOAK_CLIENTS_0_TYPE
     value: "M2M"
   - name:  KEYCLOAK_CLIENTS_0_PERMISSIONS_0_RESOURCE_SERVER_ID
     value: "zeebe-api"
   - name:  KEYCLOAK_CLIENTS_0_PERMISSIONS_0_DEFINITION
     value: "write:*"
   - name: IDENTITY_AUTH_PROVIDER_ISSUER_URL
     value: "http://keycloak.localhost/auth/realms/camunda-platform"
```
```
tasklist:
  env: 
   - name: ZEEBE_CLIENT_ID
     value: my-id
   - name: ZEEBE_CLIENT_SECRET
     value: my-secret
   - name: ZEEBE_TOKEN_AUDIENCE
     value: zeebe-api
```

```
operate:
  env: 
   - name: ZEEBE_CLIENT_ID
     value: my-id
   - name: ZEEBE_CLIENT_SECRET
     value: my-secret
   - name: ZEEBE_TOKEN_AUDIENCE
     value: zeebe-api
```

**Comment by aabouzaid** [comment]
Released in [v8.2.3](https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-8.2.3) :heavy_check_mark:

**Comment by mashkovd** [comment]
Hello, 

i set env for zeebe-gateway as 

```
  env:
  - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
    value: "identity"
  - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_ISSUERBACKENDURL
    value: "http://keycloak.my.domain/auth/realms/camunda-platform"
  - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_AUDIENCE
    value: "zeebe-api"
  - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_TYPE
    value: "keycloak"
```

and try to connect to zeebe with zbctl command 

zbctl --insecure --address zeebe.my.domain:26500 status --clientId zeebe --clientSecret YReGrXFGYp --authzUrl http://keycloak.my.domain/auth/realms/camunda-platform

![image](https://github.com/camunda/camunda-platform-helm/assets/1842423/33870487-0264-4f81-ae83-a1621d0b409c)

and get following message 
_2023/10/30 16:24:33 Warning: The configured security level does not guarantee that the credentials will be confidential. If this unintentional, please enable transport security.

Error: rpc error: code = Canceled desc = failed to apply token: failed to obtain access token: oauth2: "RESTEASY003650: No resource method found for POST, return 405 with Allow header"_


also I cant' connect by local modeler
![image](https://github.com/camunda/camunda-platform-helm/assets/1842423/94203aa9-715d-40f7-83a7-2fc5b9b800a4)

What's I do wrong? Thx
