### ISSUE TITLE
[ISSUE] Setting contextPath for operate tasklist and optimize breaks Kubernetes probes

### ISSUE THREAD

**Issue by hostalp** [camunda/camunda-platform-helm#628]
**Describe the issue:**

If configuring the Helm chart for ocmbined Ingress
https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup/#combined-ingress-setup
particularly
```yaml
operate:
  contextPath: "/operate"

tasklist:
  contextPath: "/tasklist"

optimize:
  contextPath: "/optimize"
```
Kubernetes probes (readiness probes are enabled by default here) break due to invalid URLs being used by them.
This can be worked around by modifying the `probePath` values and adding the `contextPath` prefixes in there, but it shouldn't be necessary. It should be handled by the chart.

```yaml
operate:
  contextPath: "/operate"

  readinessProbe:
    probePath: /operate/actuator/health/readiness

tasklist:
  contextPath: "/tasklist"

  readinessProbe:
    probePath: /tasklist/actuator/health/readiness

optimize:
  contextPath: "/optimize"

  readinessProbe:
    probePath: /optimize/api/readyz
```

Note that **identity** is likely affected as well, however its default `probePath: /actuator/health` doesn't seem to work even without the `contextPath` specifically set so I can't really verify that one.

**Environment:**

- Platform: Kubernetes 1.24.9
- Helm CLI version: 3.11.1
- Chart version: 8.2.0
