### ISSUE TITLE
[ISSUE] web-modeler-restapi pod fails to start because it does not honor the value specified for `postgresql.auth.existingSecret`

### ISSUE THREAD

**Issue by daniel-ewing** [camunda/camunda-platform-helm#644]
**Describe the issue:**

Create a values.yaml that specifies secrets for all components using the respective `existingSecret` configuration.  This works for all components, except for the `web-modeler-restapi` pod.  This pod seems to have a hard-coded / required secret with the specific name `<deploymentName>-postgresql-web-modeler`.

**Actual behavior:**

All pods start except the  `web-modeler-restapi` pod  This pod fails to start, `kubectl describe pod` indicates:
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  2m30s                 default-scheduler  Successfully assigned default/dev-web-modeler-restapi-855c955667-xxn5d to minikube
  Warning  Failed     17s (x12 over 2m26s)  kubelet            Error: secret "dev-postgresql-web-modeler" not found
  Normal   Pulled     5s (x13 over 2m26s)   kubelet            Container image "registry.camunda.cloud/web-modeler-ee/modeler-restapi:8.2.1" already present on machine
```

**Expected behavior:**

All pods start.

**How to reproduce:**

1. Create TLS CRT and KEY.
2. Create generic secret with TLS CRT and KEY.
3. Create all secrets as specified in [separated-ingress-secrets-values.yaml](https://github.com/daniel-ewing/camunda-platform-helm/blob/f43688fa5a36749a2ce4fa60ebc0fcaae0aad943/dev-8.2.x-tests/separated-ingress-secrets-values.yaml).
4. Install [separated-ingress-secrets-values.yaml](https://github.com/daniel-ewing/camunda-platform-helm/blob/f43688fa5a36749a2ce4fa60ebc0fcaae0aad943/dev-8.2.x-tests/separated-ingress-secrets-values.yaml).
```
openssl req -newkey rsa:4096 \
            -x509 \
            -sha256 \
            -days 9999 \
            -nodes \
            -addext "subjectAltName = DNS:connectors.c8.dev.local,DNS:identity.c8.dev.local,DNS:keycloak.c8.dev.local,DNS:modeler.c8.dev.local,DNS:operate.c8.dev.local,DNS:optimize.c8.dev.local,DNS:tasklist.c8.dev.local,DNS:websockets.c8.dev.local,DNS:zeebe.c8.dev.local" \
            -out dev.c8.separate.crt \
            -keyout dev.c8.separate.key \
            -subj "/CN=c8.dev.local"

kubectl create secret generic dev-c8-separated \
                        --from-file=tls.crt=dev.c8.separate.crt \
                        --from-file=tls.key=dev.c8.separate.key

kubectl create secret docker-registry dev-c8-registry \
                                --docker-server=valueHere \
                                --docker-username=valueHere \
                                --docker-password='valueHere' \
                                --docker-email=valueHere

kubectl create secret generic dev-identity-secrets \
                              --from-literal=operate-secret=SetThisToMakeUpgradeEasy \
                              --from-literal=tasklist-secret=SetThisToMakeUpgradeEasy \
                              --from-literal=optimize-secret=SetThisToMakeUpgradeEasy \
                              --from-literal=connectors-secret=SetThisToMakeUpgradeEasy

kubectl create secret generic dev-identity-keycloak-secrets \
                              --from-literal=admin-password=SetThisToMakeLoginEasy \
                              --from-literal=management-password=SetThisToMakeLoginEasy \

kubectl create secret generic dev-identity-keycloak-postgresql-secrets \
                              --from-literal=password=SetThisToMakeLoginEasy \
                              --from-literal=postgres-password=SetThisToMakeLoginEasy

kubectl create secret generic dev-modeler-postgresql-secrets \
                              --from-literal=password=SetThisToMakeLoginEasy \
                              --from-literal=postgres-password=SetThisToMakeLoginEasy

helm install dev camunda/camunda-platform \
                          -f separated-ingress-tls-secrets-values.yaml \
	                  --version 8.2.2
```

**Logs:**

Relevant snippet above.

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: minikube
- Helm CLI version: 3.11.3
- Chart version: 8.2.2
- Values file:  [separated-ingress-secrets-values.yaml](https://github.com/daniel-ewing/camunda-platform-helm/blob/f43688fa5a36749a2ce4fa60ebc0fcaae0aad943/dev-8.2.x-tests/separated-ingress-secrets-values.yaml)

**Comment by aabouzaid** [comment]
@daniel-ewing Thanks for reporting this issue.
The values file is not found in the repo. (It's always better to use a link with a permanent commit so it will not be lost after a while)

**Comment by daniel-ewing** [comment]
Hi @aabouzaid, I fixed the description.  It was the same values file indicated in steps 3 and 4 which had valid links.  Also, if it help, see [here for how I created the secrets](https://github.com/daniel-ewing/camunda-platform-helm/blob/dev-tests/misc/runbooks/lin-install-c8-separated-tls-secrets.txt#L24-L42).

**Comment by jessesimpson36** [comment]
Hey @daniel-ewing ,   according to your ticket, you want an example configuration that sets all existingSecrets, and if that is satisfied, then we can be sure that this issue is not present in the later releases of the helm chart.

During a recent epic where we are hoping to remove the secrets extraction step from our upgrade procedure (by introducing warnings encouraging users to set these existingSecrets)
https://github.com/camunda/product-hub/issues/1957
https://github.com/camunda/camunda-platform-helm/issues/1868

I have reworked my configuration options, so that when I test, I am always specifying my secrets explicilty.  The following is the config that I use:

```yaml
global:
  image:
    pullSecrets: 
      - name: registrycamundacloud
      - name: dockerhub-pat
  ingress:
    enabled: true
    className: ingress-nginx
    host: dev.jlscode.com
    tls:
      enabled: true
      secretName: jlscode-dev
  identity:
    auth:
      publicIssuerUrl: "https://dev.jlscode.com/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://dev.jlscode.com/operate"
        existingSecret:
          name: camunda-secrets
      optimize:
        redirectUrl: "https://dev.jlscode.com/optimize"
        existingSecret:
          name: camunda-secrets
      tasklist:
        redirectUrl: "https://dev.jlscode.com/tasklist"
        existingSecret:
          name: camunda-secrets
      webModeler:
        redirectUrl: "https://dev.jlscode.com/modeler"    
        existingSecret:
          name: camunda-secrets
      console:
        redirectUrl: "https://dev.jlscode.com"
        existingSecret:
          name: camunda-secrets
      connectors:
        existingSecret:
          name: camunda-secrets
      zeebe:
        existingSecret:
          name: camunda-secrets

connectors:
  contextPath: /connectors
  enabled: true
  ingress:
    className: ingress-nginx

prometheusServiceMonitor:
  enabled: false
  labels:
    release: kube-prometheus-stack

identity:
  contextPath: /identity
  firstUser:
    enabled: true
  ingress:
    className: ingress-nginx

identityKeycloak:
  proxy: edge
  ingress:
    ingressClassName: ingress-nginx
  auth:
    existingSecret: camunda-secrets
  postgresql:
    auth:
      existingSecret: camunda-secrets

identityPostgresql:
  enabled: true
  auth:
    existingSecret: camunda-secrets

    
operate:
  contextPath: /operate
  ingress:
    className: ingress-nginx
  
optimize:
  contextPath: /optimize
  ingress:
    className: ingress-nginx
  
tasklist:
  contextPath: /tasklist
  ingress:
    className: ingress-nginx

webModeler:
  contextPath: /modeler
  enabled: true
  ingress:
    className: ingress-nginx
  restapi:
    mail:
      smtpHost: fakehost
      smtpPort: 587
      smtpUser: fakeuser
      # smtpPassword: fakepassword
      # email address to be displayed as sender of emails from Web Modeler
      fromAddress: fake@fake.com
      existingSecret:
        name: camunda-secrets


postgresql:
  enabled: true
  auth:
    existingSecret: camunda-secrets

zeebe:
  enabled: true
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"

zeebeGateway: 
  contextPath: /zeebe
  replicas: 1
  affinity: {}
  ingress:
    grpc:
      className: ingress-nginx
      enabled: true
      annotations:
        ingress.kubernetes.io/rewrite-target: "/"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC" 
        ingress.kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      path: /zeebe
      host: zeebe-gateway.dev.jlscode.com
      tls:
        enabled: true
        secretName: "jlscode-dev"
    rest:
      className: ingress-nginx

elasticsearch:
  esMajorVersion: "8"
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  replicas: 1
  antiAffinity: "soft"
  master:
    replicaCount: 1

console:
  enabled: true
  contextPath: "/"
  ingress:
    enabled: false
    className: ingress-nginx
  image:
    pullSecrets:
    - name: registrycamundacloud
    - name: index-docker-io

```

There are some differences between my `values.yaml` and the one you specified in this ticket:
https://github.com/daniel-ewing/camunda-platform-helm/blob/e7b3e8c825fb8d43e5295b2353f40315d510e103/dev-10.0.x-tests/separated-ingress-secrets-values.yaml#L114-L127

I noticed this section is setting `identityPostgresql.auth.existingSecret` which is the postgresql  used by identity  when multitenancy or resource-based authorizations are enabled,  however, you are not setting `identityKeycloak.postgresql.auth.existingSecret`  which is the postgresql that keycloak uses.

As for web-modeler-restapi,  I think there may have been a bug in the 8.2/8.3 releases that we fixed but did not update this ticket for.  When I test using my above configuration on 8.5, I found that the secret was properly referencing `camunda-secrets`. I also exec'd into the pod to verify that I can log in with the password provided in the secret.

I think this github issue may be closed, but please let me know if  things aren't  working on newer versions after you specify `identityKeycloak.postgresql.auth.existingSecret` and `postgresql.auth.existingSecret`.

**Comment by daniel-ewing** [comment]
OK, I confirm it works in CHC 10.3.2.  The last version I tried was 10.0.x where it still insisted on using `<deploymentName>-postgresql-web-modeler` for the WM postgresql secret.  The only secret I can't see how to set ahead of time and provide via values.yaml is this one:
![image](https://github.com/user-attachments/assets/0a245827-5477-4a58-bf87-b29d1eaf8014)

**Comment by jessesimpson36** [comment]
I think you're right about `RESTAPI_PUSHER_SECRET`.  It looks like the secretKeyRef is coded to be the "webmodeler.fullname" which is c8-web-modeler in your case.

https://github.com/camunda/camunda-platform-helm/blob/e9ffb23292a0a3886cb4612a0e09d594dc7d32d4/charts/camunda-platform-latest/templates/web-modeler/deployment-restapi.yaml#L64-L68

This should be changed.  I'll check if there is an issue related to specifically that variable.

A workaround can be to set `webModeler.restapi.env` and define the `RESTAPI_PUSHER_SECRET` again.  if an env var is defined multiple times, the last one is used.

**Comment by jessesimpson36** [comment]
I linked the above ticket as a more specific branch off of this issue. If that is the only occurrence with this issue where you can't configure the secret, then I think we can close this issue.

**Comment by daniel-ewing** [comment]
So I can use:
```
webModeler:
  restapi:
    env:
      - name: RESTAPI_PUSHER_SECRET 
        valueFrom: 
          secretKeyRef: 
            name: c8-pusher-secret
            key: pusher-app-secret 
```
And create `c8-pusher-secret`:
```
kubectl create secret generic c8-pusher-secret \
                              --from-literal=pusher-app-secret=WhatDoesThisSecretDoOrControl,AnyWay?
```
?
