### ISSUE TITLE
Create a realm on keycloak as camunda-platform even if I want to change the name of the keycloak realm

### ISSUE THREAD

**Issue by aytemuryakup** [camunda/camunda-platform-helm#706]
**Describe the issue:**
I am providing external keycloak connection in this loop.
I want to use common keycloak for dev and test environment. For this reason, I want to change the realm names created on keycloak based on environment.
For example
for dev camunda --> camunda-platform-dev
for test camunda --> camunda-platform-test

For this, when I change the relevant field under auth, it creates a realm named **camunda-platform** on the included keycloak.
The fields I changed on the helm are as follows
```
common:
  exampleValue: common-chart
  global:
    identity:
      auth:
        connectors:
          existingSecret: ''
        enabled: true
        operate:
          existingSecret: null
          redirectUrl: https://operate.od.test.lab.local
        optimize:
          existingSecret: null
          redirectUrl: https://optimize.od.test.lab.local
        publicIssuerUrl: https://keycloak.lab.local/realms/camunda-platform-test
        tasklist:
          existingSecret: null
          redirectUrl: https://tasklist.od.test.lab.local
      image:
        pullSecrets: null
        registry: ''
        repository: camunda/identity
      keycloak:
        auth:
          adminUser: keyadmin
          existingSecret: keycloak-admin
          existingSecretKey: admin-password
        contextPath: /
        internal: false
        realm: realms/camunda-platform-test
        url:
          host: keycloak.lab.local
          port: '443'
          protocol: https
```
`common.global.keycloak.realm: camunda-platform-test ` When I change this field, I expect it to create a realm like the value I entered, but it creates a realm with the name **camunda-platform**.

The realm image created on keycloak is as follows.
<img width="397" alt="Screenshot 2023-05-24 at 11 29 55" src="https://github.com/camunda/camunda-platform-helm/assets/34859799/e2c80b9f-211f-4d66-b687-98e5863c0cf6">

- Platform: 8.2.3
- Helm CLI version: v3.8.2 
- Chart version:  8.2.2
- Keycloak version: 19.0.1

**Comment by aabouzaid** [comment]
@aytemuryakup could you please try to use the following to see if it will work:

```
identity:
  env:
  - name: "KEYCLOAK_REALM"
    value: camunda-platform-dev
```
