### ISSUE TITLE
[TASK] Wrong ServiceMonitor port in Identity

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#733]
**Describe the issue:**

ServiceMonitor in charts/camunda-platform/templates/service-monitor.yaml is set to extract from the port with label "http", which means port 8080 for the identity pod. However, the identity pod exposes it's metrics on the port 8082 which is labeled "metrics".

Note: to reproduce this, you must have the servicemonitor enabled:
```
prometheusServiceMonitor:
  enabled: true
```
And install the [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) operator

**Actual behavior:**

Find a metric via exec'ing into the identity pod and running:
```
wget http://127.0.0.1:8082/actuator/prometheus -O - 
```

In this case, I will use `system_cpu_count`.  In Grafana explore, input the following query:
```
system_cpu_count{container="identity"}
``` 
No results in the grafana query.
![2023-06-06-154853_grim](https://github.com/camunda/camunda-platform-helm/assets/19277629/7a552865-cb16-4f02-9a3e-c6472b0798ff)

You can also see that if you try to access `/actuator/prometheus` on port 8080, the result is a 403 error:
```
/app # wget http://127.0.0.1:8080/actuator/prometheus -O - 
Connecting to 127.0.0.1:8080 (127.0.0.1:8080)
wget: server returned error: HTTP/1.1 403 
```

**Expected behavior:**

Expected behavior is to be able to query the metrics exposed from the pod inside grafana.

In Grafana explore, input the following query:
```
system_cpu_count{container="identity"}
``` 
![2023-06-06-154707_grim](https://github.com/camunda/camunda-platform-helm/assets/19277629/844aedbf-606f-432e-9d56-09c302d2b1d5)

**How to reproduce:**

[promservmonitor-values.yaml.txt](https://github.com/camunda/camunda-platform-helm/files/11668565/promservmonitor-values.yaml.txt)

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: Kind cluster
- Helm CLI version: version.BuildInfo{Version:"v3.11", GitCommit:"", GitTreeState:"", GoVersion:"go1.20.2"}
- Chart version: 8.2.5
- Values file: [promservmonitor-values.yaml.txt](https://github.com/camunda/camunda-platform-helm/files/11668565/promservmonitor-values.yaml.txt)

Related to [SUPPORT-17949](https://jira.camunda.com/browse/SUPPORT-17949)

**Comment by jessesimpson36** [comment]
One solution would be to add the following to 
```
...
  - honorLabels: true
    interval: 10s
    path: /actuator/prometheus
    port: metrics
...
```

It also may be possible to get the identity pod to not require authentication to access the actuator endpoints.

**Comment by freakapoorv** [comment]
Hie Team,

While we are enabling the service Monitor, it says that it will monitor the port named  HTTP
```
  endpoints:
    - honorLabels: true
      path: /actuator/prometheus
      port: http
      interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
```

if you check the identity section of the chart, it says that the port named  HTTP corresponds to port no 8080 and metrics are available at port no 8082 as per the official documentation.

  ```
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8082
          name: metrics
          protocol: TCP
```
Hence, from the service monitor it says that Identity is down as no metrics are avalible at the PORT named HTTP for identity.

**Comment by jessesimpson36** [comment]
@freakapoorv ,
A temporary workaround is to create a new ServiceMonitor for the identity pod.
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 2
  name: <RELEASE_NAME>-identity
  namespace: <NAMESPACE>
spec:
  endpoints:
  - honorLabels: true
    interval: 10s
    path: /actuator/prometheus
    port: metrics
  selector:
    matchLabels:
      app: camunda-platform
      app.kubernetes.io/component: identity
```
And ensuring to replace <RELEASE_NAME> and <NAMESPACE> with your release name and namespace.
