### ISSUE TITLE
[ISSUE] Can't run Zeebe as Non-Root

### ISSUE THREAD

**Issue by floric** [camunda/camunda-platform-helm#761]
**Describe the issue:**

Because of security reasons I need to be able to run all Camunda pods as non-root. For most components this works perfectly, except Zeebe.

I use this config for all components on AWS EKS:

```
containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
```

**Actual behavior:**

Startup fails with:
```
[FATAL tini (7)] exec /usr/local/bin/startup.sh failed: Permission denied
```

**Expected behavior:**

Zeebe starts and runs successfully.

**How to reproduce:**

Use config from above nested in `zeebe.containerSecurityContext`.

**Logs:**

```
[FATAL tini (7)] exec /usr/local/bin/startup.sh failed: Permission denied
```

**Environment:**

- Platform: AWS
- Chart version: 8.2.6
- Values file: example above

**Comment by floric** [comment]
Solved by using the following configuration :)

```
containerSecurityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
podSecurityContext:
  fsGroup: 1001
```
