### ISSUE TITLE
[ENHANCEMENT] Allow for easier modification of Optimizes environment-config.yaml

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#787]
**Describe the use case:**

According to our [documentation](https://docs.camunda.io/optimize/self-managed/optimize-deployment/configuration/system-configuration/#java-system-properties--os-environment-variable-placeholders) for optimize, they allow specifying a config file named `environment-config.yaml` with a series of options that our helm chart does not expose.  In this particular support ticket, the customer wanted to modify `es.settings.index.number_of_shards`. We are currently unable to modify this via environment variables or overriding the command.  What I proposed was creating a ConfigMap

```
apiVersion: v1
data:
  environment-config.yaml: |
    es:
      settings:
        index:
          number_of_shards: 5
kind: ConfigMap
metadata:
  name: optimizeapplicationconfig
  namespace: default

```
And then modifying the extraVolumes and extraVolumeMounts inside the optimize section of values.yaml

```
optimize:
  extraVolumes:
  - configMap:
      defaultMode: 0777
      name: optimizeapplicationconfig
    name: environmentconfig
  extraVolumeMounts:
  - mountPath: /optimize/config/environment-config.yaml
    name: environmentconfig
    subPath: environment-config.yaml
```

With these options set, the application successfully changes the number of shards as shown by the screenshot:
![2023-07-13-115735_grim](https://github.com/camunda/camunda-platform-helm/assets/19277629/f9af9c02-3516-4b69-ba5b-ed8721f75313)

There are 10 shards, 1 primary and 1 replica shard for each 5 shards.

**Describe the enhancement/feature:**

I think the best way to handle this is by having the configmap,  volume, and volumeMount defined in the helm chart templates and the environment-config.yaml file being empty.  A customer could override it manually if they want.  Or perhaps we could have an option for a customer to specify their own configmap for environment-config.yaml.

**Desired outcome and acceptance tests:**

A user should be able to configure their Optimize instance without extra volume mounts.

Related to: [SUPPORT-17609](https://jira.camunda.com/browse/SUPPORT-17609)
