### ISSUE TITLE
[ENHANCEMENT] Configure Backup Store and Repository Name via Helm Chart

### ISSUE THREAD

**Issue by ManuelDittmar** [camunda/camunda-platform-helm#846]
**Describe the use case:**
I want to configure backup store of Zeebe via the Helm Chart
https://docs.camunda.io/docs/self-managed/backup-restore/zeebe-backup-and-restore/#s3-backup-store 

I want to configure the Repository Names via the Helm Chart

https://docs.camunda.io/docs/self-managed/backup-restore/operate-tasklist-backup/#prerequisites

Current Option via Environment Variables:

```
zeebe:
  env:
# Backup
  - name: ZEEBE_BROKER_DATA_BACKUP_STORE
    value: "S3"
  - name: ZEEBE_BROKER_DATA_BACKUP_S3_BUCKETNAME
    value: "c8-backup"
  - name: ZEEBE_BROKER_DATA_BACKUP_S3_FORCEPATHSTYLEACCESS
    value: "true"
  - name: ZEEBE_BROKER_DATA_BACKUP_S3_ENDPOINT
    value: "http://minio.default.svc.cluster.local:9000"
  - name: ZEEBE_BROKER_DATA_BACKUP_S3_ACCESSKEY
    value: "K6VObp9bS8E1dfUDoAlu"
  - name: ZEEBE_BROKER_DATA_BACKUP_S3_SECRETKEY
    value: "KhLkAJ7Llw0hfpTZfzuw5Cy1dGdhTwlQhvIQz3WO"
  - name: ZEEBE_BROKER_DATA_BACKUP_S3_REGION
    value: "us-east-1"

operate:
  enabled: true
  env:
# Repository
  - name: CAMUNDA_OPERATE_BACKUP_REPOSITORYNAME
    value: "repositoryName"

tasklist:
  enabled: true
  env:
# Repository
  - name: CAMUNDA_TASKLIST_BACKUP_REPOSITORYNAME
    value: "repositoryName"
```

**Describe the enhancement/feature:**

I would like to see something like this:

```
zeebe:
  backup:
    enabled: true
    bucketName: xxx
   ...
operate:
  backup:
    enabled: true
    repositoryName: name

tasklist:
  backup:
    enabled: true
    repositoryName: name

optimize:
  backup:
    enabled: true
    repositoryName: name
```

maybe it would even make sense to deploy minio as part of the helm chart (if enabled?)

**Desired outcome and acceptance tests:**

I can configure backups for all componenets via the helm chart.
