### ISSUE TITLE
[ISSUE] ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE env is not set in version 8.2.13

### ISSUE THREAD

**Issue by AndersRunningen** [camunda/camunda-platform-helm#917]
**Describe the issue:**

When we do helm install with 

```
zeebe-gateway:
  env:
  - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
    value: "none"
```
the config is not set in the Zeebe Gateway.

**Actual behavior:**

I use the custom values below:

```
global:
  ingress:
    enabled: true
    className: nginx
    host: camunda.xxxxx.xx
  identity:
    auth:
      # enabled: false
      publicIssuerUrl: "https://camunda.xxxxx.xx/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://camunda.xxxxx.xx/operate"

zeebe:
  pvcStorageClassName: managed-premium-retain
  podDisruptionBudget:
    enabled: true

zeebe-gateway:
  podDisruptionBudget:
    enabled: true
  ingress:
    enabled: true
    className: nginx
    host: "zeebe.camunda.xxxxx.xx"

  env:
  - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
    value: "none"

identity:
  contextPath: "/identity"
  fullURL: "https://camunda.xxxxx.xx/identity"

operate:
  env:
    - name: CAMUNDA_OPERATE_ENTERPRISE
      value: "true"
  contextPath: "/operate"

optimize:
  enabled: false

tasklist:
  enabled: false

connectors:
  enabled: false #8.2.X oppgradering

elasticsearch:
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: managed-premium-retain
    resources:
      requests:
        storage: 30Gi
  extraEnvs:
    - name: "ingest.geoip.downloader.enabled"
      value: "false"

retentionPolicy:
  enabled: true
  schedule: "0 1 * * *"
  zeebeIndexTTL: 10
```

With version 8.2.13 of the helmchart. I Upgrade from an running version 8.1.15 to 8.2.13 with the command:

```
helm upgrade camunda-platform camunda/camunda-platform --namespace camunda --version 8.2.13 --debug \
    --values camunda-values.yaml --values camunda-platform-values.yaml \
    --set global.identity.auth.tasklist.existingSecret=$TASKLIST_SECRET \
    --set global.identity.auth.optimize.existingSecret=$OPTIMIZE_SECRET \
    --set global.identity.auth.operate.existingSecret=$OPERATE_SECRET \
    --set global.identity.auth.connectors.existingSecret=$CONNECTORS_SECRET \
    --set identity.keycloak.auth.adminPassword=$KEYCLOAK_ADMIN_SECRET \
    --set identity.keycloak.auth.managementPassword=$KEYCLOAK_MANAGEMENT_SECRET \
    --set identity.keycloak.postgresql.auth.password=$POSTGRESQL_SECRET \
    --set global.postgresql.auth.postgresPassword=$POSTGRES_PASSWORD \
    --set global.identity.auth.zeebe.existingSecret=$ZEEBE_SECRET
```

(`camunda-values.yaml` is the `values.yaml` from the helmchart, `camunda-platform-values.yaml` is our custom config. 

The helm generated values is as expected from your documentation and previous comments [here](https://github.com/camunda/camunda-platform-helm/pull/634#issuecomment-1713607744).  

```
# Source: camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "camunda-platform-zeebe-gateway"
  labels:
    app: camunda-platform
    app.kubernetes.io/name: zeebe-gateway
    app.kubernetes.io/instance: camunda-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    helm.sh/chart: zeebe-gateway-8.2.13
    app.kubernetes.io/version: "8.2.13"
    app.kubernetes.io/component: zeebe-gateway
  annotations:
    {}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: camunda-platform
      app.kubernetes.io/name: zeebe-gateway
      app.kubernetes.io/instance: camunda-platform
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: camunda-platform
      app.kubernetes.io/component: zeebe-gateway
  template:
    metadata:
      labels:
        app: camunda-platform
        app.kubernetes.io/name: zeebe-gateway
        app.kubernetes.io/instance: camunda-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: camunda-platform
        helm.sh/chart: zeebe-gateway-8.2.13
        app.kubernetes.io/version: "8.2.13"
        app.kubernetes.io/component: zeebe-gateway
      annotations:
        {}
    spec:
      imagePullSecrets:
        []
      containers:
        - name: zeebe-gateway
          image: "camunda/zeebe:8.2.13"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9600
              name: http
            - containerPort: 26500
              name: gateway
            - containerPort: 26502
              name: internal
          env:
            - name: ZEEBE_STANDALONE_GATEWAY
              value: "true"
            - name: ZEEBE_GATEWAY_CLUSTER_CLUSTERNAME
              value: camunda-platform-zeebe
            - name: ZEEBE_GATEWAY_CLUSTER_MEMBERID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZEEBE_LOG_LEVEL
              value: "info"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+ExitOnOutOfMemoryError"
            - name: ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT
              value: camunda-platform-zeebe:26502
            - name: ZEEBE_GATEWAY_NETWORK_HOST
              value: 0.0.0.0
            - name: ZEEBE_GATEWAY_NETWORK_PORT
              value: "26500"
            - name: ZEEBE_GATEWAY_CLUSTER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ZEEBE_GATEWAY_CLUSTER_PORT
              value: "26502"
            - name: ZEEBE_GATEWAY_MONITORING_HOST
              value: 0.0.0.0
            - name: ZEEBE_GATEWAY_MONITORING_PORT
              value: "9600"
            - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_TYPE
              value: "keycloak"
            - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE <---------
              value: "identity"
            - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_ISSUERBACKENDURL
              value: "http://camunda-platform-keycloak:80/auth/realms/camunda-platform"
            - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_AUDIENCE
              value: "zeebe-api"
            - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE  <----------
              value: none
          volumeMounts:
          readinessProbe:
            httpGet:
              path: /actuator/health
              scheme: HTTP
              port: 9600
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 400m
              memory: 450Mi
            requests:
              cpu: 400m
              memory: 450Mi
      volumes:
        - name: config
          configMap:
            name: camunda-platform-zeebe-gateway-gateway
            defaultMode: 484
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - zeebe-gateway
            topologyKey: kubernetes.io/hostname
```

The applied manifest in Kubernetes looks like this:
```
k get deploy camunda-platform-zeebe-gateway -o yaml
apiVersion: apps/v1
kind: Deployment
  labels:
    app: camunda-platform
    app.kubernetes.io/component: zeebe-gateway
    app.kubernetes.io/instance: camunda-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zeebe-gateway
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/version: 8.2.13
    helm.sh/chart: zeebe-gateway-8.2.13
  name: camunda-platform-zeebe-gateway
  namespace: camunda
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: camunda-platform
      app.kubernetes.io/component: zeebe-gateway
      app.kubernetes.io/instance: camunda-platform
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: zeebe-gateway
      app.kubernetes.io/part-of: camunda-platform
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: camunda-platform
        app.kubernetes.io/component: zeebe-gateway
        app.kubernetes.io/instance: camunda-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: zeebe-gateway
        app.kubernetes.io/part-of: camunda-platform
        app.kubernetes.io/version: 8.2.13
        helm.sh/chart: zeebe-gateway-8.2.13
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - zeebe-gateway
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: ZEEBE_STANDALONE_GATEWAY
          value: "true"
        - name: ZEEBE_GATEWAY_CLUSTER_CLUSTERNAME
          value: camunda-platform-zeebe
        - name: ZEEBE_GATEWAY_CLUSTER_MEMBERID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ZEEBE_LOG_LEVEL
          value: info
        - name: JAVA_TOOL_OPTIONS
          value: -XX:+ExitOnOutOfMemoryError
        - name: ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT
          value: camunda-platform-zeebe:26502
        - name: ZEEBE_GATEWAY_NETWORK_HOST
          value: 0.0.0.0
        - name: ZEEBE_GATEWAY_NETWORK_PORT
          value: "26500"
        - name: ZEEBE_GATEWAY_CLUSTER_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ZEEBE_GATEWAY_CLUSTER_PORT
          value: "26502"
        - name: ZEEBE_GATEWAY_MONITORING_HOST
          value: 0.0.0.0
        - name: ZEEBE_GATEWAY_MONITORING_PORT
          value: "9600"
        - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_TYPE
          value: keycloak
        - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
          value: identity
        - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_ISSUERBACKENDURL
          value: http://camunda-platform-keycloak:80/auth/realms/camunda-platform
        - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_AUDIENCE
          value: zeebe-api
        image: camunda/zeebe:8.2.13
        imagePullPolicy: IfNotPresent
        name: zeebe-gateway
        ports:
        - containerPort: 9600
          name: http
          protocol: TCP
        - containerPort: 26500
          name: gateway
          protocol: TCP
        - containerPort: 26502
          name: internal
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /actuator/health
            port: 9600
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 400m
            memory: 450Mi
          requests:
            cpu: 400m
            memory: 450Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 484
          name: camunda-platform-zeebe-gateway-gateway
        name: config
```

And when looking for the env in the pod, identity is set as the `ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE`:

```
 k exec -it camunda-platform-zeebe-gateway-5549d49f4-44w5r -- /bin/bash
root@camunda-platform-zeebe-gateway-5549d49f4-44w5r:/usr/local/zeebe# echo $ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
identity
```

**Expected behavior:**

We expect that the helmchart is able to set the environment variable so `ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE` is configurable and we are able to set it to `none`

**How to reproduce:**

**Logs:**

**Environment:**
Dev/test/prod

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform:  AKS 1.27.3
- Helm CLI version:  `version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}`
- Chart version:  8.1.15 -> 8.2.15
- Values file: 
```
global:
  ingress:
    enabled: true
    className: nginx
    host: camunda.xxxxx.xx
  identity:
    auth:
      # enabled: false
      publicIssuerUrl: "https://camunda.xxxxx.xx/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://camunda.xxxxx.xx/operate"

zeebe:
  pvcStorageClassName: managed-premium-retain
  podDisruptionBudget:
    enabled: true

zeebe-gateway:
  podDisruptionBudget:
    enabled: true
  ingress:
    enabled: true
    className: nginx
    host: "zeebe.camunda.xxxxx.xx"

  env:
  - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
    value: "none"

identity:
  contextPath: "/identity"
  fullURL: "https://camunda.xxxxx.xx/identity"

operate:
  env:
    - name: CAMUNDA_OPERATE_ENTERPRISE
      value: "true"
  contextPath: "/operate"

optimize:
  enabled: false

tasklist:
  enabled: false

connectors:
  enabled: false #8.2.X oppgradering

elasticsearch:
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: managed-premium-retain
    resources:
      requests:
        storage: 30Gi
  extraEnvs:
    - name: "ingest.geoip.downloader.enabled"
      value: "false"

retentionPolicy:
  enabled: true
  schedule: "0 1 * * *"
  zeebeIndexTTL: 10
```

**Comment by AndersRunningen** [comment]
Side comment:
If applying the generated manifest manually outside helm, the value is set as expected.

**Comment by aabouzaid** [comment]
@AndersRunningen I think it's something related to YAML interpreting `none` and `null`.

Could you please try using `NONE` instead?

```
zeebe-gateway:
  env:
  - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
    value: "NONE"
```
