### ISSUE TITLE
[ISSUE] No longer possible to set StorageClass for Elastic Search

### ISSUE THREAD

**Issue by inghak** [camunda/camunda-platform-helm#948]
**Describe the issue:**

Previously we set the size and storage class of Elasticsearch in charts using `volumeClaimTemplate` i.e.:

```
volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "ssd"
    resources:
      requests:
        storage: 15Gi
```
From version 8 this no longer works, and is replaced by different syntaks `master` i.e:

```
master:
    masterOnly: false
    heapSize: 1024m
    persistence:
      size: 20Gi
```
But in the new master syntax there is no way to set `storageClassName` as before.

**Actual behavior:**

The storageclass is always "standard" and can not be changed

**Expected behavior:**

There should be property to set `storageClassName` in the new `master` syntaks.
It would also be approriate to set other properties like `accessModes` so that it will match previous functionality and support the standard configurations of `pvc`.

**How to reproduce:**
If you combine the `master`and `volumeClaimTemplate`, only `master`is used.

**Logs:**

**Environment:**
Kubernetes HELM chart

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: GCP
- Chart version: 8.3.0
