### ISSUE TITLE
[ISSUE] Elasticsearch Helm Chart configuration "extraConfig" from the parent Elasticsearch chart cannot be used

### ISSUE THREAD

**Issue by lukas-beumer** [camunda/camunda-platform-helm#977]
**Describe the issue:**

The update to 8.3.0 also uses a newer version of the Elasticsearch Helm Chart from Bitnami. Here, the setting of the configuration has probably changed somewhat.

However, the Camunda Helm Chart sets its own emptyDir on the corresponding path, which then in turn leads to an error if the "extraConfig: {}" parameter from the Bitnami Helm Chart. Error reads something like "Cannot parse config... is a directory". 

**Actual behavior:**

https://github.com/camunda/camunda-platform-helm/blob/fa5dae2fd59bbe9f227f344e8c36e7de4cc01b6b/charts/camunda-platform/values.yaml#L2978,L2979
The Elasticsearch cluster fails to start successfully and terminates with the corresponding error.

**Expected behavior:**

The Elasticsearch cluster stays healthy even with the extraConfig parameter set.

**How to reproduce:**

Use the following elasticsearch configuration:

```
camunda-platform:
  elasticsearch:
    enabled: true
    extraConfig:
      node:
        store:
          allow_mmap: false
      index:
        store:
          type: niofs
    sysctlImage:
      enabled: false
```

**Logs:**

Error reads something like "Elasticsearch Exception: Cannot parse config... is a directory". 

**Environment:**

Kubernetes (GKE)

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: GKE Kubernetes
- Helm CLI version: 3.12.2
- Chart version: 8.3.0
- Values file: see above
