### ISSUE TITLE
[BUG] Connectors failing to start due to going to legacy Keycloak URL for Token

### ISSUE THREAD

**Issue by ChrisJBurns** [camunda/camunda-platform-helm#978]
**Describe the issue:**

Connectors pod is failing to start because it keeps trying to go to the following path for a token: `POST /auth/realms/realms/camunda-platform/protocol/openid-connect/token`. These logs are from our istio sidecar. In the connectors container we get `An attempt to connect to Operate failed: io.camunda.operate.exception.OperateException: Error 404 obtaining access token : Not Found` before it eventually crashes and restarts container.

**Expected behavior:**

I expect the connectors container to start without issue and not use the old `/auth/` path. I have set the context to `/` because we are using keycloak v19.

**How to reproduce:**
Using the Chart, here is my values file:
```yaml
    global:
      image:
        registry: our.registry
      identity:
        auth:
          enabled: true
          publicIssuerUrl: "https://auth.test.our.domain/realms/camunda-platform"
          connectors:
            existingSecret: camunda-connectors-identity-secret
          operate:
            redirectUrl: https://camunda-operate.test.our.domain
            existingSecret: camunda-operate-identity-secret
          tasklist:
            existingSecret: camunda-tasklist-identity-secret
            redirectUrl: https://camunda-tasklist.test.our.domain
          optimize:
            existingSecret: camunda-optimize-identity-secret
            redirectUrl: https://camunda-optimize.test.our.domain
          zeebe:
            existingSecret: camunda-zeebe-identity-secret
        keycloak:
          internal: true
          legacy: false
          url:
            protocol: "http"
            host: "auth-idp.apps"
            port: 80
          contextPath: "/"
          realm: "realms/camunda-platform"
          # auth:
          #   adminUser: "admin"
          #   existingSecret: "camunda-keycloak"
          #   existingSecretKey: "admin-password"
    zeebe:
      image:
        repository: third-party/camunda/zeebe
        tag: 8.3.0 # {"$imagepolicy": "flux-system:camunda-zeebe:tag"}
    zeebe-gateway:
      image:
        repository: third-party/camunda/zeebe
        tag: 8.3.0  # {"$imagepolicy": "flux-system:camunda-zeebe:tag"}
    operate:
      image:
        repository: third-party/camunda/operate
        tag: 8.3.0 # {"$imagepolicy": "flux-system:camunda-operate:tag"}
    tasklist:
      image:
        repository: third-party/camunda/tasklist
        tag: 8.3.0 # {"$imagepolicy": "flux-system:camunda-tasklist:tag"}
    connectors:
      image:
        repository: third-party/camunda/connectors-bundle
        tag: 8.3.0 # {"$imagepolicy": "flux-system:camunda-connectors-bundle:tag"}
      env:
      - name: CAMUNDA_OPERATE_CLIENT_KEYCLOAK-URL
        value: "http://auth-idp.apps:80"
    optimize:
      image:
        repository: third-party/camunda/optimize
        tag: 3.11.0 # {"$imagepolicy": "flux-system:camunda-optimize:tag"}
      podLabels:
        sidecar.istio.io/inject: "false"
    identity:
      image:
        repository: third-party/camunda/identity
        tag: 8.3.0 # {"$imagepolicy": "flux-system:camunda-identity:tag"}
      keycloak:
        enabled: false
        httpRelativePath: "/"
      env:
        - name: IDENTITY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: camunda-keycloak
              key: admin-password
        - name: KEYCLOAK_REALM
          value: camunda-platform
        - name: KEYCLOAK_SETUP_REALM
          value: camunda-platform
```

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: AWS EKS
- Helm CLI version: 3.11.2
- Chart version:8.3.0
